import { SubTopic } from '../data-types';

export const dailyRoutineChange: SubTopic = {
    id: 'daily-routine-change',
    title: 'Daily routine & Change',
    type: '事件题',
    color: 'blue',
    isNew: true,
    words: [
      { word: 'frequently', phonetic: '/ˈfriːkwəntli/', definition: '频繁地', example: 'I frequently change my hairstyle.', emoji: 'https://em-content.zobj.net/source/apple/391/repeat-button_1f501.png' },
      { word: 'regret', phonetic: '/rɪˈɡret/', definition: '后悔', example: 'She doesn\'t regret the changes she has made in her life.', emoji: 'https://em-content.zobj.net/source/apple/391/woman-facepalming_1f926-200d-2640-fe0f.png' },
      { word: 'adapt', phonetic: '/əˈdæpt/', definition: '适应', example: 'Animals need to adapt to environmental changes to survive.', emoji: 'https://em-content.zobj.net/source/apple/391/lizard_1f98e.png' },
      { word: 'unexpected', phonetic: '/ˌʌnɪkˈspektɪd/', definition: '意想不到的', example: 'The sudden change in weather was completely unexpected.', emoji: 'https://em-content.zobj.net/source/apple/391/exploding-head_1f92f.png' },
      { word: 'transform', phonetic: '/trænsˈfɔːrm/', definition: '改变；转变', example: 'The internet has transformed the way people communicate.', emoji: 'https://em-content.zobj.net/source/apple/391/butterfly_1f98b.png' },
      { word: 'adjust', phonetic: '/əˈdʒʌst/', definition: '调整', example: 'You may need to adjust your plans if things change.', emoji: 'https://em-content.zobj.net/source/apple/391/wrench_1f527.png' },
      { word: 'wake up', phonetic: '/weɪk ʌp/', definition: '醒来', example: 'I wake up at 7 AM every morning.', emoji: 'https://em-content.zobj.net/source/apple/391/alarm-clock_23f0.png' },
      { word: 'commute', phonetic: '/kəˈmjuːt/', definition: '通勤', example: 'My daily commute to work takes about an hour.', emoji: 'https://em-content.zobj.net/source/apple/391/train_1f686.png' },
      { word: 'schedule', phonetic: '/ˈskedʒuːl/', definition: '日程安排', example: 'I have a very busy schedule today.', emoji: 'https://em-content.zobj.net/source/apple/391/calendar_1f4c5.png' },
      { word: 'fulfill', phonetic: '/fʊlˈfɪl/', definition: '履行；满足', example: 'It\'s satisfying to fulfill all the tasks on my to-do list.', emoji: 'https://em-content.zobj.net/source/apple/391/check-mark-button_2705.png' },
      { word: 'productive', phonetic: '/prəˈdʌktɪv/', definition: '富有成效的', example: 'I had a very productive morning and finished my report.', emoji: 'https://em-content.zobj.net/source/apple/391/flexed-biceps_1f4aa.png' },
      { word: 'balance', phonetic: '/ˈbæləns/', definition: '平衡', example: 'Finding a good work-life balance is crucial for well-being.', emoji: 'https://em-content.zobj.net/source/apple/391/balance-scale_2696-fe0f.png' },
      { word: 'incorporate', phonetic: '/ɪnˈkɔːrpəreɪt/', definition: '包含；合并', example: 'I try to incorporate at least 30 minutes of exercise into my daily routine.', emoji: 'https://em-content.zobj.net/source/apple/391/puzzle-piece_1f9e9.png' },
      { word: 'cooperate', phonetic: '/koʊˈɑːpəreɪt/', definition: '合作', example: 'We need to cooperate to change our daily routine for the better.', emoji: 'https://em-content.zobj.net/source/apple/391/handshake_1f91d.png' },
      { word: 'alter', phonetic: '/ˈɔːltər/', definition: '改变；修改', example: 'We\'ve had to alter our daily routine because of the new schedule.', emoji: 'https://em-content.zobj.net/source/apple/391/artist-palette_1f3a8.png' },
      { word: 'initial', phonetic: '/ɪˈnɪʃl/', definition: '最初的', example: 'My initial plan for the day was to go jogging, but it rained.', emoji: '🥇' },
      { word: 'initially', phonetic: '/ɪˈnɪʃəli/', definition: '最初；开头', example: 'Initially, I found it hard to wake up early, but now I\'m used to it.', emoji: 'https://em-content.zobj.net/source/apple/391/chequered-flag_1f3c1.png' },
      { word: 'conscious', phonetic: '/ˈkɑːnʃəs/', definition: '有意识的；意识到的', example: 'I made a conscious decision to change my morning routine.', emoji: 'https://em-content.zobj.net/source/apple/391/brain_1f9e0.png' },
      { word: 'consciously', phonetic: '/ˈkɑːnʃəsli/', definition: '有意识地；自觉地', example: 'I consciously try to add a short walk to my daily schedule.', emoji: 'https://em-content.zobj.net/source/apple/391/thinking-face_1f914.png' },
    ],
};
