import { SubTopic } from '../data-types';

export const doingWell: SubTopic = {
    id: 'doing-well',
    title: 'Doing something well',
    type: '事件题',
    color: 'blue',
    isNew: true,
    words: [
      { word: 'champion', phonetic: '/ˈtʃæmpiən/', definition: '冠军/拥护者', example: 'He is a true champion of the sport.', emoji: 'https://em-content.zobj.net/source/apple/391/trophy_1f3c6.png' },
      { word: 'praise', phonetic: '/preɪz/', definition: '赞扬', example: 'The critics praised the film for its originality.', emoji: 'https://em-content.zobj.net/source/apple/391/clapping-hands_1f44f.png' },
      { word: 'accomplishment', phonetic: '/əˈkʌmplɪʃmənt/', definition: '成就', example: 'Finishing the marathon was a huge accomplishment for her.', emoji: 'https://em-content.zobj.net/source/apple/391/sports-medal_1f3c5.png' },
      { word: 'excel', phonetic: '/ɪkˈsel/', definition: '擅长/超越', example: 'She has always excelled in science subjects.', emoji: 'https://em-content.zobj.net/source/apple/391/glowing-star_1f31f.png' },
      { word: 'outstanding', phonetic: '/aʊtˈstændɪŋ/', definition: '杰出的', example: 'His performance was outstanding.', emoji: 'https://em-content.zobj.net/source/apple/391/star_2b50.png' },
      { word: 'proficient', phonetic: '/prəˈfɪʃnt/', definition: '精通的', example: 'I am proficient in both spoken and written English.', emoji: 'https://em-content.zobj.net/source/apple/391/woman-technologist_1f469-200d-1f4bb.png' },
      { word: 'skillful', phonetic: '/ˈskɪlfəl/', definition: '熟练的', example: 'He is a skillful negotiator.', emoji: 'https://em-content.zobj.net/source/apple/391/artist-palette_1f3a8.png' },
      { word: 'expert', phonetic: '/ˈekspɜːrt/', definition: '专家', example: 'She is an expert in the field of genetics.', emoji: 'https://em-content.zobj.net/source/apple/391/woman-scientist_1f469-200d-1f52c.png' },
      { word: 'achieve', phonetic: '/əˈtʃiːv/', definition: '实现；达到', example: 'With hard work, you can achieve your goals.', emoji: 'https://em-content.zobj.net/source/apple/391/direct-hit_1f3af.png' },
      { word: 'succeed', phonetic: '/səkˈsiːd/', definition: '成功', example: 'She worked hard and finally succeeded in her business.', emoji: 'https://em-content.zobj.net/source/apple/391/party-popper_1f389.png' },
      { word: 'practice', phonetic: '/ˈpræktɪs/', definition: '练习', example: 'To become good at anything, you need to practice regularly.', emoji: 'https://em-content.zobj.net/source/apple/391/repeat-button_1f501.png' },
      { word: 'proud', phonetic: '/praʊd/', definition: '自豪的', example: 'Her parents were very proud of her graduation.', emoji: 'https://em-content.zobj.net/source/apple/391/smiling-face-with-smiling-eyes_1f60a.png' },
      { word: 'improve', phonetic: '/ɪmˈpruːv/', definition: '提高；改善', example: 'I want to improve my public speaking skills.', emoji: 'https://em-content.zobj.net/source/apple/391/chart-increasing_1f4c8.png' },
      { word: 'good at', phonetic: '/ɡʊd æt/', definition: '擅长于', example: 'She is very good at playing the piano.', emoji: 'https://em-content.zobj.net/source/apple/391/thumbs-up_1f44d.png' },
      { word: 'win', phonetic: '/wɪn/', definition: '赢', example: 'Our team worked hard and managed to win the game.', emoji: 'https://em-content.zobj.net/source/apple/391/trophy_1f3c6.png' },
      { word: 'successful', phonetic: '/səkˈsesfəl/', definition: '成功的', example: 'He is a successful businessman.', emoji: 'https://em-content.zobj.net/source/apple/391/briefcase_1f4bc.png' },
      { word: 'talented', phonetic: '/ˈtæləntɪd/', definition: '有天赋的', example: 'He is a talented musician.', emoji: 'https://em-content.zobj.net/source/apple/391/sparkles_2728.png' },
      { word: 'hard-working', phonetic: '/ˌhɑːrdˈwɜːrkɪŋ/', definition: '勤奋的', example: 'A successful student needs to be hard-working.', emoji: 'https://em-content.zobj.net/source/apple/391/flexed-biceps_1f4aa.png' },
      { word: 'smart', phonetic: '/smɑːrt/', definition: '聪明的', example: 'She is a smart student who always gets good grades.', emoji: 'https://em-content.zobj.net/source/apple/391/light-bulb_1f4a1.png' },
      { word: 'clever', phonetic: '/ˈklevər/', definition: '聪明的', example: 'That was a clever solution to a difficult problem.', emoji: 'https://em-content.zobj.net/source/apple/391/brain_1f9e0.png' },
      { word: 'experience', phonetic: '/ɪkˈspɪəriəns/', definition: '经验', example: 'Practice is the best way to gain experience.', emoji: 'https://em-content.zobj.net/source/apple/391/graduation-cap_1f393.png' },
      { word: 'learn', phonetic: '/lɜːrn/', definition: '学习', example: 'You are never too old to learn.', emoji: 'https://em-content.zobj.net/source/apple/391/books_1f4da.png' },
    ],
};
