import { SubTopic } from '../data-types';

export const excitingActivity: SubTopic = {
    id: 'exciting-activity',
    title: 'Sports, Exciting Activities & Athletes',
    type: '事件题',
    color: 'blue',
    isNew: true,
    words: [
      { word: 'roller coaster', phonetic: '/ˈroʊlər ˌkoʊstər/', definition: '过山车', example: 'Riding a roller coaster is a thrilling experience.', emoji: 'https://em-content.zobj.net/source/apple/391/roller-coaster_1f3a2.png' },
      { word: 'thrilling', phonetic: '/ˈθrɪlɪŋ/', definition: '惊险的；刺激的', example: 'The movie had a thrilling chase scene.', emoji: 'https://em-content.zobj.net/source/apple/391/face-screaming-in-fear_1f631.png' },
      { word: 'exhilarating', phonetic: '/ɪɡˈzɪləreɪtɪŋ/', definition: '令人振奋的', example: 'The exhilarating feeling of skiing down the mountain is unforgettable.', emoji: 'https://em-content.zobj.net/source/apple/391/party-popper_1f389.png' },
      { word: 'unforgettable', phonetic: '/ˌʌnfərˈɡetəbl/', definition: '难忘的', example: 'Visiting the Grand Canyon was an unforgettable experience.', emoji: 'https://em-content.zobj.net/source/apple/391/sparkling-heart_1f496.png' },
      { word: 'adventurous', phonetic: '/ədˈventʃərəs/', definition: '富有冒险精神的', example: 'He is an adventurous traveler who loves exploring new places.', emoji: 'https://em-content.zobj.net/source/apple/391/woman-climbing_1f9d7-200d-2640-fe0f.png' },
      { word: 'breathtaking', phonetic: '/ˈbreθteɪkɪŋ/', definition: '惊人的；惊险的', example: 'The view from the top of the mountain was breathtaking.', emoji: 'https://em-content.zobj.net/source/apple/391/face-with-open-mouth_1f62e.png' },
      { word: 'athlete', phonetic: '/ˈæθliːt/', definition: '运动员', example: 'He is a professional athlete who competes in marathons.', emoji: 'https://em-content.zobj.net/source/apple/391/person-running_1f3c3.png' },
      { word: 'compete', phonetic: '/kəmˈpiːt/', definition: '竞争；比赛', example: 'Many teams compete for the championship.', emoji: 'https://em-content.zobj.net/source/apple/391/sports-medal_1f3c5.png' },
      { word: 'stadium', phonetic: '/ˈsteɪdiəm/', definition: '体育场', example: 'The stadium was packed with excited fans.', emoji: 'https://em-content.zobj.net/source/apple/391/stadium_1f3df-fe0f.png' },
      { word: 'teamwork', phonetic: '/ˈtiːmwɜːrk/', definition: '团队合作', example: 'Teamwork is essential for success in basketball.', emoji: 'https://em-content.zobj.net/source/apple/391/handshake_1f91d.png' },
      { word: 'exercise', phonetic: '/ˈeksərsaɪz/', definition: '锻炼', example: 'Regular exercise is important for staying healthy.', emoji: 'https://em-content.zobj.net/source/apple/391/person-lifting-weights_1f3cb-fe0f.png' },
      { word: 'energetic', phonetic: '/ˌenərˈdʒetɪk/', definition: '精力充沛的', example: 'The children were very energetic after the party.', emoji: 'https://em-content.zobj.net/source/apple/391/battery_1f50b.png' },
      { word: 'sportsperson', phonetic: '/ˈspɔːrtsˌpɜːrsn/', definition: '体育运动人物', example: 'She is a respected sportsperson known for her fair play.', emoji: '🏃‍♀️' },
      { word: 'professional player', phonetic: '/prəˈfeʃənl ˈpleɪər/', definition: '职业选手', example: 'Becoming a professional player requires years of dedication.', emoji: '🏆' },
      { word: 'champion', phonetic: '/ˈtʃæmpiən/', definition: '冠军', example: 'He is a true champion of the sport.', emoji: 'https://em-content.zobj.net/source/apple/391/trophy_1f3c6.png' },
      { word: 'world-class', phonetic: '/ˌwɜːrldˈklæs/', definition: '世界级', example: 'He is a world-class athlete with several records.', emoji: '🌎' },
      { word: 'well-known', phonetic: '/ˌwelˈnoʊn/', definition: '著名的', example: 'The team has a well-known coach.', emoji: '🌟' },
      { word: 'talented', phonetic: '/ˈtæləntɪd/', definition: '有天赋的', example: 'She is a talented swimmer with a bright future.', emoji: '✨' },
      { word: 'swimmer', phonetic: '/ˈswɪmər/', definition: '游泳运动员', example: 'The swimmer trained hard for the Olympics.', emoji: '🏊' },
      { word: 'runner', phonetic: '/ˈrʌnər/', definition: '跑步运动员', example: 'The runner crossed the finish line in first place.', emoji: '🏃' },
      { word: 'coach', phonetic: '/koʊtʃ/', definition: '教练', example: 'The coach provided guidance and support to the team.', emoji: '👨‍🏫' },
      { word: 'disciplined', phonetic: '/ˈdɪsəplɪnd/', definition: '自律的', example: 'A successful athlete must be highly disciplined.', emoji: '🧘' },
      { word: 'determined', phonetic: '/dɪˈtɜːrmɪnd/', definition: '有决心的', example: 'She was determined to win the race.', emoji: '💪' },
      { word: 'confident', phonetic: '/ˈkɑːnfɪdənt/', definition: '自信的', example: 'The player was confident in his ability to score.', emoji: '😎' },
      { word: 'humble', phonetic: '/ˈhʌmbl/', definition: '谦虚的', example: 'Despite his success, the champion remained humble.', emoji: '🙏' },
      { word: 'strong-minded', phonetic: '/ˌstrɔːŋˈmaɪndɪd/', definition: '意志坚强的', example: 'You need to be strong-minded to handle the pressure of competition.', emoji: '🧠' },
      { word: 'never give up', phonetic: '/ˈnevər ɡɪv ʌp/', definition: '永不放弃', example: 'His motto is to never give up, no matter the challenge.', emoji: '✊' },
      { word: 'train hard', phonetic: '/treɪn hɑːrd/', definition: '努力训练', example: 'Athletes train hard every day to stay in top condition.', emoji: '🏋️' },
      { word: 'overcome difficulties', phonetic: '/ˌoʊvərˈkʌm ˈdɪfɪkəltiz/', definition: '克服困难', example: 'She had to overcome many difficulties to achieve her goals.', emoji: '🧗‍♀️' },
      { word: 'deal with pressure', phonetic: '/diːl wɪθ ˈpreʃər/', definition: '承受压力', example: 'Professional players must learn how to deal with pressure.', emoji: '😌' },
      { word: 'stay focused', phonetic: '/steɪ ˈfoʊkəst/', definition: '保持专注', example: 'It is important to stay focused during a match.', emoji: '🎯' },
      { word: 'push oneself', phonetic: '/pʊʃ wʌnˈself/', definition: '激励自己', example: 'To improve, you have to constantly push oneself.', emoji: '🚀' },
      { word: 'win medals', phonetic: '/wɪn ˈmedlz/', definition: '获得奖牌', example: 'Her dream is to win medals at the Olympics.', emoji: '🥇' },
      { word: 'break records', phonetic: '/breɪk ˈrekərdz/', definition: '打破纪录', example: 'The runner is trying to break the world record.', emoji: '📈' },
      { word: 'represent the country', phonetic: '/ˌreprɪˈzent ðə ˈkʌntri/', definition: '为国家出赛', example: 'It is an honor to represent the country in a competition.', emoji: '🏁' },
      { word: 'achieve great success', phonetic: '/əˈtʃiːv ɡreɪt səkˈses/', definition: '取得巨大成功', example: 'He hopes to achieve great success in his career.', emoji: '🤩' },
      { word: 'inspire millions of people', phonetic: '/ɪnˈspaɪər ˈmɪljənz əv ˈpiːpl/', definition: '激励了很多人', example: 'Her story will inspire millions of people around the world.', emoji: '💖' },
      { word: 'admire', phonetic: '/ədˈmaɪər/', definition: '钦佩', example: 'I admire her dedication and hard work.', emoji: '😍' },
      { word: 'strong willpower', phonetic: '/strɔːŋ ˈwɪlˌpaʊər/', definition: '坚强的意志力', example: 'It takes strong willpower to train for a marathon.', emoji: '🔥' },
      { word: 'role model', phonetic: '/ˈroʊl ˌmɑːdl/', definition: '榜样', example: 'Many young athletes look up to him as a role model.', emoji: '👨‍👧‍👦' },
    ],
};
