import { SubTopic } from '../data-types';

export const gardening: SubTopic = {
    id: 'gardening',
    title: 'Growing vegetables/fruits',
    type: '事件题',
    color: 'blue',
    words: [
      { word: 'cultivate', phonetic: '/ˈkʌltɪveɪt/', definition: '栽培', example: 'We cultivate a variety of vegetables in our garden.', emoji: 'https://em-content.zobj.net/source/apple/391/seedling_1f331.png' },
      { word: 'harvest', phonetic: '/ˈhɑːrvɪst/', definition: '收获', example: 'It\'s time to harvest the ripe tomatoes.', emoji: 'https://em-content.zobj.net/source/apple/391/basket_1f9fa.png' },
      { word: 'organic', phonetic: '/ɔːrˈɡænɪk/', definition: '有机的', example: 'We prefer to grow organic vegetables without pesticides.', emoji: 'https://em-content.zobj.net/source/apple/391/herb_1f33f.png' },
      { word: 'horticulture', phonetic: '/ˈhɔːrtɪkʌltʃər/', definition: '园艺', example: 'Horticulture is a relaxing and rewarding hobby.', emoji: 'https://em-content.zobj.net/source/apple/391/potted-plant_1fab4.png' },
      { word: 'farm', phonetic: '/fɑːrm/', definition: '农场', example: 'My grandparents live on a farm and grow their own vegetables.', emoji: 'https://em-content.zobj.net/source/apple/391/tractor_1f69c.png' },
      { word: 'backyard', phonetic: '/ˈbækjɑːrd/', definition: '后院', example: 'We have a small vegetable garden in our backyard.', emoji: 'https://em-content.zobj.net/source/apple/391/house-with-garden_1f3e1.png' },
      { word: 'soil', phonetic: '/sɔɪl/', definition: '土壤', example: 'Good soil is essential for growing healthy plants.', emoji: 'https://em-content.zobj.net/source/apple/391/potted-plant_1fab4.png' },
      { word: 'seeds', phonetic: '/siːdz/', definition: '种子', example: 'We bought some tomato seeds to plant in our garden.', emoji: 'https://em-content.zobj.net/source/apple/391/seedling_1f331.png' },
      { word: 'water', phonetic: '/ˈwɔːtər/', definition: '水；浇水', example: 'Plants need plenty of water and sunlight to grow.', emoji: 'https://em-content.zobj.net/source/apple/391/droplet_1f4a7.png' },
      { word: 'sunlight', phonetic: '/ˈsʌnlaɪt/', definition: '阳光', example: 'These plants need at least six hours of direct sunlight each day.', emoji: 'https://em-content.zobj.net/source/apple/391/sun_2600-fe0f.png' },
      { word: 'plant seeds', phonetic: '/plænt siːdz/', definition: '播种', example: 'Spring is the best time to plant seeds for summer vegetables.', emoji: 'https://em-content.zobj.net/source/apple/391/palms-up-together_1f932.png' },
      { word: 'water the plants', phonetic: '/ˈwɔːtər ðə plænts/', definition: '给植物浇水', example: 'Remember to water the plants every morning.', emoji: 'https://em-content.zobj.net/source/apple/391/sweat-droplets_1f4a6.png' },
      { word: 'take care of', phonetic: '/teɪk ker əv/', definition: '照顾', example: 'It is important to take care of the plants properly.', emoji: 'https://em-content.zobj.net/source/apple/391/man-farmer_1f468-200d-1f33e.png' },
      { word: 'home-grown', phonetic: '/ˈhoʊmˈɡroʊn/', definition: '自家种植的', example: 'I love the taste of home-grown tomatoes.', emoji: 'https://em-content.zobj.net/source/apple/391/tomato_1f345.png' },
      { word: 'relaxing', phonetic: '/rɪˈlæksɪŋ/', definition: '放松的', example: 'Gardening can be a very relaxing hobby.', emoji: 'https://em-content.zobj.net/source/apple/391/relieved-face_1f60c.png' },
      { word: 'enjoyable', phonetic: '/ɪnˈdʒɔɪəbl/', definition: '愉快的', example: 'Watching the plants grow from seeds is an enjoyable experience.', emoji: 'https://em-content.zobj.net/source/apple/391/smiling-face-with-smiling-eyes_1f60a.png' },
      { word: 'interesting', phonetic: '/ˈɪntrəstɪŋ/', definition: '有趣的', example: 'It is interesting to see how different plants grow.', emoji: 'https://em-content.zobj.net/source/apple/391/thinking-face_1f914.png' },
      { word: 'rewarding', phonetic: '/rɪˈwɔːrdɪŋ/', definition: '有成就感的', example: 'Harvesting your own vegetables is a very rewarding feeling.', emoji: 'https://em-content.zobj.net/source/apple/391/trophy_1f3c6.png' },
      { word: 'meaningful', phonetic: '/ˈmiːnɪŋfl/', definition: '有意义的', example: 'Growing your own food can be a meaningful way to connect with nature.', emoji: 'https://em-content.zobj.net/source/apple/391/sparkling-heart_1f496.png' },
      { word: 'close to nature', phonetic: '/kloʊs tu ˈneɪtʃər/', definition: '接近自然', example: 'Gardening helps me feel close to nature.', emoji: 'https://em-content.zobj.net/source/apple/391/deciduous-tree_1f333.png' },
      { word: 'healthy lifestyle', phonetic: '/ˈhelθi ˈlaɪfstaɪl/', definition: '健康的生活方式', example: 'Eating fresh, home-grown vegetables is part of a healthy lifestyle.', emoji: 'https://em-content.zobj.net/source/apple/391/green-salad_1f957.png' },
      { word: 'take time and effort', phonetic: '/teɪk taɪm ænd ˈefərt/', definition: '花费时间和精力', example: 'Gardening can take time and effort, but it is worth it.', emoji: 'https://em-content.zobj.net/source/apple/391/flexed-biceps_1f4aa.png' },
      { word: 'space', phonetic: '/speɪs/', definition: '空间', example: 'You don\'t need a lot of space to grow some herbs.', emoji: 'https://em-content.zobj.net/source/apple/391/straight-ruler_1f4cf.png' },
      { word: 'easy to grow', phonetic: '/ˈiːzi tu ɡroʊ/', definition: '容易种植', example: 'Herbs like mint and basil are very easy to grow.', emoji: 'https://em-content.zobj.net/source/apple/391/thumbs-up_1f44d.png' },
      { word: 'school garden', phonetic: '/skuːl ˈɡɑːrdn/', definition: '校园菜园', example: 'The students work together to maintain the school garden.', emoji: 'https://em-content.zobj.net/source/apple/391/school_1f3eb.png' },
      { word: 'hands-on experience', phonetic: '/ˌhændzˈɒn ɪkˈspɪəriəns/', definition: '动手实践', example: 'The school garden provides hands-on experience in agriculture.', emoji: 'https://em-content.zobj.net/source/apple/391/open-hands_1f450.png' },
      { word: 'environmental education', phonetic: '/ɪnˌvaɪrənˈmentl ˌedʒuˈkeɪʃn/', definition: '环保教育', example: 'School gardens are a great tool for environmental education.', emoji: 'https://em-content.zobj.net/source/apple/391/globe-showing-europe-africa_1f30d.png' },
      { word: 'learn responsibility', phonetic: '/lɜːrn rɪˌspɒnsəˈbɪləti/', definition: '学会责任感', example: 'Taking care of plants helps children learn responsibility.', emoji: 'https://em-content.zobj.net/source/apple/391/student_1f9d1-200d-1f393.png' },
      { word: 'teamwork', phonetic: '/ˈtiːmwɜːrk/', definition: '团队合作', example: 'Maintaining a school garden requires a lot of teamwork.', emoji: 'https://em-content.zobj.net/source/apple/391/handshake_1f91d.png' },
    ],
};
