import { SubTopic } from '../data-types';

export const gardening: SubTopic = {
    id: 'gardening',
    title: 'Growing Plants & Vegetables',
    type: '事件题',
    color: 'blue',
    isNew: true,
    wordSections: [
        {
            title: '基础词汇',
            words: [
              { word: 'farm', phonetic: '/fɑːrm/', definition: '农场', example: 'My grandparents live on a farm and grow their own vegetables.', emoji: 'https://em-content.zobj.net/source/apple/391/tractor_1f69c.png' },
              { word: 'backyard', phonetic: '/ˈbækjɑːrd/', definition: '后院', example: 'We have a small vegetable garden in our backyard.', emoji: 'https://em-content.zobj.net/source/apple/391/house-with-garden_1f3e1.png' },
              { word: 'soil', phonetic: '/sɔɪl/', definition: '土壤', example: 'Good soil is essential for growing healthy plants.', emoji: 'https://em-content.zobj.net/source/apple/391/potted-plant_1fab4.png' },
              { word: 'seeds', phonetic: '/siːdz/', definition: '种子', example: 'We bought some tomato seeds to plant in our garden.', emoji: 'https://em-content.zobj.net/source/apple/391/seedling_1f331.png' },
              { word: 'water', phonetic: '/ˈwɔːtər/', definition: '水；浇水', example: 'Plants need plenty of water and sunlight to grow.', emoji: 'https://em-content.zobj.net/source/apple/391/droplet_1f4a7.png' },
              { word: 'sunlight', phonetic: '/ˈsʌnlaɪt/', definition: '阳光', example: 'These plants need at least six hours of direct sunlight each day.', emoji: 'https://em-content.zobj.net/source/apple/391/sun_2600-fe0f.png' },
              { word: 'fresh air', phonetic: '/freʃ er/', definition: '新鲜空气', example: 'Plants help to provide fresh air by producing oxygen.', emoji: 'https://em-content.zobj.net/source/apple/391/leaf-fluttering-in-wind_1f343.png' },
              { word: 'plant seeds', phonetic: '/plænt siːdz/', definition: '播种', example: 'Spring is the best time to plant seeds for summer vegetables.', emoji: 'https://em-content.zobj.net/source/apple/391/palms-up-together_1f932.png' },
              { word: 'water the plants', phonetic: '/ˈwɔːtər ðə plænts/', definition: '给植物浇水', example: 'Remember to water the plants every morning.', emoji: 'https://em-content.zobj.net/source/apple/391/sweat-droplets_1f4a6.png' },
              { word: 'root', phonetic: '/ruːt/', definition: '根', example: 'The roots of the tree go deep into the ground.', emoji: 'https://em-content.zobj.net/source/apple/391/potted-plant_1fab4.png' },
              { word: 'stem', phonetic: '/stem/', definition: '茎', example: 'The stem supports the leaves and flowers.', emoji: 'https://em-content.zobj.net/source/apple/391/herb_1f33f.png' },
              { word: 'petal', phonetic: '/ˈpetl/', definition: '花瓣', example: 'The rose has beautiful red petals.', emoji: 'https://em-content.zobj.net/source/apple/391/rose_1f940.png' },
              { word: 'blossom', phonetic: '/ˈblɑːsəm/', definition: '花', example: 'The cherry trees are in full blossom.', emoji: 'https://em-content.zobj.net/source/apple/391/cherry-blossom_1f338.png' },
              { word: 'bloom', phonetic: '/bluːm/', definition: '开花', example: 'The flowers will bloom in the spring.', emoji: 'https://em-content.zobj.net/source/apple/391/blossom_1f33c.png' },
              { word: 'potted plant', phonetic: '/ˈpɒtɪd plænt/', definition: '盆栽', example: 'A potted plant is a great way to bring some nature indoors.', emoji: 'https://em-content.zobj.net/source/apple/391/potted-plant_1fab4.png' },
              { word: 'houseplants', phonetic: '/ˈhaʊsplænts/', definition: '室内植物', example: 'I have several houseplants to decorate my living room.', emoji: 'https://em-content.zobj.net/source/apple/391/potted-plant_1fab4.png' },
              { word: 'indoor plants', phonetic: '/ˈɪndɔːr plænts/', definition: '室内植物', example: 'Indoor plants can make a room feel more alive and welcoming.', emoji: 'https://em-content.zobj.net/source/apple/391/herb_1f33f.png' },
              { word: 'green plants', phonetic: '/ɡriːn plænts/', definition: '绿色植物', example: 'Having green plants in the office can improve productivity.', emoji: 'https://em-content.zobj.net/source/apple/391/herb_1f33f.png' },
              { word: 'flower shop', phonetic: '/ˈflaʊər ʃɒp/', definition: '花店', example: 'I bought a beautiful bouquet from the local flower shop.', emoji: 'https://em-content.zobj.net/source/apple/391/bouquet_1f490.png' },
              { word: 'school garden', phonetic: '/skuːl ˈɡɑːrdn/', definition: '校园菜园', example: 'The students work together to maintain the school garden.', emoji: 'https://em-content.zobj.net/source/apple/391/school_1f3eb.png' },
              { word: 'grow beans', phonetic: '/ɡroʊ biːnz/', definition: '种豆子', example: 'In our science class, we learned how to grow beans in a cup.', emoji: 'https://em-content.zobj.net/source/apple/391/seedling_1f331.png' },
              { word: 'grow flowers', phonetic: '/ɡroʊ ˈflaʊərz/', definition: '种花', example: 'My mother loves to grow flowers in her garden.', emoji: 'https://em-content.zobj.net/source/apple/391/cherry-blossom_1f338.png' },
              { word: 'observe the growth', phonetic: '/əbˈzɜːrv ðə ɡroʊθ/', definition: '观察生长', example: 'It\'s fascinating to observe the growth of a plant from a tiny seed.', emoji: 'https://em-content.zobj.net/source/apple/391/microscope_1f52c.png' },
              { word: 'wait for it to sprout', phonetic: '/weɪt fɔːr ɪt tuː spraʊt/', definition: '等它发芽', example: 'After planting the seed, you have to wait for it to sprout.', emoji: 'https://em-content.zobj.net/source/apple/391/seedling_1f331.png' },
            ]
        },
        {
            title: '进阶词汇',
            words: [
              { word: 'cultivate', phonetic: '/ˈkʌltɪveɪt/', definition: '栽培', example: 'We cultivate a variety of vegetables in our garden.', emoji: 'https://em-content.zobj.net/source/apple/391/seedling_1f331.png' },
              { word: 'harvest', phonetic: '/ˈhɑːrvɪst/', definition: '收获', example: 'It\'s time to harvest the ripe tomatoes.', emoji: 'https://em-content.zobj.net/source/apple/391/basket_1f9fa.png' },
              { word: 'organic', phonetic: '/ɔːrˈɡænɪk/', definition: '有机的', example: 'We prefer to grow organic vegetables without pesticides.', emoji: 'https://em-content.zobj.net/source/apple/391/herb_1f33f.png' },
              { word: 'horticulture', phonetic: '/ˈhɔːrtɪkʌltʃər/', definition: '园艺', example: 'Horticulture is a relaxing and rewarding hobby.', emoji: 'https://em-content.zobj.net/source/apple/391/potted-plant_1fab4.png' },
              { word: 'botany', phonetic: '/ˈbɑːtəni/', definition: '植物学', example: 'Botany is the scientific study of plants.', emoji: 'https://em-content.zobj.net/source/apple/391/microscope_1f52c.png' },
              { word: 'fragrance', phonetic: '/ˈfreɪɡrəns/', definition: '香味', example: 'I love the fragrance of fresh flowers.', emoji: 'https://em-content.zobj.net/source/apple/391/nose_1f443.png' },
              { word: 'popular', phonetic: '/ˈpɒpjələr/', definition: '受欢迎的', example: 'Gardening has become a very popular hobby.', emoji: 'https://em-content.zobj.net/source/apple/391/smiling-face-with-hearts_1f970.png' },
              { word: 'take care of', phonetic: '/teɪk ker əv/', definition: '照顾', example: 'It is important to take care of the plants properly.', emoji: 'https://em-content.zobj.net/source/apple/391/man-farmer_1f468-200d-1f33e.png' },
              { word: 'home-grown', phonetic: '/ˈhoʊmˈɡroʊn/', definition: '自家种植的', example: 'I love the taste of home-grown tomatoes.', emoji: 'https://em-content.zobj.net/source/apple/391/tomato_1f345.png' },
              { word: 'relaxing', phonetic: '/rɪˈlæksɪŋ/', definition: '放松的', example: 'Gardening can be a very relaxing hobby.', emoji: 'https://em-content.zobj.net/source/apple/391/relieved-face_1f60c.png' },
              { word: 'enjoyable', phonetic: '/ɪnˈdʒɔɪəbl/', definition: '愉快的', example: 'Watching the plants grow from seeds is an enjoyable experience.', emoji: 'https://em-content.zobj.net/source/apple/391/smiling-face-with-smiling-eyes_1f60a.png' },
              { word: 'interesting', phonetic: '/ˈɪntrəstɪŋ/', definition: '有趣的', example: 'It is interesting to see how different plants grow.', emoji: 'https://em-content.zobj.net/source/apple/391/thinking-face_1f914.png' },
              { word: 'rewarding', phonetic: '/rɪˈwɔːrdɪŋ/', definition: '有成就感的', example: 'Harvesting your own vegetables is a very rewarding feeling.', emoji: 'https://em-content.zobj.net/source/apple/391/trophy_1f3c6.png' },
              { word: 'meaningful', phonetic: '/ˈmiːnɪŋfl/', definition: '有意义的', example: 'Growing your own food can be a meaningful way to connect with nature.', emoji: 'https://em-content.zobj.net/source/apple/391/sparkling-heart_1f496.png' },
              { word: 'close to nature', phonetic: '/kloʊs tu ˈneɪtʃər/', definition: '接近自然', example: 'Gardening helps me feel close to nature.', emoji: 'https://em-content.zobj.net/source/apple/391/deciduous-tree_1f333.png' },
              { word: 'healthy lifestyle', phonetic: '/ˈhelθi ˈlaɪfstaɪl/', definition: '健康的生活方式', example: 'Eating fresh, home-grown vegetables is part of a healthy lifestyle.', emoji: 'https://em-content.zobj.net/source/apple/391/green-salad_1f957.png' },
              { word: 'take time and effort', phonetic: '/teɪk taɪm ænd ˈefərt/', definition: '花费时间和精力', example: 'Gardening can take time and effort, but it is worth it.', emoji: 'https://em-content.zobj.net/source/apple/391/flexed-biceps_1f4aa.png' },
              { word: 'space', phonetic: '/speɪs/', definition: '空间', example: 'You don\'t need a lot of space to grow some herbs.', emoji: 'https://em-content.zobj.net/source/apple/391/straight-ruler_1f4cf.png' },
              { word: 'easy to grow', phonetic: '/ˈiːzi tu ɡroʊ/', definition: '容易种植', example: 'Herbs like mint and basil are very easy to grow.', emoji: 'https://em-content.zobj.net/source/apple/391/thumbs-up_1f44d.png' },
              { word: 'hands-on experience', phonetic: '/ˌhændzˈɒn ɪkˈspɪəriəns/', definition: '动手实践', example: 'The school garden provides hands-on experience in agriculture.', emoji: 'https://em-content.zobj.net/source/apple/391/open-hands_1f450.png' },
              { word: 'environmental education', phonetic: '/ɪnˌvaɪrənˈmentl ˌedʒuˈkeɪʃn/', definition: '环保教育', example: 'School gardens are a great tool for environmental education.', emoji: 'https://em-content.zobj.net/source/apple/391/globe-showing-europe-africa_1f30d.png' },
              { word: 'learn responsibility', phonetic: '/lɜːrn rɪˌspɒnsəˈbɪləti/', definition: '学会责任感', example: 'Taking care of plants helps children learn responsibility.', emoji: 'https://em-content.zobj.net/source/apple/391/student_1f9d1-200d-1f393.png' },
              { word: 'teamwork', phonetic: '/ˈtiːmwɜːrk/', definition: '团队合作', example: 'Maintaining a school garden requires a lot of teamwork.', emoji: 'https://em-content.zobj.net/source/apple/391/handshake_1f91d.png' },
              { word: 'keep plants at home', phonetic: '/kiːp plænts ət hoʊm/', definition: '在家养植物', example: 'Many people keep plants at home to purify the air.', emoji: 'https://em-content.zobj.net/source/apple/391/house-with-garden_1f3e1.png' },
              { word: 'decorate the room', phonetic: '/ˈdekəreɪt ðə ruːm/', definition: '装饰房间', example: 'I use green plants to decorate the room.', emoji: 'https://em-content.zobj.net/source/apple/391/framed-picture_1f5bc-fe0f.png' },
              { word: 'make the room feel alive', phonetic: '/meɪk ðə ruːm fiːl əˈlaɪv/', definition: '让房间更有生气', example: 'Adding some plants can make the room feel alive.', emoji: 'https://em-content.zobj.net/source/apple/391/sparkles_2728.png' },
              { word: 'give enough sunlight', phonetic: '/ɡɪv ɪˈnʌf ˈsʌnlaɪt/', definition: '给足阳光', example: 'You need to give these plants enough sunlight for them to grow well.', emoji: 'https://em-content.zobj.net/source/apple/391/sun_2600-fe0f.png' },
              { word: 'school gardening class', phonetic: '/skuːl ˈɡɑːrdnɪŋ klæs/', definition: '学校的种植课', example: 'I learned about different plants in my school gardening class.', emoji: 'https://em-content.zobj.net/source/apple/391/man-teacher_1f468-200d-1f3eb.png' },
              { word: 'take time to grow', phonetic: '/teɪk taɪm tuː ɡroʊ/', definition: '生长需要时间', example: 'You must be patient; plants take time to grow.', emoji: 'https://em-content.zobj.net/source/apple/391/hourglass-not-done_23f3.png' },
              { word: 'symbol of good luck', phonetic: '/ˈsɪmbəl əv ɡʊd lʌk/', definition: '象征好运', example: 'The money tree is often considered a symbol of good luck.', emoji: 'https://em-content.zobj.net/source/apple/391/four-leaf-clover_1f340.png' },
              { word: 'special occasions', phonetic: '/ˈspeʃl əˈkeɪʒənz/', definition: '特别场合', example: 'Flowers are a popular gift for special occasions like birthdays and anniversaries.', emoji: 'https://em-content.zobj.net/source/apple/391/party-popper_1f389.png' },
              { word: 'housewarming gift', phonetic: '/ˈhaʊswɔːrmɪŋ ɡɪft/', definition: '乔迁礼物', example: 'A potted plant makes a lovely housewarming gift.', emoji: 'https://em-content.zobj.net/source/apple/391/wrapped-gift_1f381.png' },
              { word: 'meaningful gift', phonetic: '/ˈmiːnɪŋfəl ɡɪft/', definition: '有意义的礼物', example: 'A plant you\'ve grown yourself can be a very meaningful gift.', emoji: 'https://em-content.zobj.net/source/apple/391/heart-with-ribbon_1f49d.png' },
              { word: 'peaceful', phonetic: '/ˈpiːsfl/', definition: '宁静的', example: 'Tending to my garden is a peaceful activity.', emoji: 'https://em-content.zobj.net/source/apple/391/person-in-lotus-position_1f9d8.png' },
              { word: 'refreshing', phonetic: '/rɪˈfreʃɪŋ/', definition: '令人清新的', example: 'The smell of mint leaves is very refreshing.', emoji: 'https://em-content.zobj.net/source/apple/391/leaf-fluttering-in-wind_1f343.png' },
              { word: 'pleasant', phonetic: '/ˈpleznt/', definition: '愉快的', example: 'It was a pleasant afternoon spent in the garden.', emoji: 'https://em-content.zobj.net/source/apple/391/smiling-face-with-smiling-eyes_1f60a.png' },
            ]
        }
    ],
};
