import { SubTopic } from '../data-types';

export const goodService: SubTopic = {
    id: 'good-service',
    title: 'Good Service',
    type: '事件题',
    color: 'blue',
    badge: 'Part 2',
    words: [
      { word: 'shop assistant', phonetic: '/ʃɒp əˈsɪstənt/', definition: '售货员', example: 'The shop assistant was very helpful when I was looking for a new pair of jeans.', emoji: 'https://em-content.zobj.net/source/apple/391/woman-tipping-hand_1f481-200d-2640-fe0f.png' },
      { word: 'cashier', phonetic: '/kæˈʃɪər/', definition: '收银员', example: 'I paid the cashier for my groceries and she gave me the receipt.', emoji: 'https://em-content.zobj.net/source/apple/391/money-bag_1f4b0.png' },
      { word: 'counter', phonetic: '/ˈkaʊntər/', definition: '柜台', example: 'I placed my items on the counter to be scanned by the cashier.', emoji: 'https://em-content.zobj.net/source/apple/391/desktop-computer_1f5a5-fe0f.png' },
      { word: 'fitting room', phonetic: '/ˈfɪtɪŋ ruːm/', definition: '试衣间', example: 'I need to use the fitting room to try on this dress.', emoji: 'https://em-content.zobj.net/source/apple/391/dress_1f457.png' },
      { word: 'discount', phonetic: '/ˈdɪskaʊnt/', definition: '折扣', example: 'I got a 20% discount on these shoes because they were on sale.', emoji: 'https://em-content.zobj.net/source/apple/391/label_1f3f7-fe0f.png' },
      { word: 'helpful', phonetic: '/ˈhelpfəl/', definition: '有帮助的', example: 'The staff at the hotel were extremely helpful and friendly.', emoji: 'https://em-content.zobj.net/source/apple/391/thumbs-up_1f44d.png' },
      { word: 'attentive', phonetic: '/əˈtentɪv/', definition: '殷勤的；体贴的', example: 'The waiter was very attentive, refilling our water glasses without us asking.', emoji: 'https://em-content.zobj.net/source/apple/391/person-bowing_1f647.png' },
      { word: 'recommend products', phonetic: '/ˌrekəˈmend ˈprɒdʌkts/', definition: '推荐产品', example: 'The shop assistant was good at recommending products that suited my needs.', emoji: 'https://em-content.zobj.net/source/apple/391/light-bulb_1f4a1.png' },
      { word: 'didn’t push me to buy', phonetic: '/dɪdnt pʊʃ miː tuː baɪ/', definition: '没有强迫我购买', example: 'She showed me some options but didn’t push me to buy anything, which I appreciated.', emoji: 'https://em-content.zobj.net/source/apple/391/hand-with-fingers-splayed_1f590-fe0f.png' },
      { word: 'help me choose', phonetic: '/help miː tʃuːz/', definition: '帮我选择', example: 'She was patient and helped me choose the right color.', emoji: 'https://em-content.zobj.net/source/apple/391/artist-palette_1f3a8.png' },
      { word: 'reasonable price', phonetic: '/ˈriːznəbl praɪs/', definition: '合理的价格', example: 'The meal was delicious and sold at a reasonable price.', emoji: 'https://em-content.zobj.net/source/apple/391/money-with-wings_1f4b8.png' },
      { word: 'good quality', phonetic: '/ɡʊd ˈkwɒləti/', definition: '质量好', example: 'The jacket is of good quality and should last for years.', emoji: 'https://em-content.zobj.net/source/apple/391/gem-stone_1f48e.png' },
      { word: 'worth the money', phonetic: '/wɜːrθ ðə ˈmʌni/', definition: '物有所值', example: 'It was expensive, but the service was so good it was worth the money.', emoji: 'https://em-content.zobj.net/source/apple/391/chart-increasing_1f4c8.png' },
      { word: 'menu', phonetic: '/ˈmenjuː/', definition: '菜单', example: 'The waiter brought us the menu as soon as we sat down.', emoji: 'https://em-content.zobj.net/source/apple/391/scroll_1f4dc.png' },
      { word: 'reservation', phonetic: '/ˌrezərˈveɪʃn/', definition: '预定', example: 'We made a reservation for a table for two at 7 PM.', emoji: 'https://em-content.zobj.net/source/apple/391/spiral-calendar_1f5d3-fe0f.png' },
      { word: 'thoughtful', phonetic: '/ˈθɔːtfl/', definition: '体贴的', example: 'It was very thoughtful of the staff to offer us a blanket on the chilly evening.', emoji: 'https://em-content.zobj.net/source/apple/391/sparkling-heart_1f496.png' },
      { word: 'greet us warmly', phonetic: '/ɡriːt əs ˈwɔːrmli/', definition: '热情地迎接我们', example: 'The host greeted us warmly at the door and made us feel welcome.', emoji: '🤗' },
      { word: 'show us to the table', phonetic: '/ʃoʊ əs tuː ðə ˈteɪbl/', definition: '带我们到座位', example: 'The waiter showed us to our table by the window.', emoji: 'https://em-content.zobj.net/source/apple/391/chair_1fa91.png' },
      { word: 'recommend dishes', phonetic: '/ˌrekəˈmend ˈdɪʃɪz/', definition: '推荐菜肴', example: 'The chef came out to recommend some of the daily specials.', emoji: 'https://em-content.zobj.net/source/apple/391/man-cook_1f468-200d-1f373.png' },
      { word: 'refill the water', phonetic: '/ˌriːˈfɪl ðə ˈwɔːtər/', definition: '续水', example: 'The server was quick to refill our water glasses throughout the meal.', emoji: 'https://em-content.zobj.net/source/apple/391/droplet_1f4a7.png' },
      { word: 'check on us regularly', phonetic: '/tʃek ɒn əs ˈreɡjələrli/', definition: '定期过来看看我们', example: 'Our waiter would check on us regularly to see if we needed anything.', emoji: 'https://em-content.zobj.net/source/apple/391/eyes_1f440.png' },
      { word: 'respond quickly', phonetic: '/rɪˈspɒnd ˈkwɪkli/', definition: '反应迅速', example: 'When we had a question, the staff responded quickly and efficiently.', emoji: 'https://em-content.zobj.net/source/apple/391/high-voltage_26a1.png' },
      { word: 'handled everything smoothly', phonetic: '/ˈhændld ˈevriθɪŋ ˈsmuːðli/', definition: '把一切都处理得很顺利', example: 'Even though the restaurant was busy, our server handled everything smoothly.', emoji: 'https://em-content.zobj.net/source/apple/391/ok-hand_1f44c.png' },
      { word: 'fresh', phonetic: '/freʃ/', definition: '新鲜的', example: 'The restaurant is known for using fresh, locally sourced ingredients.', emoji: 'https://em-content.zobj.net/source/apple/391/green-salad_1f957.png' },
      { word: 'well-seasoned', phonetic: '/ˌwel ˈsiːzənd/', definition: '调味恰到好处', example: 'The steak was perfectly cooked and well-seasoned.', emoji: 'https://em-content.zobj.net/source/apple/391/salt_1f9c2.png' },
      { word: 'worth the price', phonetic: '/wɜːrθ ðə praɪs/', definition: '物有所值', example: 'The meal was a bit expensive, but the quality of the food made it worth the price.', emoji: 'https://em-content.zobj.net/source/apple/391/chart-increasing_1f4c8.png' },
      { word: 'pleasant', phonetic: '/ˈpleznt/', definition: '愉快的', example: 'We had a very pleasant dining experience at that restaurant.', emoji: 'https://em-content.zobj.net/source/apple/391/smiling-face-with-smiling-eyes_1f60a.png' },
      { word: 'atmosphere', phonetic: '/ˈætməsfɪər/', definition: '氛围', example: 'The restaurant had a cozy and romantic atmosphere.', emoji: '🕯️' },
      { word: 'air-conditioned', phonetic: '/ˌeər kənˈdɪʃənd/', definition: '有空调的', example: 'The mall is fully air-conditioned, which is great in the summer.', emoji: '❄️' },
      { word: 'social place', phonetic: '/ˈsoʊʃl pleɪs/', definition: '社交场所', example: 'The local market is not just for shopping, it\'s a social place where people meet and chat.', emoji: '🧑‍🤝‍🧑' },
      { word: 'entertainment facilities', phonetic: '/ˌentərˈteɪnmənt fəˈsɪlətiz/', definition: '娱乐设施', example: 'The shopping center has great entertainment facilities, including a cinema and an arcade.', emoji: '🎮' },
      { word: 'personal service', phonetic: '/ˈpɜːrsənl ˈsɜːrvɪs/', definition: '个性化服务', example: 'Small boutiques often offer better personal service than large department stores.', emoji: '💁' },
      { word: 'friendly atmosphere', phonetic: '/ˈfrendli ˈætməsfɪər/', definition: '友好的氛围', example: 'The cafe has a warm and friendly atmosphere that makes you want to stay for hours.', emoji: '😊' },
      { word: 'support local economy', phonetic: '/səˈpɔːrt ˈloʊkl ɪˈkɑːnəmi/', definition: '支持当地经济', example: 'Shopping at local markets is a great way to support the local economy.', emoji: '🏘️' },
      { word: 'limited choice', phonetic: '/ˈlɪmɪtɪd tʃɔɪs/', definition: '有限的选择', example: 'The small shop had a limited choice of products.', emoji: '🤷' },
      { word: 'inconvenient', phonetic: '/ˌɪnkənˈviːniənt/', definition: '不方便的', example: 'The store\'s location is inconvenient as it\'s far from the city center.', emoji: '😩' },
      { word: 'lack of variety', phonetic: '/læk əv vəˈraɪəti/', definition: '缺乏多样性', example: 'I didn\'t buy anything due to the lack of variety in their collection.', emoji: '😕' },
      { word: 'not many options', phonetic: '/nɑːt ˈmeni ˈɑːpʃənz/', definition: '没有太多选择', example: 'There are not many options for vegetarians at that restaurant.', emoji: '🙅' },
      { word: 'no promotion', phonetic: '/noʊ prəˈmoʊʃn/', definition: '没有促销', example: 'I was hoping for a sale, but there was no promotion at the store.', emoji: '💸' },
      { word: 'no discounts', phonetic: '/noʊ ˈdɪskaʊnts/', definition: '没有折扣', example: 'The store has a policy of no discounts, so you always pay full price.', emoji: '🚫' },
      { word: 'old-fashioned', phonetic: '/ˌoʊldˈfæʃənd/', definition: '过时的', example: 'The store\'s layout and decor felt a bit old-fashioned.', emoji: '👵' },
      { word: 'in-store shopping', phonetic: '/ˈɪn stɔːr ˈʃɑːpɪŋ/', definition: '实体店购物', example: 'I prefer in-store shopping because I like to see the products before I buy them.', emoji: '🛍️' },
      { word: 'home delivery', phonetic: '/hoʊm dɪˈlɪvəri/', definition: '送货上门', example: 'Online stores offer the convenience of home delivery.', emoji: '🚚' },
      { word: 'see and touch the product', phonetic: '/siː ænd tʌtʃ ðə ˈprɒdʌkt/', definition: '看到并触摸产品', example: 'The advantage of physical stores is that you can see and touch the product.', emoji: '👀' },
      { word: 'try on clothes', phonetic: '/traɪ ɒn kloʊðz/', definition: '试穿衣服', example: 'It\'s important to try on clothes to make sure they fit perfectly.', emoji: '👕' },
      { word: 'shipping delay', phonetic: '/ˈʃɪpɪŋ dɪˈleɪ/', definition: '运输延迟', example: 'I was frustrated because there was a shipping delay for my order.', emoji: '⏳' },
      { word: 'return / refund', phonetic: '/rɪˈtɜːrn / ˈriːfʌnd/', definition: '退货/退款', example: 'The store has a flexible return policy, so you can get a full refund if you\'re not satisfied.', emoji: '↩️' },
      { word: 'consumption', phonetic: '/kənˈsʌmpʃn/', definition: '消费', example: 'The government is trying to boost domestic consumption.', emoji: '🛒' },
      { word: 'wide selection', phonetic: '/waɪd sɪˈlekʃn/', definition: '广泛的选择', example: 'The online store offers a wide selection of books.', emoji: '📚' },
      { word: 'price comparison', phonetic: '/praɪs kəmˈpærɪsn/', definition: '价格比较', example: 'Online shopping makes price comparison much easier.', emoji: '⚖️' },
      { word: 'risk of fake products', phonetic: '/rɪsk əv feɪk ˈprɒdʌkts/', definition: '假货风险', example: 'There\'s always a risk of fake products when you buy from unknown sellers online.', emoji: '🎭' },
      { word: 'cannot check quality', phonetic: '/ˈkænɒt tʃek ˈkwɒləti/', definition: '无法检查质量', example: 'A major disadvantage of online shopping is that you cannot check the quality of the product beforehand.', emoji: '🤔' },
      { word: 'delivery problems', phonetic: '/dɪˈlɪvəri ˈprɒbləmz/', definition: '配送问题', example: 'Delivery problems, such as delays or damaged goods, can be frustrating.', emoji: '📦' },
      { word: 'impulsive buying', phonetic: '/ɪmˈpʌlsɪv ˈbaɪɪŋ/', definition: '冲动消费', example: 'Online promotions often lead to impulsive buying.', emoji: '💸' },
      { word: 'stimulate the economy', phonetic: '/ˈstɪmjuleɪt ði ɪˈkɑːnəmi/', definition: '刺激经济', example: 'Increased consumer spending can help stimulate the economy.', emoji: '📈' },
      { word: 'increase demand', phonetic: '/ɪnˈkriːs dɪˈmænd/', definition: '增加需求', example: 'Advertising campaigns are designed to increase demand for a product.', emoji: '🔥' },
      { word: 'boost business', phonetic: '/buːst ˈbɪznəs/', definition: '促进业务', example: 'Good customer service can significantly boost business.', emoji: '🚀' },
      { word: 'over-consumption', phonetic: '/ˌoʊvər kənˈsʌmpʃn/', definition: '过度消费', example: 'Over-consumption of resources is a major environmental concern.', emoji: '🗑️' },
      { word: 'debt', phonetic: '/det/', definition: '债务', example: 'Impulsive buying can lead to credit card debt.', emoji: '💳' },
      { word: 'circulation', phonetic: '/ˌsɜːrkjəˈleɪʃn/', definition: '流通', example: 'The circulation of money is essential for a healthy economy.', emoji: '🔄' },
      { word: 'produce', phonetic: '/prəˈduːs/', definition: '产品；农产品', example: 'The supermarket sells fresh local produce.', emoji: '🍎' },
      { word: 'profits', phonetic: '/ˈprɒfɪts/', definition: '利润', example: 'The company made huge profits last year.', emoji: '💰' },
      { word: 'goods', phonetic: '/ɡʊdz/', definition: '商品；货物', example: 'The store sells a variety of household goods.', emoji: '📦' },
      { word: 'products', phonetic: '/ˈprɒdʌkts/', definition: '产品', example: 'They launched a new line of skin care products.', emoji: '🧴' },
    ],
};