import { SubTopic } from '../data-types';

export const unusualMeal: SubTopic = {
    id: 'unusual-meal',
    title: 'Meals & Dining',
    type: '事件题',
    color: 'blue',
    words: [
      { word: 'recently', phonetic: '/ˈriːsntli/', definition: '最近', example: 'I recently tried a very unusual meal during my trip to Thailand.', emoji: '📅' },
      { word: 'during a trip', phonetic: '/ˈdʊrɪŋ ə trɪp/', definition: '旅行时', example: 'I had this meal during a trip to the mountains.', emoji: '✈️' },
      { word: 'on a special occasion', phonetic: '/ɒn ə ˈspeʃəl əˈkeɪʒən/', definition: '特别的场合', example: 'We had this traditional meal on a special occasion, like a local festival.', emoji: '🎉' },
      { word: 'outdoors', phonetic: '/ˈaʊtˌdɔːrz/', definition: '在户外', example: 'The meal was cooked outdoors over an open fire.', emoji: '🏕️' },
      { word: 'in nature', phonetic: '/ɪn ˈneɪtʃər/', definition: '在自然中', example: 'Eating in nature, surrounded by trees, was a unique experience.', emoji: '🌳' },
      { word: 'with a group of people', phonetic: '/wɪð ə ɡruːp əv ˈpiːpəl/', definition: '和一群人', example: 'I shared the meal with a group of people I met on my travels.', emoji: '🧑‍🤝‍🧑' },
      { word: 'host', phonetic: '/hoʊst/', definition: '主人', example: 'The host was very welcoming and explained the dish to us.', emoji: '💁' },
      { word: 'home-made food', phonetic: '/ˌhoʊmˈmeɪd fuːd/', definition: '家常菜', example: 'It was a simple home-made food, but it tasted amazing.', emoji: '🏡' },
      { word: 'local food', phonetic: '/ˈloʊkəl fuːd/', definition: '当地特色菜', example: 'I always try to eat local food when I travel.', emoji: '🥘' },
      { word: 'traditional meal', phonetic: '/trəˈdɪʃənl miːl/', definition: '传统餐食', example: 'The village has a traditional meal that they only prepare for festivals.', emoji: '🏛️' },
      { word: 'street food', phonetic: '/striːt fuːd/', definition: '街头小吃', example: 'The city is famous for its delicious street food.', emoji: '🍢' },
      { word: 'spicy', phonetic: '/ˈspaɪsi/', definition: '辣的', example: 'The dish was very spicy, but I enjoyed the heat.', emoji: '🌶️' },
      { word: 'sweet and sour', phonetic: '/ˌswiːt ənd ˈsaʊər/', definition: '酸甜的', example: 'The fish was cooked in a sweet and sour sauce.', emoji: '🍍' },
      { word: 'unique flavor', phonetic: '/juːˈniːk ˈfleɪvər/', definition: '独特的味道', example: 'The combination of herbs gave the dish a unique flavor.', emoji: '😋' },
      { word: 'strange taste', phonetic: '/streɪndʒ teɪst/', definition: '奇怪的味道', example: 'It had a strange taste that I wasn\'t used to, but it grew on me.', emoji: '🤨' },
      { word: 'fresh ingredients', phonetic: '/freʃ ɪnˈɡriːdiənts/', definition: '新鲜食材', example: 'The chef only uses fresh ingredients from the local market.', emoji: '🥬' },
      { word: 'unexpected', phonetic: '/ˌʌnɪkˈspektɪd/', definition: '出乎意料的', example: 'The flavor was completely unexpected, but in a good way.', emoji: '😲' },
      { word: 'rare', phonetic: '/rer/', definition: '少见的', example: 'It\'s a rare dish that you can\'t find in many restaurants.', emoji: '💎' },
      { word: 'special recipe', phonetic: '/ˈspeʃəl ˈresəpi/', definition: '特别做法', example: 'The family has a special recipe that has been passed down for generations.', emoji: '📜' },
      { word: 'never tried before', phonetic: '/ˈnevər traɪd bɪˈfɔːr/', definition: '我以前从没吃过', example: 'I had never tried it before, so I was a bit hesitant at first.', emoji: '🤔' },
      { word: 'tasted different', phonetic: '/ˈteɪstɪd ˈdɪfrənt/', definition: '它和我想象的不一样', example: 'It tasted different from what I expected, but I liked it.', emoji: '🤯' },
      { word: 'different culture', phonetic: '/ˈdɪfrənt ˈkʌltʃər/', definition: '不同的文化', example: 'Trying new foods is a great way to experience a different culture.', emoji: '🌍' },
      { word: 'memorable', phonetic: '/ˈmemərəbl/', definition: '难忘的', example: 'It was a truly memorable dining experience.', emoji: '💖' },
      { word: 'unforgettable', phonetic: '/ˌʌnfərˈɡetəbl/', definition: '难以忘怀的', example: 'The taste of that meal is unforgettable.', emoji: '🥰' },
      { word: 'enjoyable', phonetic: '/ɪnˈdʒɔɪəbl/', definition: '令人愉快的', example: 'Despite being unusual, the meal was very enjoyable.', emoji: '😊' },
      { word: 'no need to cook', phonetic: '/noʊ niːd tuː kʊk/', definition: '不用做饭', example: 'The best part about eating out is that there\'s no need to cook.', emoji: '🍳' },
      { word: 'save time', phonetic: '/seɪv taɪm/', definition: '省时间', example: 'Ordering takeout can save a lot of time on busy days.', emoji: '⏳' },
      { word: 'professional chef', phonetic: '/prəˈfeʃənl ʃef/', definition: '专业厨师', example: 'The meal was prepared by a professional chef and it was delicious.', emoji: '👨‍🍳' },
      { word: 'dining atmosphere', phonetic: '/ˈdaɪnɪŋ ˈætməsfɪər/', definition: '用餐氛围', example: 'The restaurant has a wonderful dining atmosphere with soft music.', emoji: '🕯️' },
      { word: 'social experience', phonetic: '/ˈsoʊʃl ɪkˈspɪəriəns/', definition: '社交体验', example: 'Eating with friends is an important social experience.', emoji: '🧑‍🤝‍🧑' },
      { word: 'crowded', phonetic: '/ˈkraʊdɪd/', definition: '拥挤', example: 'The restaurant was too crowded and noisy on a Friday night.', emoji: '👨‍👩‍👧‍👦' },
      { word: 'noisy', phonetic: '/ˈnɔɪzi/', definition: '吵', example: 'It was so noisy that we couldn\'t hear each other talk.', emoji: '🗣️' },
      { word: 'high calories', phonetic: '/haɪ ˈkæləriz/', definition: '热量高', example: 'Fast food often contains high calories and is not very healthy.', emoji: '🍔' },
      { word: 'fast food restaurants', phonetic: '/fæst fuːd ˈrestrɑːnts/', definition: '快餐店', example: 'Fast food restaurants are popular because they are quick and cheap.', emoji: '🍟' },
      { word: 'local fast food', phonetic: '/ˈloʊkəl fæst fuːd/', definition: '本地快餐', example: 'I prefer local fast food like noodle shops to big chains.', emoji: '🍜' },
      { word: 'street food stalls', phonetic: '/striːt fuːd stɔːlz/', definition: '路边摊', example: 'The night market is full of street food stalls selling delicious snacks.', emoji: '🍢' },
      { word: 'convenient but unhealthy', phonetic: '/kənˈviːniənt bət ʌnˈhelθi/', definition: '方便但不太健康', example: 'Instant noodles are convenient but unhealthy if you eat them too often.', emoji: '🤷' },
      { word: 'order takeout', phonetic: '/ˈɔːrdər ˈteɪkaʊt/', definition: '点外卖', example: 'On lazy evenings, we often order takeout from a nearby restaurant.', emoji: '🥡' },
      { word: 'frozen food', phonetic: '/ˈfroʊzn fuːd/', definition: '速冻食品', example: 'The supermarket has a large section for frozen food like dumplings and pizzas.', emoji: '❄️' },
      { word: 'instant noodles', phonetic: '/ˈɪnstənt ˈnuːdlz/', definition: '方便面', example: 'Instant noodles are a quick meal for students.', emoji: '🍜' },
      { word: 'heat-and-eat meals', phonetic: '/hiːt ænd iːt miːlz/', definition: '加热即食餐', example: 'Heat-and-eat meals are perfect for people who don\'t have time to cook.', emoji: '🍱' },
      { word: 'quick and easy', phonetic: '/kwɪk ænd ˈiːzi/', definition: '快速简单', example: 'Making a sandwich is a quick and easy lunch option.', emoji: '🥪' },
      { word: 'go out to eat', phonetic: '/ɡoʊ aʊt tuː iːt/', definition: '出去吃', example: 'Let\'s go out to eat tonight to celebrate your promotion.', emoji: '🍽️' },
      { word: 'better atmosphere', phonetic: '/ˈbetər ˈætməsfɪər/', definition: '氛围更好', example: 'Restaurants often have a better atmosphere for a romantic dinner.', emoji: '✨' },
      { word: 'freshly cooked', phonetic: '/ˈfreʃli kʊkt/', definition: '现做的', example: 'The food tastes better because it\'s freshly cooked.', emoji: '🔥' },
      { word: 'taste better', phonetic: '/teɪst ˈbetər/', definition: '味道更好', example: 'I think restaurant food often tastes better than home-cooked meals.', emoji: '😋' },
      { word: 'get tired of', phonetic: '/ɡet ˈtaɪərd əv/', definition: '吃腻了', example: 'Sometimes I get tired of eating at home and want a change.', emoji: '😒' },
      { word: 'socialize', phonetic: '/ˈsoʊʃəlaɪz/', definition: '社交', example: 'Going out for dinner is a great way to socialize with friends.', emoji: '🥂' },
      { word: 'celebrate', phonetic: '/ˈseləbreɪt/', definition: '庆祝', example: 'We went to a fancy restaurant to celebrate our anniversary.', emoji: '🥳' },
      { word: 'dinner gatherings', phonetic: '/ˈdɪnər ˈɡæðərɪŋz/', definition: '聚餐', example: 'We often have dinner gatherings with our extended family.', emoji: '👨‍👩‍👧‍👦' },
      { word: 'family reunion', phonetic: '/ˈfæməli riːˈjuːniən/', definition: '家庭聚会', example: 'The family reunion dinner is an important tradition during the Spring Festival.', emoji: '🏡' },
      { word: 'business dinner', phonetic: '/ˈbɪznəs ˈdɪnər/', definition: '商务宴请', example: 'He has a business dinner with some clients tonight.', emoji: '💼' },
      { word: 'birthday celebration', phonetic: '/ˈbɜːrθdeɪ ˌseləˈbreɪʃn/', definition: '生日聚餐', example: 'We are planning a surprise birthday celebration for her.', emoji: '🎂' },
      { word: 'lively environment', phonetic: '/ˈlaɪvli ɪnˈvaɪrənmənt/', definition: '热闹的环境', example: 'The restaurant has a lively environment, perfect for a group of friends.', emoji: '🎉' },
      { word: 'good place to talk', phonetic: '/ɡʊd pleɪs tuː tɔːk/', definition: '适合聊天', example: 'A quiet cafe is a good place to talk and catch up.', emoji: '☕' },
      { word: 'traditional dishes', phonetic: '/trəˈdɪʃənl ˈdɪʃɪz/', definition: '传统菜肴', example: 'My grandmother taught me how to cook several traditional dishes.', emoji: '🍲' },
      { word: 'family cooking traditions', phonetic: '/ˈfæməli ˈkʊkɪŋ trəˈdɪʃənz/', definition: '家庭做菜传统', example: 'Our family cooking traditions have been passed down for generations.', emoji: '📜' },
      { word: 'regional cuisine', phonetic: '/ˈriːdʒənl kwɪˈziːn/', definition: '地方菜系', example: 'Sichuan food is a famous regional cuisine in China.', emoji: '🗺️' },
      { word: 'history of food', phonetic: '/ˈhɪstəri əv fuːd/', definition: '饮食历史', example: 'Learning about the history of food can tell you a lot about a culture.', emoji: '🏛️' },
      { word: 'taste', phonetic: '/teɪst/', definition: '味道', example: 'The taste of home-cooked food is always the best.', emoji: '👅' },
      { word: 'meaning', phonetic: '/ˈmiːnɪŋ/', definition: '意义', example: 'Many traditional dishes have a special meaning behind them.', emoji: '💖' },
      { word: 'food is part of culture', phonetic: '/fuːd ɪz pɑːrt əv ˈkʌltʃər/', definition: '食物是文化的一部分', example: 'I believe that food is part of culture and a way to connect with a country\'s heritage.', emoji: '🌍' },
      { word: 'value family meals', phonetic: '/ˈvæljuː ˈfæməli miːlz/', definition: '重视家庭一起吃饭', example: 'In our culture, we value family meals as a time for bonding.', emoji: '👨‍👩‍👧' },
      { word: 'daily life', phonetic: '/ˈdeɪli laɪf/', definition: '在我的日常生活中', example: 'In my daily life, I usually cook at home.', emoji: '🗓️' },
      { word: 'it depends on the situation', phonetic: '/ɪt dɪˈpendz ɒn ðə ˌsɪtʃuˈeɪʃn/', definition: '看情况', example: 'Whether I eat out or cook depends on the situation.', emoji: '🤔' },
      { word: 'about connection', phonetic: '/əˈbaʊt kəˈnekʃn/', definition: '是情感联系', example: 'For me, sharing a meal is not just about food, it’s about connection.', emoji: '💞' },
    ],
};