import { SubTopic } from '../data-types';

export const cantLiveWithout: SubTopic = {
    id: '2026-01-04-p2-cant-live-without',
    title: "Can't live without",
    type: '事物题',
    color: 'green',
    section: 'Part 2 & 3',
    seasons: ['2026年 1-4月', '2026年1-4月'],
    words: [
        {
            word: 'thermos bottle',
            phonetic: '/ˈθɜːrməs ˈbɒtl/',
            definition: '保温杯；保温瓶',
            example: 'I carry a thermos bottle every day to drink warm water.',
            emoji: '🥤',
            level: 'basic',
        },
        {
            word: 'vacuum flask',
            phonetic: '/ˈvækjuːm flæsk/',
            definition: '保温瓶（英式表达）',
            example: 'A vacuum flask can keep drinks warm for a long time.',
            emoji: '🫖',
            level: 'basic',
        },
        {
            word: 'fill ... with ...',
            phonetic: '/fɪl ... wɪð .../',
            definition: '用……装满……',
            example: 'I fill it with warm water before I go out.',
            emoji: '🚰',
            level: 'basic',
        },
        {
            word: 'remind me to',
            phonetic: '/rɪˈmaɪnd mi tuː/',
            definition: '提醒我去做……',
            example: 'It reminds me to drink more water.',
            emoji: '⏰',
            level: 'basic',
        },
        {
            word: 'dry throat',
            phonetic: '/draɪ θroʊt/',
            definition: '喉咙干',
            example: 'If I don’t drink enough water, I get a dry throat.',
            emoji: '😮‍💨',
            level: 'basic',
        },
        {
            word: 'low energy',
            phonetic: '/loʊ ˈenərdʒi/',
            definition: '没精神；精力低',
            example: 'When I forget to drink, I feel low energy.',
            emoji: '🪫',
            level: 'basic',
        },
        {
            word: 'keep ... warm',
            phonetic: '/kiːp ... wɔːrm/',
            definition: '让……保持温度；保温',
            example: 'It can keep water warm in winter.',
            emoji: '🔥',
            level: 'basic',
        },
        {
            word: 'save money',
            phonetic: '/seɪv ˈmʌni/',
            definition: '省钱',
            example: 'It helps me save money because I buy fewer drinks.',
            emoji: '💰',
            level: 'basic',
        },
        {
            word: 'sugary drinks',
            phonetic: '/ˈʃʊɡəri drɪŋks/',
            definition: '含糖饮料',
            example: 'I try not to drink too many sugary drinks.',
            emoji: '🥤',
            level: 'basic',
        },
        {
            word: 'better for the environment',
            phonetic: '/ˈbetər fɔːr ði ɪnˈvaɪrənmənt/',
            definition: '更环保',
            example: 'Using one bottle again and again is better for the environment.',
            emoji: '🌍',
            level: 'basic',
        },
        {
            word: 'routine',
            phonetic: '/ruːˈtiːn/',
            definition: '日常；作息；习惯',
            example: 'It is part of my daily routine.',
            emoji: '📅',
            level: 'basic',
        },
        {
            word: 'contain',
            phonetic: '/kənˈteɪn/',
            definition: '包含；容纳',
            example: 'My bag contains some basic necessities for the whole day.',
            emoji: '📦',
            level: 'basic',
        },
        {
            word: 'tissues',
            phonetic: '/ˈtɪʃuːz/',
            definition: '纸巾',
            example: 'I always carry tissues in case I need to clean my hands.',
            emoji: '🧻',
            level: 'basic',
        },
        {
            word: 'paper tissues',
            phonetic: '/ˈpeɪpər ˈtɪʃuːz/',
            definition: '纸巾（同 tissues）',
            example: 'I keep some paper tissues in my backpack.',
            emoji: '🧻',
            level: 'basic',
        },
        {
            word: 'necessities',
            phonetic: '/nəˈsesətiz/',
            definition: '必需品',
            example: 'Water and tissues are daily necessities for me.',
            emoji: '🧰',
            level: 'basic',
        },
        {
            word: 'identity card',
            phonetic: '/aɪˈdentəti kɑːrd/',
            definition: '身份证',
            example: 'In some situations, you need your identity card to enter a building.',
            emoji: '🪪',
            level: 'basic',
        },
        {
            word: 'attend lectures',
            phonetic: '/əˈtend ˈlektʃərz/',
            definition: '上课；听讲座',
            example: 'I attend lectures in the morning, so I bring my thermos with me.',
            emoji: '🎓',
            level: 'basic',
        },
        {
            word: 'prepared',
            phonetic: '/prɪˈperd/',
            definition: '准备好的；有准备的',
            example: 'With these small items, I feel prepared for my day.',
            emoji: '✅',
            level: 'basic',
        },
    ],
};
