import { SubTopic } from '../data-types';
import { getManyFromPool } from '../pool/utils';

export const interestingBuilding: SubTopic = {
    id: '2026-01-04-p2-interesting-building',
    title: 'Interesting building',
    type: '地点题',
    color: 'green',
    section: 'Part 2 & 3',
    seasons: ['2026年 1-4月', '2026年1-4月'],
    words: [
        {
            word: 'central part',
            phonetic: '/ˈsentrəl pɑːrt/',
            definition: '中心区域；核心部分',
            example: 'It is in the central part of the city, so it is easy to visit.',
            emoji: '📍',
            level: 'basic',
        },
        {
            word: 'be located in',
            phonetic: '/bi loʊˈkeɪtɪd ɪn/',
            definition: '位于……',
            example: 'The building is located in the city centre, so it is easy to reach.',
            emoji: '📍',
            level: 'basic',
        },
        {
            word: 'Pearl River',
            phonetic: '/pɜːrl ˈrɪvər/',
            definition: '珠江（Pearl River）',
            example: 'It is close to the Pearl River, so the view is great at night.',
            emoji: '🌊',
            level: 'basic',
        },
        {
            word: 'twisted shape',
            phonetic: '/ˈtwɪstɪd ʃeɪp/',
            definition: '扭曲/扭转的形状',
            example: 'It has a twisted shape, which makes it look unique.',
            emoji: '🌀',
            level: 'basic',
        },
        {
            word: 'bright',
            phonetic: '/braɪt/',
            definition: '明亮的',
            example: 'At night, the lights are bright and colorful.',
            emoji: '💡',
            level: 'basic',
        },
        {
            word: 'whole city',
            phonetic: '/hoʊl ˈsɪti/',
            definition: '整个城市',
            example: 'From the top, you can see the whole city clearly.',
            emoji: '🏙️',
            level: 'basic',
        },
        {
            word: 'whole view',
            phonetic: '/hoʊl vjuː/',
            definition: '整体景色；全景',
            example: 'From the top, you can enjoy the whole view of Guangzhou.',
            emoji: '🌇',
            level: 'basic',
        },
        {
            word: 'outside view',
            phonetic: '/ˌaʊtˈsaɪd vjuː/',
            definition: '外部景色；外景',
            example: 'The outside view is amazing, especially at night.',
            emoji: '🏞️',
            level: 'basic',
        },
        {
            word: 'elevator',
            phonetic: '/ˈeləveɪtər/',
            definition: '电梯',
            example: 'Visitors can take an elevator to the top of the tower.',
            emoji: '🛗',
            level: 'basic',
        },
        {
            word: 'Ferris wheel',
            phonetic: '/ˈferɪs wiːl/',
            definition: '摩天轮',
            example: 'There is a Ferris wheel nearby, and many people take photos there.',
            emoji: '🎡',
            level: 'basic',
        },
        ...getManyFromPool(['lively', 'landmark', 'entertainment'], 'basic'),
        ...getManyFromPool(['sightseeing', 'impressed'], 'basic'),
        {
            word: 'tourism',
            phonetic: '/ˈtʊrɪzəm/',
            definition: '旅游；旅游业',
            example: 'This landmark is important for local tourism.',
            emoji: '🧳',
            level: 'basic',
        },
        {
            word: 'play an important role in',
            phonetic: '/pleɪ ən ɪmˈpɔːrtnt roʊl ɪn/',
            definition: '在……中起重要作用',
            example: 'It plays an important role in the city’s tourism.',
            emoji: '⭐',
            level: 'basic',
        },
        {
            word: 'represent',
            phonetic: '/ˌreprɪˈzent/',
            definition: '代表；象征',
            example: 'The tower represents the modern side of Guangzhou.',
            emoji: '🏙️',
            level: 'basic',
        },
        {
            word: 'relaxation',
            phonetic: '/ˌriːlækˈseɪʃn/',
            definition: '放松',
            example: 'For many people, visiting this place is a kind of relaxation.',
            emoji: '😌',
            level: 'basic',
        },
    ],
};
