import { SubTopic } from '../data-types';

export const recentMovie: SubTopic = {
    id: '2026-01-04-p2-movie-enjoyed-recently',
    title: 'Recent movie',
    type: '事物题',
    color: 'green',
    section: 'Part 2 & 3',
    seasons: ['2026年 1-4月', '2026年1-4月'],
    words: [
        {
            word: 'recently',
            phonetic: '/ˈriːs(ə)ntli/',
            definition: '最近；不久前',
            example: 'I watched a movie recently and enjoyed it a lot.',
            emoji: '🕒',
            level: 'basic',
        },
        {
            word: 'Avatar',
            phonetic: '/ˈævətɑːr/',
            definition: '《阿凡达》（电影名）',
            example: 'Avatar 3 is a popular science fiction movie.',
            emoji: '🎬',
            level: 'basic',
        },
        {
            word: 'planet',
            phonetic: '/ˈplænɪt/',
            definition: '星球',
            example: 'The story happens on a new planet.',
            emoji: '🪐',
            level: 'basic',
        },
        {
            word: 'alien',
            phonetic: '/ˈeɪliən/',
            definition: '外星人',
            example: 'Many aliens live on the planet.',
            emoji: '👽',
            level: 'basic',
        },
        {
            word: 'resource',
            phonetic: '/rɪˈzɔːrs/',
            definition: '资源',
            example: 'A natural resource can be very valuable.',
            emoji: '⛏️',
            level: 'basic',
        },
        {
            word: 'conflict',
            phonetic: '/ˈkɑːnflɪkt/',
            definition: '冲突',
            example: 'There is a big conflict between humans and aliens.',
            emoji: '⚔️',
            level: 'basic',
        },
        {
            word: 'culture',
            phonetic: '/ˈkʌltʃər/',
            definition: '文化',
            example: 'The movie shows their culture and lifestyle.',
            emoji: '🏺',
            level: 'basic',
        },
        {
            word: 'reason',
            phonetic: '/ˈriːz(ə)n/',
            definition: '原因',
            example: 'The main reason I watched it was that it was popular.',
            emoji: '💡',
            level: 'basic',
        },
        {
            word: 'disappointed',
            phonetic: '/ˌdɪsəˈpɔɪntɪd/',
            definition: '失望的',
            example: 'I felt a little disappointed after watching it.',
            emoji: '😞',
            level: 'basic',
        },
        {
            word: 'excellent',
            phonetic: '/ˈeksələnt/',
            definition: '极好的；优秀的',
            example: 'The special effects were excellent.',
            emoji: '🌟',
            level: 'basic',
        },
        {
            word: 'expect',
            phonetic: '/ɪkˈspekt/',
            definition: '期待；预期',
            example: 'I didn’t expect it to be so long.',
            emoji: '🔮',
            level: 'basic',
        },
        {
            word: 'expected',
            phonetic: '/ɪkˈspektɪd/',
            definition: '预期的；期待的',
            example: 'It was not as good as I expected.',
            emoji: '🔮',
            level: 'basic',
        },
        {
            word: 'waste time',
            phonetic: '/weɪst taɪm/',
            definition: '浪费时间',
            example: 'I felt like I wasted time on it.',
            emoji: '⏳',
            level: 'basic',
        },
        {
            word: 'special effect',
            phonetic: '/ˈspeʃl ɪˈfekt/',
            definition: '特效',
            example: 'The movie has great special effect.',
            emoji: '✨',
            level: 'basic',
        },
    ],
};
