
import { SubTopic } from './data-types';

export const highFreqGeneral: SubTopic = {
    id: 'hf-general',
    title: '万能高频动词',
    type: '高频词',
    color: 'purple',
    section: 'High Frequency',
    words: [
        { word: 'acquire', phonetic: '/əˈkwaɪər/', definition: '获得', example: 'It is a good way to acquire new knowledge.', emoji: '📥' },
        { word: 'essential', phonetic: '/ɪˈsenʃl/', definition: '必不可少的', example: 'Practice is essential for success.', emoji: '✨' },
    ]
};

export const highFreqExpressingLikes: SubTopic = {
    id: 'hf-expressing-likes',
    title: '表示喜欢 (Expressing Likes)',
    type: '高频词',
    color: 'green',
    section: 'High Frequency',
    words: [
        { word: '... is my cup of tea', level: 'advanced', phonetic: '', definition: '……是我的菜/我很喜欢……', example: 'Classical music is my cup of tea.', emoji: '☕️' },
        { word: 'I adore ...', level: 'advanced', phonetic: '', definition: '我非常喜欢……', example: 'I adore animals, especially cats.', emoji: '😍' },
        { word: 'I generally prefer ... to ...', level: 'basic', phonetic: '', definition: '一般来说，我更喜欢……而不是……', example: 'I generally prefer tea to coffee.', emoji: '↔️' },
        { word: 'I have a particular fondness for ...', level: 'advanced', phonetic: '', definition: '我对……情有独钟', example: 'I have a particular fondness for street food.', emoji: '💛' },
        { word: 'I like ...', level: 'basic', phonetic: '', definition: '我喜欢……', example: 'I like doing some exercise after work.', emoji: '👍' },
        { word: 'I simply adore ...', level: 'advanced', phonetic: '', definition: '我真的特别喜欢……', example: 'I simply adore rainy days when I can stay at home.', emoji: '🥰' },
        { word: 'I\'m fairly keen on ...', level: 'advanced', phonetic: '', definition: '我挺喜欢/挺热衷于……', example: 'I\'m fairly keen on photography.', emoji: '📷' },
        { word: 'I\'m fascinated by ...', level: 'advanced', phonetic: '', definition: '我对……很着迷/很好奇', example: 'I\'m fascinated by how AI works.', emoji: '🧠' },
        { word: 'I\'m obsessed with ...', level: 'advanced', phonetic: '', definition: '我对……很上头/痴迷……', example: 'I\'m obsessed with this TV series.', emoji: '🎬' },
        { word: 'I\'m pretty fond of ...', level: 'advanced', phonetic: '', definition: '我挺喜欢……', example: 'I\'m pretty fond of spicy food.', emoji: '🌶️' },
        { word: 'I\'m quite a big fan of ...', level: 'advanced', phonetic: '', definition: '我非常喜欢……/是……的忠实粉丝', example: 'I\'m quite a big fan of basketball.', emoji: '🏀' },
        { word: 'I\'m quite enthusiastic/passionate about ...', level: 'advanced', phonetic: '', definition: '我对……很有热情/很热衷于……', example: 'I\'m quite enthusiastic about learning languages.', emoji: '🔥' },
        { word: 'I\'m really into ...', level: 'basic', phonetic: '', definition: '我真的很喜欢/很沉迷于……', example: 'I\'m really into indie music these days.', emoji: '🎧' },
        { word: 'I\'m totally mad about ...', level: 'advanced', phonetic: '', definition: '我超级喜欢……/对……狂热', example: 'I\'m totally mad about hiking.', emoji: '⛰️' },
        { word: 'I\'m enthusiastic about ...', level: 'basic', phonetic: '', definition: '我对……很有热情', example: 'I\'m enthusiastic about volunteering.', emoji: '🙌' },
        { word: 'I\'m interested in ...', level: 'basic', phonetic: '', definition: '我对……感兴趣', example: 'I\'m interested in architecture.', emoji: '🏛️' },
        { word: 'I\'m passionate about ...', level: 'advanced', phonetic: '', definition: '我对……充满热情', example: 'I\'m passionate about helping others.', emoji: '❤️' },
        { word: 'It appeals to me.', level: 'advanced', phonetic: '', definition: '它很吸引我/我很喜欢它', example: 'Working from home really appeals to me.', emoji: '✨' },
    ],
};

export const highFreqExpressingDislikes: SubTopic = {
    id: 'hf-expressing-dislikes',
    title: '表示不喜欢 (Expressing Dislikes)',
    type: '高频词',
    color: 'blue',
    section: 'High Frequency',
    words: [
        { word: '... is not my cup of tea', level: 'advanced', phonetic: '', definition: '……不是我的菜/我不太喜欢……', example: 'Horror movies are not my cup of tea.', emoji: '☕️' },
        { word: '... is not my thing', level: 'advanced', phonetic: '', definition: '……不是我喜欢的东西/不合我口味', example: 'Clubbing is not my thing.', emoji: '🙅' },
        { word: 'I detest ...', level: 'advanced', phonetic: '', definition: '我非常讨厌……', example: 'I detest wasting time in traffic.', emoji: '😖' },
        { word: 'I dislike ...', level: 'basic', phonetic: '', definition: '我不喜欢……', example: 'I dislike getting up early.', emoji: '👎' },
        { word: 'I despise ...', level: 'advanced', phonetic: '', definition: '我鄙视/厌恶……', example: 'I despise people who lie all the time.', emoji: '😤' },
        { word: 'I don\'t care for ...', level: 'advanced', phonetic: '', definition: '我不太喜欢……', example: 'I don\'t care for very sweet desserts.', emoji: '🍰' },
        { word: 'I don\'t think much of ...', level: 'advanced', phonetic: '', definition: '我对……评价不高/不怎么喜欢……', example: 'I don\'t think much of online gossip.', emoji: '🤷' },
        { word: 'I hate ...', level: 'basic', phonetic: '', definition: '我讨厌……', example: 'I hate being late.', emoji: '⏰' },
        { word: 'I loathe ...', level: 'advanced', phonetic: '', definition: '我非常厌恶……', example: 'I loathe people talking loudly on the phone.', emoji: '😣' },
        { word: 'I really can\'t stand ...', level: 'advanced', phonetic: '', definition: '我真的受不了……', example: 'I really can\'t stand noisy neighbors.', emoji: '🤯' },
        { word: 'I\'m not interested in ...', level: 'basic', phonetic: '', definition: '我对……不感兴趣', example: 'I\'m not interested in celebrity news.', emoji: '📰' },
        { word: 'I\'m not into it.', level: 'basic', phonetic: '', definition: '我不喜欢/我不太感兴趣', example: 'I tried it once, but I\'m not into it.', emoji: '🚫' },
        { word: 'I\'m tired of ...', level: 'basic', phonetic: '', definition: '我厌倦了……', example: 'I\'m tired of eating fast food every day.', emoji: '🥱' },
        { word: 'I\'m not much of a fan of ...', level: 'advanced', phonetic: '', definition: '我不太喜欢……', example: 'I\'m not much of a fan of extreme sports.', emoji: '⛔️' },
        { word: 'I\'m not so keen on ...', level: 'advanced', phonetic: '', definition: '我不太喜欢……', example: 'I\'m not so keen on crowded places.', emoji: '🚶‍➡️' },
        { word: 'I\'m really not that fond of ...', level: 'advanced', phonetic: '', definition: '我真的不怎么喜欢……', example: 'I\'m really not that fond of bitter coffee.', emoji: '🙃' },
    ],
};

export const highFreqExpressingMaybeProbability: SubTopic = {
    id: 'hf-expressing-maybe-probability',
    title: '表示也许 (Expressing Maybe/Probability)',
    type: '高频词',
    color: 'yellow',
    section: 'High Frequency',
    words: [
        { word: 'may', level: 'basic', phonetic: '/meɪ/', definition: '也许/可能（情态动词）', example: 'I may go for a walk later.', emoji: '🤔' },
        { word: 'might', level: 'basic', phonetic: '/maɪt/', definition: '可能/也许（比 may 更不确定）', example: 'I might stay in and watch a movie tonight.', emoji: '🎲' },
        { word: 'likely', level: 'basic', phonetic: '/ˈlaɪkli/', definition: '可能的；很可能', example: 'It\'s likely that I\'ll take the subway.', emoji: '📈' },
        { word: 'perhaps', level: 'advanced', phonetic: '/pərˈhæps/', definition: '也许；可能', example: 'Perhaps I\'ll travel abroad after graduation.', emoji: '🤔' },
        { word: 'possibly', level: 'advanced', phonetic: '/ˈpɑːsəbli/', definition: '可能地；也许', example: 'We could possibly meet this weekend.', emoji: '🧩' },
        { word: 'probably', level: 'basic', phonetic: '/ˈprɑːbəbli/', definition: '很可能；大概', example: 'I\'ll probably have a quick lunch.', emoji: '✅' },
        { word: 'A common situation is ...', level: 'advanced', phonetic: '', definition: '常见的情况是……', example: 'A common situation is that people check their phones first thing in the morning.', emoji: '🧠' },
        { word: 'In some cases, ...', level: 'advanced', phonetic: '', definition: '在某些情况下，……', example: 'In some cases, it\'s better to keep things simple.', emoji: '🧩' },
        { word: 'In some situations, ...', level: 'advanced', phonetic: '', definition: '在一些情境下，……', example: 'In some situations, I prefer to stay quiet and listen.', emoji: '🎭' },
    ],
};

export const highFreqExpressingHappiness: SubTopic = {
    id: 'hf-expressing-happiness',
    title: '表示开心 (Expressing Happiness)',
    type: '高频词',
    color: 'green',
    section: 'High Frequency',
    words: [
        { word: 'rejoice', level: 'advanced', phonetic: '/rɪˈdʒɔɪs/', definition: '欢欣；欣喜', example: 'We rejoiced at the good news.', emoji: '🎉' },
        { word: 'amused', level: 'basic', phonetic: '/əˈmjuːzd/', definition: '被逗乐的', example: 'I was amused by his jokes.', emoji: '😄' },
        { word: 'cheerful', level: 'basic', phonetic: '/ˈtʃɪrfl/', definition: '愉快的；兴高采烈的', example: 'She\'s always cheerful in the morning.', emoji: '😊' },
        { word: 'content', level: 'advanced', phonetic: '/kənˈtent/', definition: '满足的；知足的', example: 'I feel content with my life right now.', emoji: '😌' },
        { word: 'delighted', level: 'basic', phonetic: '/dɪˈlaɪtɪd/', definition: '高兴的；欣喜的', example: 'I was delighted to hear that I passed.', emoji: '😁' },
        { word: 'happy', level: 'basic', phonetic: '/ˈhæpi/', definition: '开心的', example: 'I\'m happy with my decision.', emoji: '🙂' },
        { word: 'joyful', level: 'advanced', phonetic: '/ˈdʒɔɪfl/', definition: '充满喜悦的', example: 'The festival was joyful.', emoji: '🥳' },
        { word: 'overjoyed', level: 'advanced', phonetic: '/ˌoʊvərˈdʒɔɪd/', definition: '欣喜若狂的', example: 'My parents were overjoyed when I got the offer.', emoji: '🤩' },
        { word: 'pleased', level: 'basic', phonetic: '/pliːzd/', definition: '满意的；高兴的', example: 'I\'m pleased with the result.', emoji: '👍' },
        { word: 'thrilled', level: 'advanced', phonetic: '/θrɪld/', definition: '激动的；兴奋的', example: 'I was thrilled to meet my favorite singer.', emoji: '🎊' },
        { word: 'like a dog with two tails', level: 'advanced', phonetic: '', definition: '高兴得不得了', example: 'I was like a dog with two tails when I got the ticket.', emoji: '🐶' },
        { word: 'brighten up the day', level: 'advanced', phonetic: '', definition: '让一天都变得更开心/更明亮', example: 'A short chat with a friend can brighten up my day.', emoji: '☀️' },
        { word: 'cheer sb. up', level: 'advanced', phonetic: '', definition: '让某人振作/开心起来', example: 'I tried to cheer my sister up after her exam.', emoji: '🎈' },
        { word: 'elevate one\'s mood', level: 'advanced', phonetic: '', definition: '提升情绪', example: 'Music can elevate my mood instantly.', emoji: '🎵' },
        { word: 'full of the joys of spring', level: 'advanced', phonetic: '', definition: '洋溢着欢乐/精神抖擞', example: 'She walked in, full of the joys of spring.', emoji: '🌸' },
        { word: 'happy camper', level: 'advanced', phonetic: '', definition: '很开心/很满意的人', example: 'After a good meal, I\'m a happy camper.', emoji: '🏕️' },
        { word: 'have a blast', level: 'basic', phonetic: '', definition: '玩得很嗨/玩得很开心', example: 'We had a blast at the party.', emoji: '🎆' },
        { word: 'in a good mood', level: 'basic', phonetic: '', definition: '心情很好', example: 'I\'m in a good mood because the weather is great.', emoji: '😄' },
        { word: 'in high spirits', level: 'advanced', phonetic: '', definition: '兴致很高', example: 'Everyone was in high spirits before the trip.', emoji: '🕺' },
        { word: 'in seventh heaven', level: 'advanced', phonetic: '', definition: '极其幸福/飘飘然', example: 'I was in seventh heaven when I got the scholarship.', emoji: '😇' },
        { word: 'increase the happiness', level: 'advanced', phonetic: '', definition: '提升幸福感/增加快乐', example: 'Doing exercise can increase the happiness in my life.', emoji: '📈' },
        { word: 'jump for joy', level: 'advanced', phonetic: '', definition: '高兴得跳起来', example: 'I jumped for joy when I heard the news.', emoji: '🤸' },
        { word: 'like the cat that got the cream', level: 'advanced', phonetic: '', definition: '得意洋洋/心满意足', example: 'He looked like the cat that got the cream after winning.', emoji: '🐱' },
        { word: 'on cloud nine', level: 'advanced', phonetic: '', definition: '欣喜若狂/飘飘然', example: 'I was on cloud nine after the interview.', emoji: '☁️' },
        { word: 'on top of the world', level: 'advanced', phonetic: '', definition: '感觉自己无比幸福/状态爆棚', example: 'After I finished the marathon, I felt on top of the world.', emoji: '🌍' },
        { word: 'over the moon', level: 'advanced', phonetic: '', definition: '高兴得不得了', example: 'My parents were over the moon about my results.', emoji: '🌙' },
        { word: 'walk on air', level: 'advanced', phonetic: '', definition: '走路带风/飘飘然', example: 'I was walking on air after receiving the gift.', emoji: '🪽' },
        { word: 'wild with joy', level: 'advanced', phonetic: '', definition: '欣喜若狂', example: 'The kids were wild with joy when school ended.', emoji: '🎈' },
    ],
};

export const highFreqExpressingSadness: SubTopic = {
    id: 'hf-expressing-sadness',
    title: '表示伤心 (Expressing Sadness)',
    type: '高频词',
    color: 'blue',
    section: 'High Frequency',
    words: [
        { word: 'deflate', level: 'advanced', phonetic: '/dɪˈfleɪt/', definition: '使泄气；使沮丧', example: 'I felt deflated after failing the test.', emoji: '🎈' },
        { word: 'grieve', level: 'advanced', phonetic: '/ɡriːv/', definition: '悲痛；哀悼', example: 'She grieved for her lost pet.', emoji: '🖤' },
        { word: 'broken-hearted', level: 'advanced', phonetic: '/ˌbroʊkənˈhɑːrtɪd/', definition: '心碎的', example: 'I was broken-hearted when it ended.', emoji: '💔' },
        { word: 'choked up', level: 'advanced', phonetic: '/tʃoʊkt ʌp/', definition: '哽咽的；说不出话的', example: 'I was choked up during the speech.', emoji: '😢' },
        { word: 'gloomy', level: 'basic', phonetic: '/ˈɡluːmi/', definition: '忧郁的；阴沉的', example: 'The room felt gloomy without sunlight.', emoji: '☁️' },
        { word: 'hurt', level: 'basic', phonetic: '/hɜːrt/', definition: '受伤的；难过的', example: 'It really hurt when he forgot my birthday.', emoji: '🥀' },
        { word: 'inconsolable', level: 'advanced', phonetic: '/ˌɪnkənˈsoʊləbl/', definition: '无法安慰的', example: 'She was inconsolable after the news.', emoji: '😭' },
        { word: 'melancholy', level: 'advanced', phonetic: '/ˈmelənkɑːli/', definition: '忧郁；伤感', example: 'There was a touch of melancholy in his voice.', emoji: '🌧️' },
        { word: 'miserable', level: 'basic', phonetic: '/ˈmɪzrəbl/', definition: '痛苦的；难受的', example: 'I felt miserable after the argument.', emoji: '😞' },
        { word: 'mournful', level: 'advanced', phonetic: '/ˈmɔːrnfl/', definition: '悲伤的', example: 'He gave me a mournful look.', emoji: '🕯️' },
        { word: 'sad', level: 'basic', phonetic: '/sæd/', definition: '伤心的', example: 'I felt sad when the holidays ended.', emoji: '😔' },
        { word: 'unhappy', level: 'basic', phonetic: '/ʌnˈhæpi/', definition: '不开心的', example: 'I was unhappy with the service.', emoji: '🙁' },
        { word: 'be down in the dumps', level: 'advanced', phonetic: '', definition: '情绪低落', example: 'I was down in the dumps after a long day.', emoji: '⬇️' },
        { word: 'cloud up', level: 'advanced', phonetic: '', definition: '（心情/表情）变得阴沉', example: 'His face clouded up when he heard the news.', emoji: '☁️' },
        { word: 'cry one\'s heart out', level: 'advanced', phonetic: '', definition: '痛哭一场', example: 'She cried her heart out after the breakup.', emoji: '😭' },
        { word: 'down in the mouth', level: 'advanced', phonetic: '', definition: '情绪低落/垂头丧气', example: 'He looked a bit down in the mouth.', emoji: '😟' },
        { word: 'feel blue', level: 'advanced', phonetic: '', definition: '感到忧郁', example: 'I feel blue on rainy days.', emoji: '💙' },
        { word: 'feel like crying', level: 'basic', phonetic: '', definition: '想哭', example: 'Sometimes I feel like crying for no reason.', emoji: '😢' },
        { word: 'get a face like a wet weekend', level: 'advanced', phonetic: '', definition: '脸色难看/一脸不高兴', example: 'He got a face like a wet weekend after losing.', emoji: '☔️' },
        { word: 'in a bad mood', level: 'basic', phonetic: '', definition: '心情不好', example: 'I\'m in a bad mood when I don\'t get enough sleep.', emoji: '😞' },
        { word: 'in low spirits', level: 'advanced', phonetic: '', definition: '情绪低落', example: 'She was in low spirits after the meeting.', emoji: '⬇️' },
        { word: 'lump in one\'s throat', level: 'advanced', phonetic: '', definition: '喉咙哽住/哽咽', example: 'I had a lump in my throat during the farewell.', emoji: '😢' },
        { word: 'one\'s heart sinks', level: 'advanced', phonetic: '', definition: '心一沉', example: 'My heart sank when I saw the score.', emoji: '⬇️' },
        { word: 'out of sorts', level: 'advanced', phonetic: '', definition: '状态不好/心情不佳', example: 'I\'ve been out of sorts lately.', emoji: '😕' },
        { word: 'with a heavy heart', level: 'advanced', phonetic: '', definition: '怀着沉重的心情', example: 'With a heavy heart, I said goodbye.', emoji: '🪨' },
    ],
};

export const highFreqExpressingAnger: SubTopic = {
    id: 'hf-expressing-anger',
    title: '表示生气 (Expressing Anger)',
    type: '高频词',
    color: 'purple',
    section: 'High Frequency',
    words: [
        { word: 'angry', level: 'basic', phonetic: '/ˈæŋɡri/', definition: '生气的', example: 'I get angry when people cut in line.', emoji: '😠' },
        { word: 'annoyed', level: 'basic', phonetic: '/əˈnɔɪd/', definition: '恼火的', example: 'I was annoyed by the noise.', emoji: '😒' },
        { word: 'cross', level: 'advanced', phonetic: '/krɔːs/', definition: '生气的（英式口语）', example: 'My mum was cross with me for being late.', emoji: '😤' },
        { word: 'furious', level: 'advanced', phonetic: '/ˈfjʊriəs/', definition: '暴怒的', example: 'He was furious about the delay.', emoji: '🤬' },
        { word: 'irritated', level: 'advanced', phonetic: '/ˈɪrɪteɪtɪd/', definition: '恼怒的', example: 'I was irritated by constant interruptions.', emoji: '😑' },
        { word: 'mad', level: 'basic', phonetic: '/mæd/', definition: '生气的（口语）', example: 'I was mad at him for lying to me.', emoji: '😡' },
        { word: 'red-hot', level: 'advanced', phonetic: '', definition: '非常愤怒的', example: 'I was red-hot with anger for a moment.', emoji: '🔥' },
        { word: 'upset', level: 'basic', phonetic: '/ʌpˈset/', definition: '心烦的；生气的', example: 'I was upset about what happened.', emoji: '😣' },
        { word: 'be pissed off', level: 'advanced', phonetic: '', definition: '非常生气（口语/略粗）', example: 'I was really pissed off when my flight got canceled.', emoji: '🚫' },
        { word: 'blow one\'s top', level: 'advanced', phonetic: '', definition: '勃然大怒', example: 'He blew his top when he heard the news.', emoji: '💥' },
        { word: 'burn someone up', level: 'advanced', phonetic: '', definition: '让某人火大', example: 'It really burns me up when people are rude.', emoji: '🔥' },
        { word: 'burst with anger', level: 'advanced', phonetic: '', definition: '气炸了', example: 'She was bursting with anger.', emoji: '💢' },
        { word: 'drive someone nuts', level: 'advanced', phonetic: '', definition: '把某人逼疯/惹毛', example: 'That noise drives me nuts.', emoji: '🤯' },
        { word: 'freak out', level: 'advanced', phonetic: '', definition: '抓狂/情绪失控', example: 'He freaked out and started shouting.', emoji: '😵' },
        { word: 'get on one\'s nerves', level: 'advanced', phonetic: '', definition: '惹恼某人', example: 'Loud chewing really gets on my nerves.', emoji: '🧨' },
        { word: 'go bananas', level: 'advanced', phonetic: '', definition: '抓狂/暴怒', example: 'My dad goes bananas when the internet is down.', emoji: '🍌' },
        { word: 'have a cow', level: 'advanced', phonetic: '', definition: '大惊小怪/生大气', example: 'Don\'t have a cow—it\'s not a big deal.', emoji: '🐄' },
        { word: 'have a fit', level: 'advanced', phonetic: '', definition: '大发脾气', example: 'He had a fit when he saw the mess.', emoji: '😤' },
        { word: 'hit the ceiling', level: 'advanced', phonetic: '', definition: '暴跳如雷', example: 'My boss hit the ceiling when he found out.', emoji: '🏠' },
        { word: 'hit the roof', level: 'advanced', phonetic: '', definition: '怒不可遏', example: 'She hit the roof over the extra charges.', emoji: '🏚️' },
        { word: 'in a rage', level: 'advanced', phonetic: '', definition: '暴怒中', example: 'He stormed out in a rage.', emoji: '😡' },
        { word: 'lose one\'s temper', level: 'advanced', phonetic: '', definition: '发脾气/失去耐心', example: 'I try not to lose my temper in public.', emoji: '🌡️' },
        { word: 'make one\'s blood boil', level: 'advanced', phonetic: '', definition: '让人火冒三丈', example: 'It makes my blood boil when people cheat.', emoji: '🩸' },
        { word: 'tick sb. off', level: 'advanced', phonetic: '', definition: '惹恼某人（口语）', example: 'It ticks me off when people are late.', emoji: '😤' },
    ],
};

// 后续可以继续在此处 export const 其他高频词类别
