
import { SubTopic } from './data-types';

export const hometown: SubTopic = {
    id: 'p1-hometown',
    title: 'Hometown',
    type: '基础题',
    color: 'green',
    section: 'Part 1',
    wordSections: [
        {
            title: '基础描述',
            words: [
                { word: 'birthplace', level: 'basic', phonetic: '/ˈbɜːrθpleɪs/', definition: '出生地', example: 'Beijing is my birthplace and I grew up there.', emoji: '🏠' },
                { word: 'province', level: 'basic', phonetic: '/ˈprɑːvɪns/', definition: '省', example: 'My hometown is in Jiangsu Province.', emoji: '🗺️' },
                { word: 'city', level: 'basic', phonetic: '/ˈsɪti/', definition: '城市', example: 'It is a small city, but it has everything I need.', emoji: '🏙️' },
                { word: 'town', level: 'basic', phonetic: '/taʊn/', definition: '小镇', example: 'It is a quiet town where people know each other.', emoji: '🏘️' },
                { word: 'scenery', level: 'basic', phonetic: '/ˈsiːnəri/', definition: '风景', example: 'The scenery in my hometown is breathtaking.', emoji: '🏔️' },
                { word: 'landscape', level: 'basic', phonetic: '/ˈlændskeɪp/', definition: '地貌；景观', example: 'The landscape is a mix of mountains and rivers.', emoji: '🏞️' },
                { word: 'nature', level: 'basic', phonetic: '/ˈneɪtʃər/', definition: '大自然；自然界', example: 'My hometown is close to nature, with mountains and rivers nearby.', emoji: '🌿' },
                { word: 'climate', level: 'basic', phonetic: '/ˈklaɪmət/', definition: '气候', example: 'The climate is mild, so it is comfortable to live there.', emoji: '🌤️' },
                { word: 'weather', level: 'basic', phonetic: '/ˈweðər/', definition: '天气', example: 'The weather can be unpredictable in spring.', emoji: '🌦️' },
                { word: 'facility', level: 'basic', phonetic: '/fəˈsɪləti/', definition: '设施', example: 'The city has good public facilities like parks and libraries.', emoji: '🏗️' },
                { word: 'skyscraper', level: 'basic', phonetic: '/ˈskaɪˌskreɪpər/', definition: '摩天大楼', example: 'There are a few skyscrapers in the new district.', emoji: '🏙️' },
                { word: 'residents', level: 'basic', phonetic: '/ˈrezɪdənts/', definition: '居民', example: 'The local residents are very friendly and welcoming.', emoji: '🧑‍🤝‍🧑' },
                { word: 'historical', level: 'basic', phonetic: '/hɪˈstɔːrɪkl/', definition: '历史悠久的', example: 'There are many historical buildings in the city center.', emoji: '🏛️' },
            ]
        },
        {
            title: '进阶描述',
            words: [
                { word: 'urbanization', level: 'advanced', phonetic: '/ˌɜːrbənaɪˈzeɪʃn/', definition: '城市化', example: 'The town has seen rapid urbanization in recent years.', emoji: '🏙️' },
                { word: 'pace of life', level: 'advanced', phonetic: '/peɪs əv laɪf/', definition: '生活节奏', example: 'I prefer the slow pace of life in my hometown.', emoji: '⏳' },
                { word: 'dynamic', level: 'advanced', phonetic: '/daɪˈnæmɪk/', definition: '充满活力的；充满变化的', example: 'It is a dynamic place with lots of young people and new businesses.', emoji: '⚡️' },
                { word: 'vibrant', level: 'advanced', phonetic: '/ˈvaɪbrənt/', definition: '充满活力的', example: 'The city center is vibrant, especially at night.', emoji: '🔥' },
                { word: 'overcrowded', level: 'advanced', phonetic: '/ˌoʊvərˈkraʊdɪd/', definition: '人满为患的', example: 'Some areas can get overcrowded during public holidays.', emoji: '👥' },
                { word: 'well-known', level: 'advanced', phonetic: '/ˌwelˈnoʊn/', definition: '知名的', example: 'My hometown is well-known for its street food.', emoji: '⭐️' },
                { word: 'backwater', level: 'advanced', phonetic: '/ˈbækˌwɔːtər/', definition: '偏僻落后的地方', example: 'Some people may call it a backwater, but I enjoy the peaceful lifestyle.', emoji: '🌾' },
                { word: 'metropolis', level: 'advanced', phonetic: '/məˈtrɑːpəlɪs/', definition: '大都市', example: 'My hometown has transformed into a bustling metropolis.', emoji: '🌃' },
                { word: 'metropolitan city', level: 'advanced', phonetic: '/ˌmetrəˈpɑːlɪtən ˈsɪti/', definition: '大都市', example: 'Living in a metropolitan city means more job opportunities but also more stress.', emoji: '🌆' },
                { word: 'capital city', level: 'advanced', phonetic: '/ˈkæpɪtl ˈsɪti/', definition: '首都', example: 'The capital city usually offers better education and medical services.', emoji: '🏛️' },
                { word: 'coastal city', level: 'advanced', phonetic: '/ˈkoʊstl ˈsɪti/', definition: '沿海城市', example: 'It is a coastal city, so seafood is fresh and the air feels humid.', emoji: '🌊' },
                { word: 'inland city', level: 'advanced', phonetic: '/ˈɪnlænd ˈsɪti/', definition: '内陆城市', example: 'It is an inland city, so we have to travel far to see the ocean.', emoji: '🗺️' },
                { word: 'industrial city', level: 'advanced', phonetic: '/ɪnˈdʌstriəl ˈsɪti/', definition: '工业城市', example: 'It used to be an industrial city with many factories.', emoji: '🏭' },
                { word: 'tourist city', level: 'advanced', phonetic: '/ˈtʊrɪst ˈsɪti/', definition: '旅游城市', example: 'It is a tourist city, so there are lots of hotels and souvenir shops.', emoji: '📸' },
                { word: 'agricultural city', level: 'advanced', phonetic: '/ˌæɡrɪˈkʌltʃərəl ˈsɪti/', definition: '农业城市', example: 'It is an agricultural city surrounded by farmland.', emoji: '🌾' },
                { word: 'air pollution', level: 'advanced', phonetic: '/er pəˈluːʃn/', definition: '空气污染', example: 'Air pollution can be a problem in winter when there is little wind.', emoji: '🌫️' },
                { word: 'basic infrastructure', level: 'advanced', phonetic: '/ˈbeɪsɪk ˈɪnfrəˌstrʌktʃər/', definition: '基础设施', example: 'The basic infrastructure has improved a lot, like roads and public transport.', emoji: '🛣️' },
                { word: 'cultural diversity', level: 'advanced', phonetic: '/ˈkʌltʃərəl daɪˈvɜːrsəti/', definition: '文化多样性', example: 'I love the cultural diversity because people from different places live there.', emoji: '🌍' },
                { word: 'entertainment place', level: 'advanced', phonetic: '/ˌentərˈteɪnmənt pleɪs/', definition: '娱乐场所', example: 'There are many entertainment places, like cinemas, cafés, and karaoke bars.', emoji: '🎭' },
                { word: 'historical site', level: 'advanced', phonetic: '/hɪˈstɔːrɪkl saɪt/', definition: '历史遗址；名胜古迹', example: 'There are several historical sites that attract tourists every year.', emoji: '🏛️' },
                { word: 'local snack', level: 'advanced', phonetic: '/ˈloʊkl snæk/', definition: '当地小吃', example: 'My favorite local snack is sold at a small night market.', emoji: '🥟' },
                { word: 'beef balls', level: 'basic', phonetic: '/biːf bɔːlz/', definition: '牛肉丸', example: 'Beef balls are one of the most popular street foods in my hometown.', emoji: '🍲' },
                { word: 'night life', level: 'advanced', phonetic: '/naɪt laɪf/', definition: '夜生活', example: 'The night life is lively on weekends, especially around the downtown area.', emoji: '🌙' },
                { word: 'life expense', level: 'advanced', phonetic: '/laɪf ɪkˈspens/', definition: '生活开销', example: 'The life expense is much lower than in first-tier cities.', emoji: '💰' },
                { word: 'population density', level: 'advanced', phonetic: '/ˌpɑːpjəˈleɪʃn ˈdensəti/', definition: '人口密度', example: 'The population density is high in the city center.', emoji: '📊' },
                { word: 'public transportation', level: 'advanced', phonetic: '/ˈpʌblɪk ˌtrænspɔːrˈteɪʃn/', definition: '公共交通', example: 'Public transportation is convenient, so I rarely drive.', emoji: '🚌' },
                { word: 'seldom', level: 'basic', phonetic: '/ˈseldəm/', definition: '很少；不常', example: 'I seldom go downtown because it is always crowded.', emoji: '🕰️' },
                { word: 'shopping mall', level: 'advanced', phonetic: '/ˈʃɑːpɪŋ mɔːl/', definition: '购物中心', example: 'There is a huge shopping mall near my home.', emoji: '🛍️' },
                { word: 'sports facility', level: 'advanced', phonetic: '/spɔːrts fəˈsɪləti/', definition: '体育设施', example: 'The city has great sports facilities like stadiums and swimming pools.', emoji: '🏟️' },
                { word: 'tower block', level: 'advanced', phonetic: '/ˈtaʊər blɑːk/', definition: '高层住宅楼', example: 'Many people live in tower blocks in the new district.', emoji: '🏢' },
                { word: 'heavy traffic', level: 'advanced', phonetic: '/ˈhevi ˈtræfɪk/', definition: '交通繁忙', example: 'There is heavy traffic during morning and evening rush hours.', emoji: '🚦' },
                { word: 'bumper-to-bumper traffic', level: 'advanced', phonetic: '/ˌbʌmpər tə ˈbʌmpər ˈtræfɪk/', definition: '车挨车的交通拥堵', example: 'At rush hour, it is bumper-to-bumper traffic on the main road.', emoji: '🚗' },
                { word: 'traffic congestion', level: 'advanced', phonetic: '/ˈtræfɪk kənˈdʒestʃən/', definition: '交通拥堵', example: 'Traffic congestion is getting worse year by year.', emoji: '🚧' },
                { word: 'traffic jam', level: 'advanced', phonetic: '/ˈtræfɪk dʒæm/', definition: '交通堵塞', example: 'I got stuck in a traffic jam on my way to the office.', emoji: '🚙' },
                { word: 'be famous for', level: 'advanced', phonetic: '/bi ˈfeɪməs fɔːr/', definition: '以…闻名', example: 'My hometown is famous for its spicy noodles.', emoji: '🏆' },
                { word: 'be noted for', level: 'advanced', phonetic: '/bi ˈnoʊtɪd fɔːr/', definition: '因…著称', example: 'The area is noted for its beautiful natural scenery.', emoji: '📝' },
                { word: 'be located in', level: 'advanced', phonetic: '/bi loʊˈkeɪtɪd ɪn/', definition: '位于', example: 'My hometown is located in the southeast of China.', emoji: '📍' },
                { word: 'be situated in', level: 'advanced', phonetic: '/bi ˈsɪtʃueɪtɪd ɪn/', definition: '坐落于', example: 'It is situated in a valley near a river.', emoji: '📌' },
                { word: 'local delicacy', level: 'advanced', phonetic: '/ˈloʊkl ˈdelɪkəsi/', definition: '当地美食', example: 'You must try the local delicacy when you visit.', emoji: '🍲' },
                { word: 'sentimental value', level: 'advanced', phonetic: '/ˌsentɪˈmentl ˈvæljuː/', definition: '情感价值', example: 'This old park has great sentimental value to me.', emoji: '💖' },
            ]
        }
    ]
};
