import { SubTopic, Word } from './data-types';

const words: Word[] = [
    {
        word: 'accessory',
        phonetic: '/əkˈsesəri/',
        definition: '配饰；附件',
        example: 'Jewellery is a common fashion accessory.',
        emoji: '🎀',
        level: 'basic',
    },
    {
        word: 'ornamentation',
        phonetic: '/ˌɔːrnəmenˈteɪʃn/',
        definition: '装饰；装饰物',
        example: 'The necklace has delicate ornamentation on it.',
        emoji: '✨',
        level: 'advanced',
    },
    {
        word: 'amber',
        phonetic: '/ˈæmbər/',
        definition: '琥珀',
        example: 'She wears an amber bracelet as a lucky charm.',
        emoji: '🟠',
        level: 'advanced',
    },
    {
        word: 'bracelet',
        phonetic: '/ˈbreɪslət/',
        definition: '手链',
        example: 'My mom gave me a bracelet for my birthday.',
        emoji: '📿',
        level: 'basic',
    },
    {
        word: 'clip',
        phonetic: '/klɪp/',
        definition: '夹子；夹扣（发夹/首饰扣）',
        example: 'This earring has a clip, so you don’t need pierced ears.',
        emoji: '📎',
        level: 'advanced',
    },
    {
        word: 'diamond',
        phonetic: '/ˈdaɪmənd/',
        definition: '钻石',
        example: 'A diamond ring is a classic choice.',
        emoji: '💎',
        level: 'basic',
    },
    {
        word: 'earring',
        phonetic: '/ˈɪrɪŋ/',
        definition: '耳环',
        example: 'She bought a pair of earrings online.',
        emoji: '👂',
        level: 'basic',
    },
    {
        word: 'emerald',
        phonetic: '/ˈemərəld/',
        definition: '祖母绿',
        example: 'The emerald looks stunning under the light.',
        emoji: '💚',
        level: 'advanced',
    },
    {
        word: 'gold',
        phonetic: '/ɡoʊld/',
        definition: '黄金',
        example: 'Gold jewellery is popular in my country.',
        emoji: '🪙',
        level: 'basic',
    },
    {
        word: 'heart',
        phonetic: '/hɑːrt/',
        definition: '心形（图案/形状）',
        example: 'I like the heart-shaped pendant because it looks cute.',
        emoji: '❤️',
        level: 'basic',
    },
    {
        word: 'octagon',
        phonetic: '/ˈɑːktəɡɑːn/',
        definition: '八边形',
        example: 'The pendant is an octagon with a stone in the middle.',
        emoji: '🛑',
        level: 'advanced',
    },
    {
        word: 'oval',
        phonetic: '/ˈoʊvl/',
        definition: '椭圆形',
        example: 'An oval gemstone can make fingers look longer.',
        emoji: '🥚',
        level: 'basic',
    },
    {
        word: 'semicircle',
        phonetic: '/ˈsemiˌsɜːrkl/',
        definition: '半圆形',
        example: 'Her earrings are in a simple semicircle shape.',
        emoji: '🌗',
        level: 'advanced',
    },
    {
        word: 'square',
        phonetic: '/skwer/',
        definition: '正方形',
        example: 'I prefer square earrings because they look modern.',
        emoji: '🟦',
        level: 'basic',
    },
    {
        word: 'triangle',
        phonetic: '/ˈtraɪæŋɡl/',
        definition: '三角形',
        example: 'Triangle earrings are quite eye-catching.',
        emoji: '🔺',
        level: 'basic',
    },
    {
        word: 'rectangle',
        phonetic: '/ˈrektæŋɡl/',
        definition: '长方形',
        example: 'A rectangle watch face looks clean and elegant.',
        emoji: '📏',
        level: 'basic',
    },
    {
        word: 'heirloom',
        phonetic: '/ˈerluːm/',
        definition: '传家宝',
        example: 'This ring is a family heirloom passed down from my grandma.',
        emoji: '🏺',
        level: 'advanced',
    },
    {
        word: 'jade',
        phonetic: '/dʒeɪd/',
        definition: '玉；翡翠',
        example: 'Many older people like jade bracelets.',
        emoji: '🧿',
        level: 'advanced',
    },
    {
        word: 'necklace',
        phonetic: '/ˈnekləs/',
        definition: '项链',
        example: 'I often wear a simple necklace with a small pendant.',
        emoji: '📿',
        level: 'basic',
    },
    {
        word: 'pearl',
        phonetic: '/pɜːrl/',
        definition: '珍珠',
        example: 'Pearl earrings look elegant and timeless.',
        emoji: '⚪',
        level: 'advanced',
    },
    {
        word: 'platinum',
        phonetic: '/ˈplætɪnəm/',
        definition: '铂金',
        example: 'Platinum is more expensive than gold in many cases.',
        emoji: '🩶',
        level: 'advanced',
    },
    {
        word: 'quartz',
        phonetic: '/kwɔːrts/',
        definition: '石英',
        example: 'Quartz is widely used in jewellery and watches.',
        emoji: '🔮',
        level: 'advanced',
    },
    {
        word: 'ring',
        phonetic: '/rɪŋ/',
        definition: '戒指',
        example: 'I only wear a ring on special occasions.',
        emoji: '💍',
        level: 'basic',
    },
    {
        word: 'ruby',
        phonetic: '/ˈruːbi/',
        definition: '红宝石',
        example: 'A ruby necklace can look luxurious.',
        emoji: '❤️',
        level: 'advanced',
    },
    {
        word: 'watch',
        phonetic: '/wɑːtʃ/',
        definition: '手表',
        example: 'My watch is a simple one, but it looks sophisticated.',
        emoji: '⌚',
        level: 'basic',
    },
    {
        word: 'coral',
        phonetic: '/ˈkɔːrəl/',
        definition: '珊瑚（首饰材质）',
        example: 'She has a coral bracelet in a warm pink colour.',
        emoji: '🪸',
        level: 'advanced',
    },
    {
        word: 'costly',
        phonetic: '/ˈkɔːstli/',
        definition: '昂贵的',
        example: 'Some jewellery is too costly for students.',
        emoji: '💰',
        level: 'basic',
    },
    {
        word: 'sophisticated',
        phonetic: '/səˈfɪstɪkeɪtɪd/',
        definition: '精致的；高级的',
        example: 'She has a sophisticated taste in jewellery.',
        emoji: '🕴️',
        level: 'advanced',
    },
    {
        word: 'eye-catching',
        phonetic: '/ˈaɪ ˌkætʃɪŋ/',
        definition: '引人注目的',
        example: 'The earrings are eye-catching but not too flashy.',
        emoji: '👀',
        level: 'basic',
    },
    {
        word: 'luxurious',
        phonetic: '/lʌɡˈʒʊriəs/',
        definition: '奢华的',
        example: 'The brand is famous for its luxurious jewellery.',
        emoji: '🛍️',
        level: 'advanced',
    },
    {
        word: 'round',
        phonetic: '/raʊnd/',
        definition: '圆形的',
        example: 'Round earrings suit most face shapes.',
        emoji: '⚪',
        level: 'basic',
    },
    {
        word: 'a piece of jewellery',
        phonetic: '/ə piːs əv ˈdʒuːəlri/',
        definition: '一件首饰',
        example: 'I rarely buy a piece of jewellery for myself.',
        emoji: '💍',
        level: 'basic',
    },
    {
        word: 'artificial stone',
        phonetic: '/ˌɑːrtɪˈfɪʃl stoʊn/',
        definition: '人造宝石',
        example: 'Artificial stones can look like real gems but are cheaper.',
        emoji: '🧪',
        level: 'advanced',
    },
    {
        word: 'rock crystal',
        phonetic: '/rɑːk ˈkrɪstl/',
        definition: '水晶（天然石英）',
        example: 'Rock crystal is often used in pendants.',
        emoji: '🔮',
        level: 'advanced',
    },
];

export const jewellery: SubTopic = {
    id: 'jewellery',
    title: 'Jewellery 首饰',
    type: '事物题',
    color: 'purple',
    words,
};

