import { SubTopic } from './data-types';
import { getManyFromPool } from './pool/utils';

export const p2Objects: SubTopic = {
    id: 'p2-objects',
    title: 'Objects 物品类',
    type: '四大题型',
    color: 'purple',
    section: 'Part 2 & 3',
    wordSections: [
        {
            title: 'List 26 · 家具与家居 (Home & Furniture)',
            words: getManyFromPool([
                'bed',
                'bookshelf',
                'cabinet',
                'chair',
                'couch',
                'desk',
                'dresser',
                'furniture',
                'lamp',
                'rug',
                'table',
                'sofa',
                'wardrobe',
            ], 'basic'),
        },
        {
            title: 'List 26 · 服装与配饰 (Clothing & Accessories)',
            words: getManyFromPool([
                'clothing',
                'coat',
                'dress',
                'shirt',
                'T-shirt',
                'skirt',
                'glove',
                'hat',
                'hoodie',
                'jacket',
                'jeans',
                'pants',
                'trousers',
                'sock',
                'sneaker',
                'suit',
                'sweater',
                'tie',
                'scarf',
            ], 'basic'),
        },
        {
            title: 'List 26 · 厨房与电器 (Kitchen & Appliances)',
            words: getManyFromPool([
                'cooker',
                'dryer',
                'fridge',
                'refrigerator',
                'kettle',
                'microwave',
                'iron',
                'toaster',
                'air conditioner',
                'electric fan',
                'electric razor',
                'hair dryer',
                'vacuum cleaner',
                'washing machine',
                'electrical appliance',
            ], 'basic'),
        },
        {
            title: 'List 26 · 文具与工具 (Stationery & Tools)',
            words: getManyFromPool([
                'eraser',
                'glue',
                'highlighter',
                'marker',
                'notebook',
                'pen',
                'pencil',
                'ruler',
                'scissors',
                'stapler',
                'stationery',
                'tape',
                'sticky note',
            ], 'basic'),
        },
        {
            title: 'List 26 · 科技与设备 (Tech & Devices)',
            words: getManyFromPool([
                'camera',
                'drone',
                'e-reader',
                'headphones',
                'laptop',
                'smartphone',
                'smartwatch',
                'tablet',
                'television',
                'TV',
                'games console',
                'fitness tracker',
                'portable charger',
                'smart home device',
                'voice assistant',
                'virtual reality headset',
                'Augmented Reality glasses',
            ], 'basic'),
        },
        {
            title: 'List 26 · 材料与其他 (Materials & Others)',
            words: [
                ...getManyFromPool([
                    'copper',
                    'cotton',
                    'marble',
                    'metal',
                    'plastic',
                    'silver',
                    'wood',
                    'wool',
                    'hamburger',
                    'juice',
                    'invention',
                ], 'basic'),
                ...getManyFromPool([
                    'renewable energy',
                    'solar energy',
                    'wind energy',
                    'handicraft work',
                ], 'basic'),
                ...getManyFromPool([
                    'fossil fuel',
                    'cultural relic',
                    'eye-opener',
                    'law on heritage protection',
                ], 'advanced'),
            ],
        },
        {
            title: 'List 26 · 形容与表达 (Adjectives & Expressions)',
            words: [
                ...getManyFromPool([
                    'advanced',
                    'convenient',
                    'cost-effective',
                    'efficient',
                    'high-tech',
                    'huge',
                    'informative',
                    'practical',
                    'tiny',
                    'trendy',
                ], 'basic'),
                ...getManyFromPool([
                    'compact',
                    'delicate',
                    'durable',
                    'enormous',
                    'innovative',
                    'life-size',
                    'portable',
                    'user-friendly',
                    'cutting edge',
                ], 'advanced'),
            ],
        },
    ],
};
