import { SubTopic } from './data-types';
import { getManyFromPool } from './pool/utils';

export const p2Places: SubTopic = {
    id: 'p2-places',
    title: 'Places 地点类',
    type: '四大题型',
    color: 'green',
    section: 'Part 2 & 3',
    wordSections: [
        {
            title: '1. 场所与建筑 (Places & Venues)',
            words: [
                ...getManyFromPool([
                    'airport',
                    'ambulance',
                    'apartment',
                    'bakery',
                    'bookshop',
                    'cafe',
                    'capital',
                    'cinema',
                    'countryside',
                    'district',
                    'downtown',
                    'gym',
                    'library',
                    'museum',
                    'restaurant',
                    'seaside',
                    'suburb',
                    'supermarket',
                    'village',
                    'amusement park',
                    'art gallery',
                    'coffee shop',
                    'department store',
                    'shopping centre',
                    'snack bar',
                    'souvenir shop',
                    'sports stadium',
                    'theme park',
                    'residential area',
                    'scenic spot',
                    'places of interest',
                    'tourist attraction',
                    'train station',
                ], 'basic'),
                ...getManyFromPool([
                    'amenity',
                    'boutique',
                    'florist',
                    'guidebook',
                    'landmark',
                    'layout',
                    'outskirts',
                    'skyscraper',
                    'villa',
                    'artistic district',
                    'bustling night market',
                    'chain store',
                    'commercial centre',
                    'concert hall',
                    'concrete jungle',
                    'cosmetic shop',
                    'food court',
                    'high-rise building',
                    'karaoke bar',
                    'lush forest',
                    'multi-storey block',
                    'opera house',
                    'tourism bureau',
                    'travel agency',
                    'UNESCO Heritage Site',
                ], 'advanced'),
            ],
        },
        {
            title: '2. 描述与氛围 (Descriptions)',
            words: [
                ...getManyFromPool([
                    'atmosphere',
                    'clean',
                    'crowded',
                    'narrow',
                    'remote',
                    'run-down',
                    'spacious',
                    'tidy',
                    'urban',
                ], 'basic'),
                ...getManyFromPool([
                    'bumper-to-bumper',
                    'bustling',
                    'classy',
                    'cosmopolitan',
                    'cramped',
                    'deluxe',
                    'densely-populated',
                    'exquisite',
                    'first-rate',
                    'furnished',
                    'high-end',
                    'magnificent',
                    'metropolitan',
                    'organised',
                    'ornate',
                    'packed',
                    'picturesque',
                    'prosperous',
                    'shabby',
                    'soothing',
                    'spectacular',
                    'splendid',
                    'superb',
                    'thriving',
                    'top-notch',
                    'upscale',
                    'well-preserved',
                    'well-ventilated',
                    'light and airy',
                    'lush and green',
                    'crystal clear water',
                    'breathtaking scenery',
                    'breathtaking view',
                    'spectacular view',
                    'stunning view',
                    'hustle and bustle',
                    'dynamic and vibrant',
                    'tranquil and serene',
                    'vibrant atmosphere',
                ], 'advanced'),
            ],
        },
        {
            title: '3. 城市发展与文化 (Ideas & Collocations)',
            words: [
                ...getManyFromPool([
                    'hang out with',
                    'get close to the nature',
                ], 'basic'),
                ...getManyFromPool([
                    'civilization',
                    'infrastructure',
                    'dweller',
                    'damage',
                    'demolish',
                    'flourish',
                    'invigorate',
                    'propagate',
                    'cultural exchange',
                    'culture diversity',
                    'density of population',
                    'developed city',
                    'employment opportunity',
                    'historic architecture',
                    'historic site',
                    'housing price',
                    'interior design',
                    'publicize culture',
                ], 'advanced'),
            ],
        },
    ],
};
