import { SubTopic } from './data-types';
import { getManyFromPool } from './pool/utils';

export const p2People: SubTopic = {
    id: 'p2-people',
    title: 'People 人物类',
    type: '四大题型',
    color: 'yellow',
    section: 'Part 2 & 3',
    wordSections: [
        {
            title: '1. 外貌与外表 (Appearance)',
            words: [
                ...getManyFromPool([
                    'beard',
                    'bald',
                    'eyelash',
                    'overweight',
                    'slim',
                    'curly hair',
                    'straight hair',
                    'gray hair',
                    'thick eyebrows',
                    'thin lips',
                    'thin waist',
                    'delicate makeup',
                    'double chin',
                    'double eyelid',
                    'full lip',
                    'long eyelashes',
                    'rosy cheek',
                    'slight figure',
                    'smartly dressed',
                    'well-built',
                    'well-defined',
                    'youthful look',
                ], 'basic'),
                ...getManyFromPool([
                    'photogenic',
                    'beer belly',
                    'buck teeth',
                    'striking feature',
                    'dimple',
                    'fringe',
                    'mole',
                    'pigtail',
                    'wrinkle',
                    'plump',
                    'oval face',
                    'square face',
                    'scruffy',
                ], 'advanced'),
            ],
        },
        {
            title: '2. 身份与名气 (Identity & Fame)',
            words: [
                ...getManyFromPool([
                    'popular',
                    'retired',
                    'celebrity',
                    'fame',
                    'idol',
                    'reputation',
                    'leadership',
                ], 'basic'),
                ...getManyFromPool([
                    'public figure',
                    'person of the year',
                    'world-renowned',
                    'entrepreneur',
                    'glamour',
                    'recruit',
                    'prestigious',
                    'prodigy',
                ], 'advanced'),
            ],
        },
        {
            title: '3. 性格与品质 (Personality & Qualities)',
            words: [
                ...getManyFromPool([
                    'character',
                    'personality',
                    'determination',
                    'talent',
                    'good taste',
                    'depression',
                    'selflessness',
                ], 'basic'),
                ...getManyFromPool([
                    'personality highlight',
                    'social anxiety disorder',
                ], 'advanced'),
            ],
        },
        {
            title: '4. 行为与互动 (Actions)',
            words: [
                ...getManyFromPool([
                    'admire',
                    'look up to',
                    'rely on',
                ], 'basic'),
                ...getManyFromPool([
                    "break one's limit",
                    'console',
                    'alienate',
                    'drift apart',
                    'hit it off',
                ], 'advanced'),
            ],
        },
        {
            title: '5. 性格形容词 (Adjectives)',
            words: [
                ...getManyFromPool([
                    'friendly',
                    'sociable',
                    'introvert',
                    'extrovert',
                    'easy-going',
                    'talkative',
                    'chatty',
                    'straightforward',
                    'frank',
                    'considerate',
                    'generous',
                    'gentle',
                    'humorous',
                    'honest',
                    'sincere',
                    'reliable',
                    'trustworthy',
                    'loyal',
                    'modest',
                    'confident',
                    'independent',
                    'open-minded',
                    'optimistic',
                    'active',
                    'energetic',
                    'enthusiastic',
                    'passionate',
                    'creative',
                    'curious',
                    'adventurous',
                    'original',
                    'fashionable',
                    'pleasant',
                    'hard-working',
                    'careful',
                    'neat',
                    'punctual',
                    'cheerful',
                    'intelligent',
                    'smart',
                    'able',
                    'capable',
                    'sensible',
                    'tough',
                    'innocent',
                    'critical',
                    'mean',
                    'selfish',
                    'dishonest',
                    'naive',
                    'naughty',
                    'inspired',
                    'shocked',
                ], 'basic'),
                ...getManyFromPool([
                    'absent-minded',
                    'adroit',
                    'adaptable',
                    'ambitious',
                    'diligent',
                    'industrious',
                    'persevering',
                    'purposeful',
                    'strong-willed',
                    'self-disciplined',
                    'self-reliant',
                    'self-made',
                    'self-sustaining',
                    'well-educated',
                    'well-rounded',
                    'versatile',
                    'worldly-wise',
                    'analytical',
                    'rational',
                    'intellectual',
                    'inquisitive',
                    'quick-witted',
                    'cogent',
                    'alert',
                    'imaginative',
                    'expressive',
                    'candid',
                    'diplomatic',
                    'discreet',
                    'amiable',
                    'affectionate',
                    'adorable',
                    'hospitable',
                    'hearty',
                    'harmonious',
                    'genuine',
                    'faithful',
                    'charitable',
                    'tender',
                    'good-tempered',
                    'happy-go-lucky',
                    'carefree',
                    'impulsive',
                    'hot-tempered',
                    'apprehensive',
                    'obedient',
                    'dependable',
                    'inconsiderate',
                    'narrow-minded',
                    'self-centred',
                    'spoilt',
                    'notorious',
                    'sequacious',
                    'sloppy',
                    'stylish',
                    'trendsetting',
                    'camera-shy',
                    'fair-skinned',
                    'faint-hearted',
                    'forceful',
                    'frugal',
                    'dowdy',
                    'eccentric',
                    'eloquent',
                    'inventive',
                    'isolated',
                    'intimate',
                    'aspirant',
                    'aspiring',
                    'impressed',
                ], 'advanced'),
            ],
        },
        {
            title: '6. 人际与关系 (Relationships)',
            words: [
                ...getManyFromPool([
                    'emotional support',
                    'supportive family',
                    'interpersonal relationship',
                    'common interest',
                    'people from all walks of life',
                ], 'basic'),
                ...getManyFromPool([
                    'joy and sorrow',
                    'bosom friend',
                    'close-knit community',
                    'kindred spirit',
                    'party pooper',
                ], 'advanced'),
            ],
        },
        {
            title: '7. 生活节奏与技能 (Life & Skills)',
            words: [
                ...getManyFromPool([
                    'comfort zone',
                    'communication skill',
                    'critical thinking',
                    'time management',
                    'under pressure',
                    'cost of living',
                    'standard of living',
                    'pace of life',
                    'family-owned company',
                    'ups and downs',
                ], 'basic'),
                ...getManyFromPool([
                    'promising future',
                    'social status',
                    'work-life balance',
                    'to some extent',
                    'tight schedule',
                ], 'advanced'),
            ],
        },
    ],
};
