import { SubTopic } from './data-types';
import { getManyFromPool } from './pool/utils';

export const p2Events: SubTopic = {
    id: 'p2-events',
    title: 'Events 事件类',
    type: '四大题型',
    color: 'blue',
    section: 'Part 2 & 3',
    wordSections: [
        {
            title: '1. 聚会与庆祝 (Gatherings & Celebrations)',
            words: getManyFromPool([
                'assembly',
                'rally',
                'gathering',
                'reunion',
                'occasion',
                'party',
                'get together',
                'social gathering',
                'house party',
                'housewarming party',
                'no-host party',
                'theme party',
                'stag party',
                'throw a party',
                'party animal',
                'potluck',
                'baby shower',
                'birthday party',
                'celebrate',
            ], 'basic'),
        },
        {
            title: '2. 学业与人生节点 (Education & Milestones)',
            words: getManyFromPool([
                'degree',
                'diploma',
                'graduate',
                'milestone',
            ], 'basic'),
        },
        {
            title: '3. 旅行与旅游 (Travel & Tourism)',
            words: [
                ...getManyFromPool([
                    'travel',
                    'sightseeing',
                    'tourist',
                    'tourist spot',
                    'tourist destination country',
                    'domestic tourism',
                    'outbound tourism',
                    'independent travel',
                    'package tour',
                    'self-driving tour',
                    'self-guided tour',
                    'peak travel time',
                    'rush hour',
                    'travelling expense',
                    'natural landscape',
                    'guide',
                    'souvenir',
                    'specialty',
                    'cultural relic',
                ], 'basic'),
                ...getManyFromPool(['overwhelming'], 'advanced'),
            ],
        },
        {
            title: '4. 住宿与房型 (Accommodation & Room Types)',
            words: [
                ...getManyFromPool([
                    'hostel',
                    'hotel',
                    'inn',
                    'lodge',
                    'motel (=motor hotel)',
                    'budget hotel',
                    'economy hotel (one-star hotel)',
                    'some comfort hotel (two-star hotel)',
                    'average hotel (three-star hotel)',
                    'high comfort hotel (four-star hotel)',
                    'deluxe hotel (five-star hotel)',
                    'big single room',
                    'single room',
                    'double room',
                    'twin room',
                    'triple room',
                    'economy room (ER)',
                    'standard room (SR)',
                    'superior room (UR)',
                    'deluxe room (DR)',
                    'standard suite (SS)',
                    'presidential suite (PS)',
                ], 'basic'),
                ...getManyFromPool(['caravansary', 'tavern'], 'advanced'),
            ],
        },
        {
            title: '5. 描述与表达 (Descriptions & Expressions)',
            words: [
                ...getManyFromPool([
                    'memorable',
                    'move',
                    'recall',
                    'kill the time',
                    'leisure activity',
                    'physical activity',
                ], 'basic'),
                ...getManyFromPool([
                    'novel',
                    'insomnia',
                    'drain',
                ], 'advanced'),
            ],
        },
        {
            title: '6. 行政机构 (Tourism Administration)',
            words: getManyFromPool([
                'Tourist Administration',
                'Autonomous Prefecture Tourism Administration',
                'Autonomous Region Tourism Administration',
                'County Tourism Administration',
                'Municipal Tourism Administration',
                'Provincial Tourism Administration',
                'tourist organization',
                'World Tourism Day',
                'World Tourism Organization',
            ], 'advanced'),
        },
        {
            title: '7. 旅游业与职业 (Tourism Industry & Careers)',
            words: getManyFromPool([
                'travel agent',
                'travel business',
                'travel expert',
                'travel industry',
                'travel journalist',
            ], 'advanced'),
        },
    ],
};
