
import { SubTopic } from './data-types';

export const highFreqGeneral: SubTopic = {
    id: 'hf-general',
    title: '万能高频动词',
    type: '高频词',
    color: 'purple',
    section: 'High Frequency',
    words: [
        { word: 'acquire', phonetic: '/əˈkwaɪər/', definition: '获得', example: 'It is a good way to acquire new knowledge.', emoji: '📥' },
        { word: 'essential', phonetic: '/ɪˈsenʃl/', definition: '必不可少的', example: 'Practice is essential for success.', emoji: '✨' },
    ]
};

export const highFreqExpressingLikes: SubTopic = {
    id: 'hf-expressing-likes',
    title: '表示喜欢 (Expressing Likes)',
    type: '高频词',
    color: 'green',
    section: 'High Frequency',
    words: [
        { word: '... is my cup of tea', level: 'advanced', phonetic: '', definition: '……是我的菜/我很喜欢……', example: 'Classical music is my cup of tea.', emoji: '☕️' },
        { word: 'I adore ...', level: 'advanced', phonetic: '', definition: '我非常喜欢……', example: 'I adore animals, especially cats.', emoji: '😍' },
        { word: 'I generally prefer ... to ...', level: 'basic', phonetic: '', definition: '一般来说，我更喜欢……而不是……', example: 'I generally prefer tea to coffee.', emoji: '↔️' },
        { word: 'I have a particular fondness for ...', level: 'advanced', phonetic: '', definition: '我对……情有独钟', example: 'I have a particular fondness for street food.', emoji: '💛' },
        { word: 'I like ...', level: 'basic', phonetic: '', definition: '我喜欢……', example: 'I like doing some exercise after work.', emoji: '👍' },
        { word: 'I simply adore ...', level: 'advanced', phonetic: '', definition: '我真的特别喜欢……', example: 'I simply adore rainy days when I can stay at home.', emoji: '🥰' },
        { word: 'I\'m fairly keen on ...', level: 'advanced', phonetic: '', definition: '我挺喜欢/挺热衷于……', example: 'I\'m fairly keen on photography.', emoji: '📷' },
        { word: 'I\'m fascinated by ...', level: 'advanced', phonetic: '', definition: '我对……很着迷/很好奇', example: 'I\'m fascinated by how AI works.', emoji: '🧠' },
        { word: 'I\'m obsessed with ...', level: 'advanced', phonetic: '', definition: '我对……很上头/痴迷……', example: 'I\'m obsessed with this TV series.', emoji: '🎬' },
        { word: 'I\'m pretty fond of ...', level: 'advanced', phonetic: '', definition: '我挺喜欢……', example: 'I\'m pretty fond of spicy food.', emoji: '🌶️' },
        { word: 'I\'m quite a big fan of ...', level: 'advanced', phonetic: '', definition: '我非常喜欢……/是……的忠实粉丝', example: 'I\'m quite a big fan of basketball.', emoji: '🏀' },
        { word: 'I\'m quite enthusiastic/passionate about ...', level: 'advanced', phonetic: '', definition: '我对……很有热情/很热衷于……', example: 'I\'m quite enthusiastic about learning languages.', emoji: '🔥' },
        { word: 'I\'m really into ...', level: 'basic', phonetic: '', definition: '我真的很喜欢/很沉迷于……', example: 'I\'m really into indie music these days.', emoji: '🎧' },
        { word: 'I\'m totally mad about ...', level: 'advanced', phonetic: '', definition: '我超级喜欢……/对……狂热', example: 'I\'m totally mad about hiking.', emoji: '⛰️' },
        { word: 'I\'m enthusiastic about ...', level: 'basic', phonetic: '', definition: '我对……很有热情', example: 'I\'m enthusiastic about volunteering.', emoji: '🙌' },
        { word: 'I\'m interested in ...', level: 'basic', phonetic: '', definition: '我对……感兴趣', example: 'I\'m interested in architecture.', emoji: '🏛️' },
        { word: 'I\'m passionate about ...', level: 'advanced', phonetic: '', definition: '我对……充满热情', example: 'I\'m passionate about helping others.', emoji: '❤️' },
        { word: 'It appeals to me.', level: 'advanced', phonetic: '', definition: '它很吸引我/我很喜欢它', example: 'Working from home really appeals to me.', emoji: '✨' },
    ],
};

export const highFreqExpressingDislikes: SubTopic = {
    id: 'hf-expressing-dislikes',
    title: '表示不喜欢 (Expressing Dislikes)',
    type: '高频词',
    color: 'blue',
    section: 'High Frequency',
    words: [
        { word: '... is not my cup of tea', level: 'advanced', phonetic: '', definition: '……不是我的菜/我不太喜欢……', example: 'Horror movies are not my cup of tea.', emoji: '☕️' },
        { word: '... is not my thing', level: 'advanced', phonetic: '', definition: '……不是我喜欢的东西/不合我口味', example: 'Clubbing is not my thing.', emoji: '🙅' },
        { word: 'I detest ...', level: 'advanced', phonetic: '', definition: '我非常讨厌……', example: 'I detest wasting time in traffic.', emoji: '😖' },
        { word: 'I dislike ...', level: 'basic', phonetic: '', definition: '我不喜欢……', example: 'I dislike getting up early.', emoji: '👎' },
        { word: 'I despise ...', level: 'advanced', phonetic: '', definition: '我鄙视/厌恶……', example: 'I despise people who lie all the time.', emoji: '😤' },
        { word: 'I don\'t care for ...', level: 'advanced', phonetic: '', definition: '我不太喜欢……', example: 'I don\'t care for very sweet desserts.', emoji: '🍰' },
        { word: 'I don\'t think much of ...', level: 'advanced', phonetic: '', definition: '我对……评价不高/不怎么喜欢……', example: 'I don\'t think much of online gossip.', emoji: '🤷' },
        { word: 'I hate ...', level: 'basic', phonetic: '', definition: '我讨厌……', example: 'I hate being late.', emoji: '⏰' },
        { word: 'I loathe ...', level: 'advanced', phonetic: '', definition: '我非常厌恶……', example: 'I loathe people talking loudly on the phone.', emoji: '😣' },
        { word: 'I really can\'t stand ...', level: 'advanced', phonetic: '', definition: '我真的受不了……', example: 'I really can\'t stand noisy neighbors.', emoji: '🤯' },
        { word: 'I\'m not interested in ...', level: 'basic', phonetic: '', definition: '我对……不感兴趣', example: 'I\'m not interested in celebrity news.', emoji: '📰' },
        { word: 'I\'m not into it.', level: 'basic', phonetic: '', definition: '我不喜欢/我不太感兴趣', example: 'I tried it once, but I\'m not into it.', emoji: '🚫' },
        { word: 'I\'m tired of ...', level: 'basic', phonetic: '', definition: '我厌倦了……', example: 'I\'m tired of eating fast food every day.', emoji: '🥱' },
        { word: 'I\'m not much of a fan of ...', level: 'advanced', phonetic: '', definition: '我不太喜欢……', example: 'I\'m not much of a fan of extreme sports.', emoji: '⛔️' },
        { word: 'I\'m not so keen on ...', level: 'advanced', phonetic: '', definition: '我不太喜欢……', example: 'I\'m not so keen on crowded places.', emoji: '🚶‍➡️' },
        { word: 'I\'m really not that fond of ...', level: 'advanced', phonetic: '', definition: '我真的不怎么喜欢……', example: 'I\'m really not that fond of bitter coffee.', emoji: '🙃' },
    ],
};

export const highFreqExpressingMaybeProbability: SubTopic = {
    id: 'hf-expressing-maybe-probability',
    title: '表示也许 (Expressing Maybe/Probability)',
    type: '高频词',
    color: 'yellow',
    section: 'High Frequency',
    words: [
        { word: 'may', level: 'basic', phonetic: '/meɪ/', definition: '也许/可能（情态动词）', example: 'I may go for a walk later.', emoji: '🤔' },
        { word: 'might', level: 'basic', phonetic: '/maɪt/', definition: '可能/也许（比 may 更不确定）', example: 'I might stay in and watch a movie tonight.', emoji: '🎲' },
        { word: 'likely', level: 'basic', phonetic: '/ˈlaɪkli/', definition: '可能的；很可能', example: 'It\'s likely that I\'ll take the subway.', emoji: '📈' },
        { word: 'perhaps', level: 'advanced', phonetic: '/pərˈhæps/', definition: '也许；可能', example: 'Perhaps I\'ll travel abroad after graduation.', emoji: '🤔' },
        { word: 'possibly', level: 'advanced', phonetic: '/ˈpɑːsəbli/', definition: '可能地；也许', example: 'We could possibly meet this weekend.', emoji: '🧩' },
        { word: 'probably', level: 'basic', phonetic: '/ˈprɑːbəbli/', definition: '很可能；大概', example: 'I\'ll probably have a quick lunch.', emoji: '✅' },
        { word: 'A common situation is ...', level: 'advanced', phonetic: '', definition: '常见的情况是……', example: 'A common situation is that people check their phones first thing in the morning.', emoji: '🧠' },
        { word: 'In some cases, ...', level: 'advanced', phonetic: '', definition: '在某些情况下，……', example: 'In some cases, it\'s better to keep things simple.', emoji: '🧩' },
        { word: 'In some situations, ...', level: 'advanced', phonetic: '', definition: '在一些情境下，……', example: 'In some situations, I prefer to stay quiet and listen.', emoji: '🎭' },
    ],
};

export const highFreqExpressingHappiness: SubTopic = {
    id: 'hf-expressing-happiness',
    title: '表示开心 (Expressing Happiness)',
    type: '高频词',
    color: 'green',
    section: 'High Frequency',
    words: [
        { word: 'rejoice', level: 'advanced', phonetic: '/rɪˈdʒɔɪs/', definition: '欢欣；欣喜', example: 'We rejoiced at the good news.', emoji: '🎉' },
        { word: 'amused', level: 'basic', phonetic: '/əˈmjuːzd/', definition: '被逗乐的', example: 'I was amused by his jokes.', emoji: '😄' },
        { word: 'cheerful', level: 'basic', phonetic: '/ˈtʃɪrfl/', definition: '愉快的；兴高采烈的', example: 'She\'s always cheerful in the morning.', emoji: '😊' },
        { word: 'content', level: 'advanced', phonetic: '/kənˈtent/', definition: '满足的；知足的', example: 'I feel content with my life right now.', emoji: '😌' },
        { word: 'delighted', level: 'basic', phonetic: '/dɪˈlaɪtɪd/', definition: '高兴的；欣喜的', example: 'I was delighted to hear that I passed.', emoji: '😁' },
        { word: 'happy', level: 'basic', phonetic: '/ˈhæpi/', definition: '开心的', example: 'I\'m happy with my decision.', emoji: '🙂' },
        { word: 'joyful', level: 'advanced', phonetic: '/ˈdʒɔɪfl/', definition: '充满喜悦的', example: 'The festival was joyful.', emoji: '🥳' },
        { word: 'overjoyed', level: 'advanced', phonetic: '/ˌoʊvərˈdʒɔɪd/', definition: '欣喜若狂的', example: 'My parents were overjoyed when I got the offer.', emoji: '🤩' },
        { word: 'pleased', level: 'basic', phonetic: '/pliːzd/', definition: '满意的；高兴的', example: 'I\'m pleased with the result.', emoji: '👍' },
        { word: 'thrilled', level: 'advanced', phonetic: '/θrɪld/', definition: '激动的；兴奋的', example: 'I was thrilled to meet my favorite singer.', emoji: '🎊' },
        { word: 'like a dog with two tails', level: 'advanced', phonetic: '', definition: '高兴得不得了', example: 'I was like a dog with two tails when I got the ticket.', emoji: '🐶' },
        { word: 'brighten up the day', level: 'advanced', phonetic: '', definition: '让一天都变得更开心/更明亮', example: 'A short chat with a friend can brighten up my day.', emoji: '☀️' },
        { word: 'cheer sb. up', level: 'advanced', phonetic: '', definition: '让某人振作/开心起来', example: 'I tried to cheer my sister up after her exam.', emoji: '🎈' },
        { word: 'elevate one\'s mood', level: 'advanced', phonetic: '', definition: '提升情绪', example: 'Music can elevate my mood instantly.', emoji: '🎵' },
        { word: 'full of the joys of spring', level: 'advanced', phonetic: '', definition: '洋溢着欢乐/精神抖擞', example: 'She walked in, full of the joys of spring.', emoji: '🌸' },
        { word: 'happy camper', level: 'advanced', phonetic: '', definition: '很开心/很满意的人', example: 'After a good meal, I\'m a happy camper.', emoji: '🏕️' },
        { word: 'have a blast', level: 'basic', phonetic: '', definition: '玩得很嗨/玩得很开心', example: 'We had a blast at the party.', emoji: '🎆' },
        { word: 'in a good mood', level: 'basic', phonetic: '', definition: '心情很好', example: 'I\'m in a good mood because the weather is great.', emoji: '😄' },
        { word: 'in high spirits', level: 'advanced', phonetic: '', definition: '兴致很高', example: 'Everyone was in high spirits before the trip.', emoji: '🕺' },
        { word: 'in seventh heaven', level: 'advanced', phonetic: '', definition: '极其幸福/飘飘然', example: 'I was in seventh heaven when I got the scholarship.', emoji: '😇' },
        { word: 'increase the happiness', level: 'advanced', phonetic: '', definition: '提升幸福感/增加快乐', example: 'Doing exercise can increase the happiness in my life.', emoji: '📈' },
        { word: 'jump for joy', level: 'advanced', phonetic: '', definition: '高兴得跳起来', example: 'I jumped for joy when I heard the news.', emoji: '🤸' },
        { word: 'like the cat that got the cream', level: 'advanced', phonetic: '', definition: '得意洋洋/心满意足', example: 'He looked like the cat that got the cream after winning.', emoji: '🐱' },
        { word: 'on cloud nine', level: 'advanced', phonetic: '', definition: '欣喜若狂/飘飘然', example: 'I was on cloud nine after the interview.', emoji: '☁️' },
        { word: 'on top of the world', level: 'advanced', phonetic: '', definition: '感觉自己无比幸福/状态爆棚', example: 'After I finished the marathon, I felt on top of the world.', emoji: '🌍' },
        { word: 'over the moon', level: 'advanced', phonetic: '', definition: '高兴得不得了', example: 'My parents were over the moon about my results.', emoji: '🌙' },
        { word: 'walk on air', level: 'advanced', phonetic: '', definition: '走路带风/飘飘然', example: 'I was walking on air after receiving the gift.', emoji: '🪽' },
        { word: 'wild with joy', level: 'advanced', phonetic: '', definition: '欣喜若狂', example: 'The kids were wild with joy when school ended.', emoji: '🎈' },
    ],
};

export const highFreqExpressingSadness: SubTopic = {
    id: 'hf-expressing-sadness',
    title: '表示伤心 (Expressing Sadness)',
    type: '高频词',
    color: 'blue',
    section: 'High Frequency',
    words: [
        { word: 'deflate', level: 'advanced', phonetic: '/dɪˈfleɪt/', definition: '使泄气；使沮丧', example: 'I felt deflated after failing the test.', emoji: '🎈' },
        { word: 'grieve', level: 'advanced', phonetic: '/ɡriːv/', definition: '悲痛；哀悼', example: 'She grieved for her lost pet.', emoji: '🖤' },
        { word: 'broken-hearted', level: 'advanced', phonetic: '/ˌbroʊkənˈhɑːrtɪd/', definition: '心碎的', example: 'I was broken-hearted when it ended.', emoji: '💔' },
        { word: 'choked up', level: 'advanced', phonetic: '/tʃoʊkt ʌp/', definition: '哽咽的；说不出话的', example: 'I was choked up during the speech.', emoji: '😢' },
        { word: 'gloomy', level: 'basic', phonetic: '/ˈɡluːmi/', definition: '忧郁的；阴沉的', example: 'The room felt gloomy without sunlight.', emoji: '☁️' },
        { word: 'hurt', level: 'basic', phonetic: '/hɜːrt/', definition: '受伤的；难过的', example: 'It really hurt when he forgot my birthday.', emoji: '🥀' },
        { word: 'inconsolable', level: 'advanced', phonetic: '/ˌɪnkənˈsoʊləbl/', definition: '无法安慰的', example: 'She was inconsolable after the news.', emoji: '😭' },
        { word: 'melancholy', level: 'advanced', phonetic: '/ˈmelənkɑːli/', definition: '忧郁；伤感', example: 'There was a touch of melancholy in his voice.', emoji: '🌧️' },
        { word: 'miserable', level: 'basic', phonetic: '/ˈmɪzrəbl/', definition: '痛苦的；难受的', example: 'I felt miserable after the argument.', emoji: '😞' },
        { word: 'mournful', level: 'advanced', phonetic: '/ˈmɔːrnfl/', definition: '悲伤的', example: 'He gave me a mournful look.', emoji: '🕯️' },
        { word: 'sad', level: 'basic', phonetic: '/sæd/', definition: '伤心的', example: 'I felt sad when the holidays ended.', emoji: '😔' },
        { word: 'unhappy', level: 'basic', phonetic: '/ʌnˈhæpi/', definition: '不开心的', example: 'I was unhappy with the service.', emoji: '🙁' },
        { word: 'be down in the dumps', level: 'advanced', phonetic: '', definition: '情绪低落', example: 'I was down in the dumps after a long day.', emoji: '⬇️' },
        { word: 'cloud up', level: 'advanced', phonetic: '', definition: '（心情/表情）变得阴沉', example: 'His face clouded up when he heard the news.', emoji: '☁️' },
        { word: 'cry one\'s heart out', level: 'advanced', phonetic: '', definition: '痛哭一场', example: 'She cried her heart out after the breakup.', emoji: '😭' },
        { word: 'down in the mouth', level: 'advanced', phonetic: '', definition: '情绪低落/垂头丧气', example: 'He looked a bit down in the mouth.', emoji: '😟' },
        { word: 'feel blue', level: 'advanced', phonetic: '', definition: '感到忧郁', example: 'I feel blue on rainy days.', emoji: '💙' },
        { word: 'feel like crying', level: 'basic', phonetic: '', definition: '想哭', example: 'Sometimes I feel like crying for no reason.', emoji: '😢' },
        { word: 'get a face like a wet weekend', level: 'advanced', phonetic: '', definition: '脸色难看/一脸不高兴', example: 'He got a face like a wet weekend after losing.', emoji: '☔️' },
        { word: 'in a bad mood', level: 'basic', phonetic: '', definition: '心情不好', example: 'I\'m in a bad mood when I don\'t get enough sleep.', emoji: '😞' },
        { word: 'in low spirits', level: 'advanced', phonetic: '', definition: '情绪低落', example: 'She was in low spirits after the meeting.', emoji: '⬇️' },
        { word: 'lump in one\'s throat', level: 'advanced', phonetic: '', definition: '喉咙哽住/哽咽', example: 'I had a lump in my throat during the farewell.', emoji: '😢' },
        { word: 'one\'s heart sinks', level: 'advanced', phonetic: '', definition: '心一沉', example: 'My heart sank when I saw the score.', emoji: '⬇️' },
        { word: 'out of sorts', level: 'advanced', phonetic: '', definition: '状态不好/心情不佳', example: 'I\'ve been out of sorts lately.', emoji: '😕' },
        { word: 'with a heavy heart', level: 'advanced', phonetic: '', definition: '怀着沉重的心情', example: 'With a heavy heart, I said goodbye.', emoji: '🪨' },
    ],
};

export const highFreqExpressingAnger: SubTopic = {
    id: 'hf-expressing-anger',
    title: '表示生气 (Expressing Anger)',
    type: '高频词',
    color: 'purple',
    section: 'High Frequency',
    words: [
        { word: 'angry', level: 'basic', phonetic: '/ˈæŋɡri/', definition: '生气的', example: 'I get angry when people cut in line.', emoji: '😠' },
        { word: 'annoyed', level: 'basic', phonetic: '/əˈnɔɪd/', definition: '恼火的', example: 'I was annoyed by the noise.', emoji: '😒' },
        { word: 'cross', level: 'advanced', phonetic: '/krɔːs/', definition: '生气的（英式口语）', example: 'My mum was cross with me for being late.', emoji: '😤' },
        { word: 'furious', level: 'advanced', phonetic: '/ˈfjʊriəs/', definition: '暴怒的', example: 'He was furious about the delay.', emoji: '🤬' },
        { word: 'irritated', level: 'advanced', phonetic: '/ˈɪrɪteɪtɪd/', definition: '恼怒的', example: 'I was irritated by constant interruptions.', emoji: '😑' },
        { word: 'mad', level: 'basic', phonetic: '/mæd/', definition: '生气的（口语）', example: 'I was mad at him for lying to me.', emoji: '😡' },
        { word: 'red-hot', level: 'advanced', phonetic: '', definition: '非常愤怒的', example: 'I was red-hot with anger for a moment.', emoji: '🔥' },
        { word: 'upset', level: 'basic', phonetic: '/ʌpˈset/', definition: '心烦的；生气的', example: 'I was upset about what happened.', emoji: '😣' },
        { word: 'be pissed off', level: 'advanced', phonetic: '', definition: '非常生气（口语/略粗）', example: 'I was really pissed off when my flight got canceled.', emoji: '🚫' },
        { word: 'blow one\'s top', level: 'advanced', phonetic: '', definition: '勃然大怒', example: 'He blew his top when he heard the news.', emoji: '💥' },
        { word: 'burn someone up', level: 'advanced', phonetic: '', definition: '让某人火大', example: 'It really burns me up when people are rude.', emoji: '🔥' },
        { word: 'burst with anger', level: 'advanced', phonetic: '', definition: '气炸了', example: 'She was bursting with anger.', emoji: '💢' },
        { word: 'drive someone nuts', level: 'advanced', phonetic: '', definition: '把某人逼疯/惹毛', example: 'That noise drives me nuts.', emoji: '🤯' },
        { word: 'freak out', level: 'advanced', phonetic: '', definition: '抓狂/情绪失控', example: 'He freaked out and started shouting.', emoji: '😵' },
        { word: 'get on one\'s nerves', level: 'advanced', phonetic: '', definition: '惹恼某人', example: 'Loud chewing really gets on my nerves.', emoji: '🧨' },
        { word: 'go bananas', level: 'advanced', phonetic: '', definition: '抓狂/暴怒', example: 'My dad goes bananas when the internet is down.', emoji: '🍌' },
        { word: 'have a cow', level: 'advanced', phonetic: '', definition: '大惊小怪/生大气', example: 'Don\'t have a cow—it\'s not a big deal.', emoji: '🐄' },
        { word: 'have a fit', level: 'advanced', phonetic: '', definition: '大发脾气', example: 'He had a fit when he saw the mess.', emoji: '😤' },
        { word: 'hit the ceiling', level: 'advanced', phonetic: '', definition: '暴跳如雷', example: 'My boss hit the ceiling when he found out.', emoji: '🏠' },
        { word: 'hit the roof', level: 'advanced', phonetic: '', definition: '怒不可遏', example: 'She hit the roof over the extra charges.', emoji: '🏚️' },
        { word: 'in a rage', level: 'advanced', phonetic: '', definition: '暴怒中', example: 'He stormed out in a rage.', emoji: '😡' },
        { word: 'lose one\'s temper', level: 'advanced', phonetic: '', definition: '发脾气/失去耐心', example: 'I try not to lose my temper in public.', emoji: '🌡️' },
        { word: 'make one\'s blood boil', level: 'advanced', phonetic: '', definition: '让人火冒三丈', example: 'It makes my blood boil when people cheat.', emoji: '🩸' },
        { word: 'tick sb. off', level: 'advanced', phonetic: '', definition: '惹恼某人（口语）', example: 'It ticks me off when people are late.', emoji: '😤' },
    ],
};

export const highFreqExpressingManyALot: SubTopic = {
    id: 'hf-expressing-many-a-lot',
    title: '表示很多 (Expressing Many/A Lot)',
    type: '高频词',
    color: 'green',
    section: 'High Frequency',
    words: [
        { word: 'countless', level: 'advanced', phonetic: '/ˈkaʊntləs/', definition: '无数的', example: 'There are countless reasons to learn English.', emoji: '♾️' },
        { word: 'immeasurable', level: 'advanced', phonetic: '/ɪˈmeʒərəbl/', definition: '无法估量的', example: 'Her support has been immeasurable.', emoji: '📏' },
        { word: 'inexhaustible', level: 'advanced', phonetic: '/ˌɪnɪɡˈzɔːstəbl/', definition: '用之不竭的', example: 'He seems to have inexhaustible energy.', emoji: '🔋' },
        { word: 'innumerable', level: 'advanced', phonetic: '/ɪˈnuːmərəbl/', definition: '无数的', example: 'I\'ve seen innumerable videos about this topic.', emoji: '🔢' },
        { word: 'numerous', level: 'advanced', phonetic: '/ˈnuːmərəs/', definition: '众多的', example: 'There are numerous cafés near my home.', emoji: '🏙️' },
        { word: 'unbounded', level: 'advanced', phonetic: '/ʌnˈbaʊndɪd/', definition: '无限的；无边无际的', example: 'She has unbounded curiosity.', emoji: '🌌' },
        { word: 'unlimited', level: 'advanced', phonetic: '/ʌnˈlɪmɪtɪd/', definition: '无限的', example: 'Online courses offer almost unlimited resources.', emoji: '🧰' },
        { word: 'unstinting', level: 'advanced', phonetic: '/ʌnˈstɪntɪŋ/', definition: '毫不吝啬的；慷慨的', example: 'He gave me unstinting help.', emoji: '🤝' },
        { word: 'untold', level: 'advanced', phonetic: '/ʌnˈtoʊld/', definition: '无数的；说不尽的', example: 'It caused untold damage to the environment.', emoji: '🌪️' },
        { word: 'various', level: 'basic', phonetic: '/ˈveriəs/', definition: '各种各样的', example: 'I enjoy various kinds of music.', emoji: '🎶' },
        { word: 'many', level: 'basic', phonetic: '/ˈmeni/', definition: '许多（可数）', example: 'Many students prefer studying in the library.', emoji: '👥' },
        { word: 'much', level: 'basic', phonetic: '/mʌtʃ/', definition: '许多（不可数）', example: 'I don\'t have much free time on weekdays.', emoji: '⏳' },
        { word: 'a bunch of', level: 'basic', phonetic: '', definition: '一堆/很多（口语）', example: 'I have a bunch of friends from university.', emoji: '🧺' },
        { word: 'a couple of', level: 'basic', phonetic: '', definition: '两三个/几个', example: 'I usually do it a couple of times a week.', emoji: '2️⃣' },
        { word: 'a dozen of', level: 'advanced', phonetic: '', definition: '一打/很多（约12个）', example: 'I bought a dozen of eggs on my way home.', emoji: '🥚' },
        { word: 'a great deal of', level: 'advanced', phonetic: '', definition: '大量（不可数）', example: 'I spend a great deal of time commuting.', emoji: '🧳' },
        { word: 'a great many of', level: 'advanced', phonetic: '', definition: '很多（可数）', example: 'A great many of my classmates live nearby.', emoji: '👥' },
        { word: 'a great quantity of', level: 'advanced', phonetic: '', definition: '大量（可数/不可数均可，但更书面）', example: 'A great quantity of waste is produced every day.', emoji: '🗑️' },
        { word: 'a large amount of', level: 'advanced', phonetic: '', definition: '大量（不可数）', example: 'I drink a large amount of water every day.', emoji: '💧' },
        { word: 'a lot of', level: 'basic', phonetic: '', definition: '很多', example: 'I have a lot of hobbies.', emoji: '🧩' },
        { word: 'a number of', level: 'advanced', phonetic: '', definition: '若干；许多（可数）', example: 'A number of people commute by subway.', emoji: '🚇' },
        { word: 'a variety of', level: 'advanced', phonetic: '', definition: '各种各样的', example: 'There are a variety of restaurants in my area.', emoji: '🍽️' },
        { word: 'dozens of', level: 'advanced', phonetic: '', definition: '几十个/许多', example: 'Dozens of tourists visit the museum every day.', emoji: '👣' },
        { word: 'large amounts of', level: 'advanced', phonetic: '', definition: '大量（不可数，复数强调很多次/很多种）', example: 'We waste large amounts of water without noticing.', emoji: '🚿' },
        { word: 'large quantities of', level: 'advanced', phonetic: '', definition: '大量（更正式）', example: 'They import large quantities of coffee beans.', emoji: '🫘' },
        { word: 'loads of', level: 'advanced', phonetic: '', definition: '很多（口语）', example: 'There are loads of things to do in the city.', emoji: '🧳' },
        { word: 'lots of', level: 'basic', phonetic: '', definition: '很多', example: 'I take lots of photos when I travel.', emoji: '📸' },
        { word: 'plenty of', level: 'basic', phonetic: '', definition: '很多；足够多', example: 'There\'s plenty of time to prepare.', emoji: '✅' },
        { word: 'quite a few', level: 'advanced', phonetic: '', definition: '相当多（可数）', example: 'I\'ve met quite a few people from different countries.', emoji: '🌍' },
        { word: 'quite a little', level: 'advanced', phonetic: '', definition: '相当多（不可数）', example: 'It takes quite a little time to build a habit.', emoji: '⏱️' },
    ],
};

export const highFreqExpressingFatigueTiredness: SubTopic = {
    id: 'hf-expressing-fatigue-tiredness',
    title: '表示很累 (Expressing Fatigue/Tiredness)',
    type: '高频词',
    color: 'blue',
    section: 'High Frequency',
    words: [
        { word: 'beat', level: 'advanced', phonetic: '/biːt/', definition: '累坏了（口语）', example: 'I\'m beat after a long day at work.', emoji: '😮‍💨' },
        { word: 'dog-tired', level: 'advanced', phonetic: '', definition: '累得像狗一样/筋疲力尽（口语）', example: 'I was dog-tired after the hike.', emoji: '🐶' },
        { word: 'drained', level: 'advanced', phonetic: '/dreɪnd/', definition: '精疲力竭的；被掏空的', example: 'I felt drained after back-to-back meetings.', emoji: '🪫' },
        { word: 'exhausted', level: 'basic', phonetic: '/ɪɡˈzɔːstɪd/', definition: '筋疲力尽的', example: 'I\'m exhausted, so I\'ll go to bed early.', emoji: '😴' },
        { word: 'fagged', level: 'advanced', phonetic: '/fæɡd/', definition: '累坏了（英式/较口语）', example: 'I was fagged after running errands all day.', emoji: '🏃' },
        { word: 'knackered', level: 'advanced', phonetic: '/ˈnækərd/', definition: '累趴了（英式口语）', example: 'I\'m absolutely knackered today.', emoji: '🪫' },
        { word: 'overworked', level: 'advanced', phonetic: '/ˌoʊvərˈwɜːrkt/', definition: '过度劳累的', example: 'Many office workers feel overworked.', emoji: '🧑‍💻' },
        { word: 'spent', level: 'advanced', phonetic: '/spent/', definition: '疲惫不堪的；精力耗尽的', example: 'I felt spent after the exam.', emoji: '📚' },
        { word: 'tired', level: 'basic', phonetic: '/ˈtaɪərd/', definition: '疲惫的', example: 'I\'m tired, but I still need to finish my work.', emoji: '😪' },
        { word: 'run on empty', level: 'advanced', phonetic: '', definition: '靠最后一点力气硬撑/电量见底（比喻）', example: 'By Friday night, I\'m basically running on empty.', emoji: '⛽️' },
        { word: 'tired to the bone', level: 'advanced', phonetic: '', definition: '累到骨子里', example: 'After moving house, I was tired to the bone.', emoji: '🦴' },
        { word: 'wiped out', level: 'advanced', phonetic: '', definition: '累趴了/精疲力尽（口语）', example: 'I was wiped out after the long flight.', emoji: '✈️' },
        { word: 'worn out', level: 'advanced', phonetic: '', definition: '疲惫不堪的；累坏了', example: 'I get worn out if I don\'t sleep well.', emoji: '🛌' },
    ],
};

export const highFreqExpressingHighStressPressure: SubTopic = {
    id: 'hf-expressing-high-stress-pressure',
    title: '表示压力很大 (Expressing High Stress/Pressure)',
    type: '高频词',
    color: 'purple',
    section: 'High Frequency',
    words: [
        { word: 'anxious', level: 'basic', phonetic: '/ˈæŋkʃəs/', definition: '焦虑的', example: 'I feel anxious before important exams.', emoji: '😰' },
        { word: 'burdened', level: 'advanced', phonetic: '/ˈbɜːrdnd/', definition: '负担沉重的', example: 'I felt burdened by too many responsibilities.', emoji: '🎒' },
        { word: 'concerned', level: 'basic', phonetic: '/kənˈsɜːrnd/', definition: '担心的；忧虑的', example: 'I\'m concerned about the rising cost of living.', emoji: '📉' },
        { word: 'overwhelmed', level: 'basic', phonetic: '/ˌoʊvərˈwelmd/', definition: '不堪重负的', example: 'I felt overwhelmed when deadlines piled up.', emoji: '🧱' },
        { word: 'tense', level: 'basic', phonetic: '/tens/', definition: '紧张的', example: 'I get tense when I speak in public.', emoji: '🧊' },
        { word: 'on edge', level: 'advanced', phonetic: '', definition: '神经紧绷/如坐针毡', example: 'I\'ve been on edge these days because of work.', emoji: '⚡️' },
        { word: 'put pressure on', level: 'advanced', phonetic: '', definition: '给……施加压力', example: 'Parents shouldn\'t put too much pressure on kids.', emoji: '🗜️' },
        { word: 'stressed out', level: 'advanced', phonetic: '', definition: '压力爆表/特别焦虑（口语）', example: 'I was stressed out before the interview.', emoji: '😵‍💫' },
        { word: 'under pressure', level: 'advanced', phonetic: '', definition: '在压力之下', example: 'I can still perform well under pressure.', emoji: '🧪' },
        { word: 'under stress', level: 'advanced', phonetic: '', definition: '处于压力状态', example: 'When I\'m under stress, I tend to overthink.', emoji: '🧠' },
        { word: 'under the gun', level: 'advanced', phonetic: '', definition: '时间紧/压力大（口语）', example: 'We were under the gun to finish the project.', emoji: '⏱️' },
    ],
};

export const highFreqExpressingVeryBusy: SubTopic = {
    id: 'hf-expressing-very-busy',
    title: '表示很忙 (Expressing Very Busy)',
    type: '高频词',
    color: 'yellow',
    section: 'High Frequency',
    words: [
        { word: 'overwhelm', level: 'advanced', phonetic: '/ˌoʊvərˈwelm/', definition: '使不堪重负；压得喘不过气', example: 'Deadlines can overwhelm me sometimes.', emoji: '🌊' },
        { word: 'busy', level: 'basic', phonetic: '/ˈbɪzi/', definition: '忙的', example: 'I\'m busy on weekdays, especially in the evening.', emoji: '📅' },
        { word: 'engaged', level: 'advanced', phonetic: '/ɪnˈɡeɪdʒd/', definition: '忙于……的；投入的', example: 'I\'m engaged in a project at the moment.', emoji: '🔧' },
        { word: 'occupied', level: 'basic', phonetic: '/ˈɑːkjəpaɪd/', definition: '忙着的；被占用的', example: 'I\'m occupied with work right now.', emoji: '🧑‍💻' },
        { word: 'around the clock', level: 'advanced', phonetic: '', definition: '24小时不停地', example: 'During peak season, some people work around the clock.', emoji: '🕒' },
        { word: 'as busy as a bee', level: 'advanced', phonetic: '', definition: '忙得团团转', example: 'Before exams, I\'m as busy as a bee.', emoji: '🐝' },
        { word: 'be swamped with', level: 'advanced', phonetic: '', definition: '忙到被……淹没', example: 'I\'m swamped with assignments this week.', emoji: '🌊' },
        { word: 'don\'t have time to catch one\'s breath', level: 'advanced', phonetic: '', definition: '忙得连喘口气都没时间', example: 'These days, I don\'t even have time to catch my breath.', emoji: '😮‍💨' },
        { word: 'have a lot on one\'s plate', level: 'advanced', phonetic: '', definition: '手头事很多/一堆事要处理', example: 'I have a lot on my plate at the moment.', emoji: '🍽️' },
        { word: 'have irons in the fire', level: 'advanced', phonetic: '', definition: '同时推进多件事', example: 'I usually have a few irons in the fire.', emoji: '🔥' },
        { word: 'have one\'s hands full', level: 'advanced', phonetic: '', definition: '忙不过来；分身乏术', example: 'I have my hands full with work and study.', emoji: '🤹' },
        { word: 'I\'m slammed.', level: 'advanced', phonetic: '', definition: '我忙炸了（口语）', example: 'Sorry, I\'m slammed today.', emoji: '📌' },
        { word: 'on the go', level: 'advanced', phonetic: '', definition: '一直在奔波/忙个不停', example: 'I\'m on the go from morning till night.', emoji: '🏃' },
        { word: 'go round in circles', level: 'advanced', phonetic: '', definition: '忙得没效率/原地打转', example: 'When I\'m too tired, I just go round in circles.', emoji: '🔄' },
        { word: 'run off one\'s feet', level: 'advanced', phonetic: '', definition: '忙得脚不沾地', example: 'I was run off my feet last week.', emoji: '🦶' },
        { word: 'tied up', level: 'advanced', phonetic: '', definition: '忙得脱不开身', example: 'I\'m tied up with meetings all afternoon.', emoji: '🪢' },
        { word: 'up to one\'s ears', level: 'advanced', phonetic: '', definition: '忙到“淹没”', example: 'I\'m up to my ears in paperwork.', emoji: '📄' },
        { word: 'up to one\'s neck', level: 'advanced', phonetic: '', definition: '忙到“没脖子”', example: 'I\'m up to my neck in deadlines.', emoji: '⏳' },
    ],
};

export const highFreqExpressingStressReliefRelaxation: SubTopic = {
    id: 'hf-expressing-stress-relief-relaxation',
    title: '表示放松压力 (Expressing Stress Relief/Relaxation)',
    type: '高频词',
    color: 'green',
    section: 'High Frequency',
    words: [
        { word: 'alleviate', level: 'advanced', phonetic: '/əˈliːvieɪt/', definition: '缓解（压力/疼痛等）', example: 'I listen to music to alleviate stress.', emoji: '🩹' },
        { word: 'ease', level: 'basic', phonetic: '/iːz/', definition: '缓解；减轻', example: 'A short walk can ease my mind.', emoji: '🚶' },
        { word: 'lighten', level: 'advanced', phonetic: '/ˈlaɪtn/', definition: '缓和；减轻；让气氛轻松', example: 'A joke can lighten the mood.', emoji: '💡' },
        { word: 'mitigate', level: 'advanced', phonetic: '/ˈmɪtɪɡeɪt/', definition: '减轻；缓和（负面影响）', example: 'I plan ahead to mitigate stress.', emoji: '🛡️' },
        { word: 'relax', level: 'basic', phonetic: '/rɪˈlæks/', definition: '放松', example: 'I relax by reading at night.', emoji: '😌' },
        { word: 'soothe', level: 'advanced', phonetic: '/suːð/', definition: '舒缓；安抚', example: 'A warm bath soothes my muscles.', emoji: '🛀' },
        { word: 'unwind', level: 'advanced', phonetic: '/ʌnˈwaɪnd/', definition: '放松；解压', example: 'I unwind by watching a sitcom.', emoji: '📺' },
        { word: 'calm down', level: 'basic', phonetic: '', definition: '冷静下来', example: 'I take deep breaths to calm down.', emoji: '🌬️' },
        { word: 'chill out', level: 'advanced', phonetic: '', definition: '放松一下（口语）', example: 'I just want to chill out at home tonight.', emoji: '🛋️' },
        { word: 'get away from the daily grind', level: 'advanced', phonetic: '', definition: '暂时逃离日常琐事/日常工作', example: 'A short trip helps me get away from the daily grind.', emoji: '🏝️' },
        { word: 'kick back', level: 'advanced', phonetic: '', definition: '放松；休息（口语）', example: 'On weekends, I kick back with a cup of tea.', emoji: '☕️' },
        { word: 'let off steam', level: 'advanced', phonetic: '', definition: '释放压力；发泄一下', example: 'I go for a run to let off steam.', emoji: '💨' },
        { word: 'let one\'s hair down', level: 'advanced', phonetic: '', definition: '放开玩；彻底放松', example: 'I let my hair down when I hang out with close friends.', emoji: '🎉' },
        { word: 'loosen up', level: 'advanced', phonetic: '', definition: '放轻松；别那么紧绷', example: 'It takes a while for me to loosen up in a new environment.', emoji: '🧊' },
        { word: 'mellow out', level: 'advanced', phonetic: '', definition: '变得平和；放松下来', example: 'Music helps me mellow out after work.', emoji: '🎵' },
        { word: 'put one\'s feet up', level: 'advanced', phonetic: '', definition: '翘脚休息', example: 'After dinner, I put my feet up and watch TV.', emoji: '🦶' },
        { word: 'reduce stress', level: 'basic', phonetic: '', definition: '减少压力', example: 'Good sleep can reduce stress.', emoji: '📉' },
        { word: 'relieve stress', level: 'basic', phonetic: '', definition: '缓解压力', example: 'Exercise can relieve stress effectively.', emoji: '🏃' },
        { word: 'take a break', level: 'basic', phonetic: '', definition: '休息一下', example: 'I take a break every hour when I study.', emoji: '⏸️' },
        { word: 'take a chill pill', level: 'advanced', phonetic: '', definition: '冷静点/放轻松（口语）', example: 'Take a chill pill—it\'s not that serious.', emoji: '💊' },
    ],
};

export const highFreqExpressingImportant: SubTopic = {
    id: 'hf-expressing-important',
    title: '表示重要的 (Expressing Important)',
    type: '高频词',
    color: 'purple',
    section: 'High Frequency',
    words: [
        { word: 'central', level: 'advanced', phonetic: '/ˈsentrəl/', definition: '核心的；中心的', example: 'Communication is central to teamwork.', emoji: '🎯' },
        { word: 'considerable', level: 'advanced', phonetic: '/kənˈsɪdərəbl/', definition: '相当大的；很重要的', example: 'It takes considerable effort to build a habit.', emoji: '🧱' },
        { word: 'critical', level: 'advanced', phonetic: '/ˈkrɪtɪkl/', definition: '关键的；至关重要的', example: 'It\'s critical to manage your time well.', emoji: '🚨' },
        { word: 'crucial', level: 'advanced', phonetic: '/ˈkruːʃl/', definition: '至关重要的', example: 'Sleep is crucial for my productivity.', emoji: '🔑' },
        { word: 'essential', level: 'advanced', phonetic: '/ɪˈsenʃl/', definition: '必不可少的', example: 'Practice is essential for progress.', emoji: '✨' },
        { word: 'front-page', level: 'advanced', phonetic: '', definition: '头版的；最重要的；引人关注的', example: 'It became front-page news overnight.', emoji: '🗞️' },
        { word: 'fundamental', level: 'advanced', phonetic: '/ˌfʌndəˈmentl/', definition: '根本的；基础的', example: 'Vocabulary is fundamental to speaking well.', emoji: '📚' },
        { word: 'imperative', level: 'advanced', phonetic: '/ɪmˈperətɪv/', definition: '极其重要且必要的', example: 'It\'s imperative to stay calm in interviews.', emoji: '📣' },
        { word: 'important', level: 'basic', phonetic: '/ɪmˈpɔːrtnt/', definition: '重要的', example: 'Family is important to me.', emoji: '⭐️' },
        { word: 'major', level: 'basic', phonetic: '/ˈmeɪdʒər/', definition: '重大的；主要的', example: 'It was a major change in my routine.', emoji: '🏔️' },
        { word: 'momentous', level: 'advanced', phonetic: '/moʊˈmentəs/', definition: '重大的；影响深远的', example: 'Graduation is a momentous event for many people.', emoji: '🎓' },
        { word: 'necessary', level: 'basic', phonetic: '/ˈnesəseri/', definition: '必要的', example: 'It\'s necessary to set realistic goals.', emoji: '✅' },
        { word: 'paramount', level: 'advanced', phonetic: '/ˈpærəmaʊnt/', definition: '最重要的；首要的', example: 'Safety is paramount.', emoji: '🛡️' },
        { word: 'pivotal', level: 'advanced', phonetic: '/ˈpɪvətl/', definition: '关键的；枢纽性的', example: 'It was a pivotal moment in my life.', emoji: '🧭' },
        { word: 'primary', level: 'advanced', phonetic: '/ˈpraɪmeri/', definition: '主要的；首要的', example: 'My primary goal is fluency.', emoji: '1️⃣' },
        { word: 'principal', level: 'advanced', phonetic: '/ˈprɪnsəpl/', definition: '主要的；最重要的', example: 'The principal reason is the cost.', emoji: '🧾' },
        { word: 'prominent', level: 'advanced', phonetic: '/ˈprɑːmɪnənt/', definition: '重要的；显著的', example: 'It\'s a prominent feature of the city.', emoji: '🏙️' },
        { word: 'significant', level: 'advanced', phonetic: '/sɪɡˈnɪfɪkənt/', definition: '重要的；显著的', example: 'There was a significant improvement over time.', emoji: '📈' },
        { word: 'staple', level: 'advanced', phonetic: '/ˈsteɪpl/', definition: '必需品；主食；常见/常用之物', example: 'Rice is a staple food in my country.', emoji: '🍚' },
        { word: 'substantial', level: 'advanced', phonetic: '/səbˈstænʃl/', definition: '重大的；可观的', example: 'It had a substantial impact on my schedule.', emoji: '🧱' },
        { word: 'urgent', level: 'basic', phonetic: '/ˈɜːrdʒənt/', definition: '紧急的', example: 'It\'s urgent to solve the problem quickly.', emoji: '⏰' },
        { word: 'valuable', level: 'basic', phonetic: '/ˈvæljuəbl/', definition: '有价值的', example: 'That feedback was really valuable.', emoji: '💎' },
        { word: 'vital', level: 'advanced', phonetic: '/ˈvaɪtl/', definition: '至关重要的', example: 'Water is vital for health.', emoji: '💧' },
        { word: 'put ... on the map', level: 'advanced', phonetic: '', definition: '让……出名/让……进入大众视野', example: 'That movie put the city on the map.', emoji: '🗺️' },
        { word: 'top priority', level: 'advanced', phonetic: '', definition: '头等大事；首要任务', example: 'My top priority is staying healthy.', emoji: '🥇' },
    ],
};

export const highFreqExpressingDeliciousTasty: SubTopic = {
    id: 'hf-expressing-delicious-tasty',
    title: '表示美味 (Expressing Delicious/Tasty)',
    type: '高频词',
    color: 'yellow',
    section: 'High Frequency',
    words: [
        { word: 'appetizing', level: 'advanced', phonetic: '/ˈæpɪtaɪzɪŋ/', definition: '开胃的；诱人的', example: 'The smell was really appetizing.', emoji: '🍽️' },
        { word: 'delectable', level: 'advanced', phonetic: '/dɪˈlektəbl/', definition: '美味的；可口的', example: 'The dessert was absolutely delectable.', emoji: '🍰' },
        { word: 'delicious', level: 'basic', phonetic: '/dɪˈlɪʃəs/', definition: '美味的', example: 'The noodles were delicious.', emoji: '🍜' },
        { word: 'flavourful', level: 'advanced', phonetic: '/ˈfleɪvərfl/', definition: '味道浓郁的；很有味道的', example: 'It\'s a flavourful dish with lots of spices.', emoji: '🌶️' },
        { word: 'lip-smacking', level: 'advanced', phonetic: '', definition: '让人回味无穷的；好吃到“咂嘴”的', example: 'The barbecue was lip-smacking.', emoji: '😋' },
        { word: 'luscious', level: 'advanced', phonetic: '/ˈlʌʃəs/', definition: '甘美的；多汁可口的', example: 'The mango was so luscious and sweet.', emoji: '🥭' },
        { word: 'mouth-watering', level: 'advanced', phonetic: '', definition: '让人垂涎欲滴的', example: 'The steak looks mouth-watering.', emoji: '🤤' },
        { word: 'palatable', level: 'advanced', phonetic: '/ˈpælətəbl/', definition: '可口的；好吃的（更书面）', example: 'It\'s quite palatable, even for kids.', emoji: '🍲' },
        { word: 'savoury', level: 'advanced', phonetic: '/ˈseɪvəri/', definition: '咸香的；可口的（非甜）', example: 'I prefer savoury snacks to sweets.', emoji: '🧀' },
        { word: 'scrumptious', level: 'advanced', phonetic: '/ˈskrʌmʃəs/', definition: '非常美味的（口语）', example: 'The homemade soup was scrumptious.', emoji: '🥣' },
        { word: 'tasty', level: 'basic', phonetic: '/ˈteɪsti/', definition: '好吃的', example: 'It\'s a simple but tasty meal.', emoji: '🍱' },
        { word: 'toothsome', level: 'advanced', phonetic: '/ˈtuːθsəm/', definition: '可口的；开胃的（较书面）', example: 'It was a toothsome snack.', emoji: '🥪' },
        { word: 'yummy', level: 'basic', phonetic: '/ˈjʌmi/', definition: '好吃的（更口语）', example: 'This cake is really yummy.', emoji: '🧁' },
        { word: 'finger-licking good', level: 'advanced', phonetic: '', definition: '好吃到吮手指', example: 'The fried chicken was finger-licking good.', emoji: '🍗' },
        { word: 'give pleasure to (the) taste buds', level: 'advanced', phonetic: '', definition: '让味蕾很享受', example: 'It really gives pleasure to the taste buds.', emoji: '👅' },
        { word: 'make one\'s mouth water', level: 'advanced', phonetic: '', definition: '让人流口水/垂涎欲滴', example: 'Just looking at it makes my mouth water.', emoji: '🤤' },
    ],
};

export const highFreqExpressingBeautifulPretty: SubTopic = {
    id: 'hf-expressing-beautiful-pretty',
    title: '表示漂亮 (Expressing Beautiful/Pretty)',
    type: '高频词',
    color: 'purple',
    section: 'High Frequency',
    words: [
        { word: 'alluring', level: 'advanced', phonetic: '/əˈlʊrɪŋ/', definition: '迷人的；吸引人的', example: 'The city has an alluring charm at night.', emoji: '✨' },
        { word: 'attractive', level: 'basic', phonetic: '/əˈtræktɪv/', definition: '有吸引力的', example: 'It\'s an attractive option for students.', emoji: '🧲' },
        { word: 'awesome', level: 'basic', phonetic: '/ˈɔːsəm/', definition: '很棒的；很惊艳的（口语）', example: 'The view from the top was awesome.', emoji: '🌄' },
        { word: 'charming', level: 'basic', phonetic: '/ˈtʃɑːrmɪŋ/', definition: '迷人的；有魅力的', example: 'It\'s a charming little town.', emoji: '🏘️' },
        { word: 'cute', level: 'basic', phonetic: '/kjuːt/', definition: '可爱的', example: 'That puppy is so cute.', emoji: '🐶' },
        { word: 'elegant', level: 'advanced', phonetic: '/ˈelɪɡənt/', definition: '优雅的', example: 'She wore an elegant dress.', emoji: '👗' },
        { word: 'exquisite', level: 'advanced', phonetic: '/ˈekskwɪzɪt/', definition: '精美的；精致的', example: 'The craftsmanship is exquisite.', emoji: '🖼️' },
        { word: 'fantastic', level: 'basic', phonetic: '/fænˈtæstɪk/', definition: '极好的；非常漂亮的', example: 'The sunset looked fantastic.', emoji: '🌇' },
        { word: 'good-looking', level: 'basic', phonetic: '', definition: '好看的', example: 'He\'s good-looking, but also very kind.', emoji: '🙂' },
        { word: 'gorgeous', level: 'advanced', phonetic: '/ˈɡɔːrdʒəs/', definition: '非常漂亮的', example: 'The beach was gorgeous.', emoji: '🏖️' },
        { word: 'handsome', level: 'basic', phonetic: '/ˈhænsəm/', definition: '英俊的；好看的（常形容男性）', example: 'He\'s a handsome guy.', emoji: '🕴️' },
        { word: 'incomparable', level: 'advanced', phonetic: '/ɪnˈkɑːmpərəbl/', definition: '无与伦比的', example: 'The scenery here is incomparable.', emoji: '🏞️' },
        { word: 'incredible', level: 'advanced', phonetic: '/ɪnˈkredəbl/', definition: '难以置信的；惊艳的', example: 'The architecture is incredible.', emoji: '🏛️' },
        { word: 'lovely', level: 'basic', phonetic: '/ˈlʌvli/', definition: '可爱的；美好的', example: 'It\'s a lovely neighborhood.', emoji: '💛' },
        { word: 'magnificent', level: 'advanced', phonetic: '/mæɡˈnɪfɪsnt/', definition: '壮丽的；宏伟的', example: 'The palace is magnificent.', emoji: '🏰' },
        { word: 'pretty', level: 'basic', phonetic: '/ˈprɪti/', definition: '漂亮的', example: 'It\'s a pretty dress.', emoji: '🌸' },
        { word: 'splendid', level: 'advanced', phonetic: '/ˈsplendɪd/', definition: '壮观的；极美的', example: 'We had a splendid view of the mountains.', emoji: '⛰️' },
        { word: 'stunning', level: 'advanced', phonetic: '/ˈstʌnɪŋ/', definition: '惊艳的', example: 'The lake looks stunning in the morning light.', emoji: '💎' },
    ],
};

export const highFreqExpressingDifficultHard: SubTopic = {
    id: 'hf-expressing-difficult-hard',
    title: '表示难的 (Expressing Difficult/Hard)',
    type: '高频词',
    color: 'blue',
    section: 'High Frequency',
    words: [
        { word: 'arduous', level: 'advanced', phonetic: '/ˈɑːrdʒuəs/', definition: '艰巨的；费力的', example: 'It was an arduous journey.', emoji: '⛰️' },
        { word: 'challenging', level: 'basic', phonetic: '/ˈtʃælɪndʒɪŋ/', definition: '有挑战性的', example: 'It\'s challenging, but I enjoy it.', emoji: '🎯' },
        { word: 'complicated', level: 'basic', phonetic: '/ˈkɑːmplɪkeɪtɪd/', definition: '复杂的', example: 'The process is more complicated than I expected.', emoji: '🧩' },
        { word: 'demanding', level: 'advanced', phonetic: '/dɪˈmændɪŋ/', definition: '要求高的；费力的', example: 'My job is mentally demanding.', emoji: '🧠' },
        { word: 'difficult', level: 'basic', phonetic: '/ˈdɪfɪkəlt/', definition: '困难的', example: 'It\'s difficult to keep a balance sometimes.', emoji: '🧗' },
        { word: 'formidable', level: 'advanced', phonetic: '/ˈfɔːrmɪdəbl/', definition: '艰难的；令人望而生畏的', example: 'It\'s a formidable task for beginners.', emoji: '🛡️' },
        { word: 'grueling', level: 'advanced', phonetic: '/ˈɡruːəlɪŋ/', definition: '极其累人的；艰苦的', example: 'It was a grueling schedule.', emoji: '🔥' },
        { word: 'hard', level: 'basic', phonetic: '/hɑːrd/', definition: '难的', example: 'It\'s hard to stay focused all the time.', emoji: '🪨' },
        { word: 'impossible', level: 'basic', phonetic: '/ɪmˈpɑːsəbl/', definition: '不可能的', example: 'It feels impossible without a plan.', emoji: '🚫' },
        { word: 'strenuous', level: 'advanced', phonetic: '/ˈstrenjuəs/', definition: '费力的；艰辛的', example: 'It\'s strenuous work, so I need breaks.', emoji: '🏋️' },
        { word: 'tricky', level: 'advanced', phonetic: '/ˈtrɪki/', definition: '棘手的', example: 'It\'s a tricky question in the interview.', emoji: '🪤' },
        { word: 'It\'s a hard nut to crack.', level: 'advanced', phonetic: '', definition: '这很难搞/很难解决', example: 'This problem is a hard nut to crack.', emoji: '🥜' },
        { word: 'It\'s a killer.', level: 'advanced', phonetic: '', definition: '这太要命了/太难了', example: 'That last task was a killer.', emoji: '💀' },
        { word: 'It\'s a pain in the neck.', level: 'advanced', phonetic: '', definition: '这很烦/很麻烦/很难缠', example: 'Paperwork is a pain in the neck.', emoji: '😣' },
        { word: 'It\'s rocket science.', level: 'advanced', phonetic: '', definition: '这很难/很专业（比喻）', example: 'Designing the system is basically rocket science for me.', emoji: '🚀' },
        { word: 'It\'s not a walk in the park.', level: 'advanced', phonetic: '', definition: '这可不轻松/没那么容易', example: 'Learning a language is not a walk in the park.', emoji: '🌳' },
    ],
};

export const highFreqExpressingEasy: SubTopic = {
    id: 'hf-expressing-easy',
    title: '表示容易的 (Expressing Easy)',
    type: '高频词',
    color: 'green',
    section: 'High Frequency',
    words: [
        { word: 'easy', level: 'basic', phonetic: '/ˈiːzi/', definition: '容易的', example: 'It\'s easy once you get used to it.', emoji: '✅' },
        { word: 'simple', level: 'basic', phonetic: '/ˈsɪmpl/', definition: '简单的', example: 'It\'s a simple method that works well.', emoji: '🧩' },
        { word: 'I can do it with my eyes closed!', level: 'advanced', phonetic: '', definition: '这太简单了/闭着眼都能做', example: 'This part is so easy—I can do it with my eyes closed!', emoji: '🙈' },
        { word: 'It\'s a cinch.', level: 'advanced', phonetic: '', definition: '小菜一碟', example: 'If you follow the steps, it\'s a cinch.', emoji: '👌' },
        { word: 'It\'s a no-brainer.', level: 'advanced', phonetic: '', definition: '显而易见；不用动脑的选择', example: 'For me, taking the subway is a no-brainer.', emoji: '🧠' },
        { word: 'It\'s a piece of cake.', level: 'advanced', phonetic: '', definition: '小菜一碟', example: 'The exam was a piece of cake.', emoji: '🍰' },
        { word: 'It\'s a snap.', level: 'advanced', phonetic: '', definition: '轻而易举', example: 'With a template, it\'s a snap.', emoji: '🫰' },
        { word: 'It\'s as easy as ABC.', level: 'advanced', phonetic: '', definition: '简单得像 ABC 一样', example: 'For him, it\'s as easy as ABC.', emoji: '🔤' },
        { word: 'It\'s as easy as pie.', level: 'advanced', phonetic: '', definition: '非常容易', example: 'Once you practice, it\'s as easy as pie.', emoji: '🥧' },
        { word: 'It\'s no big deal.', level: 'advanced', phonetic: '', definition: '没什么大不了/不难', example: 'Don\'t worry—it\'s no big deal.', emoji: '🙂' },
        { word: 'not feel a thing', level: 'advanced', phonetic: '', definition: '一点感觉都没有/毫不费力（也可用于“没疼”）', example: 'The task was so easy that I didn\'t feel a thing.', emoji: '🫧' },
        { word: 'nothing to it', level: 'advanced', phonetic: '', definition: '没什么难的', example: 'Once you know the trick, there\'s nothing to it.', emoji: '✨' },
        { word: 'That\'s no sweat at all.', level: 'advanced', phonetic: '', definition: '一点也不费劲', example: 'Sure—I can help. That\'s no sweat at all.', emoji: '💧' },
    ],
};

// 后续可以继续在此处 export const 其他高频词类别
