import { SubTopic } from '../data-types';
import { getManyFromPool } from '../pool/utils';

export const gardening: SubTopic = {
    id: 'gardening',
    title: 'Growing Plants & Vegetables',
    type: '事件题',
    color: 'blue',
    isNew: true,
    wordSections: [
        {
            title: '基础词汇',
            words: getManyFromPool([
              'farm',
              'backyard',
              'soil',
              'seeds',
              'water',
              'sunlight',
              'fresh air',
              'plant seeds',
              'water the plants',
              'root',
              'stem',
              'petal',
              'blossom',
              'bloom',
              'potted plant',
              'houseplants',
              'indoor plants',
              'green plants',
              'flower shop',
              'school garden',
              'grow beans',
              'grow flowers',
              'observe the growth',
              'wait for it to sprout',
            ], 'basic')
        },
        {
            title: '进阶词汇',
            words: getManyFromPool([
              'cultivate',
              'harvest',
              'organic',
              'horticulture',
              'botany',
              'fragrance',
              'popular',
              'take care of',
              'home-grown',
              'relaxing',
              'enjoyable',
              'interesting',
              'rewarding',
              'meaningful',
              'close to nature',
              'healthy lifestyle',
              'take time and effort',
              'space',
              'easy to grow',
              'hands-on experience',
              'environmental education',
              'learn responsibility',
              'teamwork',
              'keep plants at home',
              'decorate the room',
              'make the room feel alive',
              'give enough sunlight',
              'school gardening class',
              'take time to grow',
              'symbol of good luck',
              'special occasions',
              'housewarming gift',
              'meaningful gift',
              'peaceful',
              'refreshing',
              'pleasant',
            ], 'advanced')
        }
    ],
};
