
import { SubTopic } from './data-types';

export const rules: SubTopic = {
    id: 'rules',
    title: 'Rules',
    type: '事物题',
    color: 'purple',
    wordSections: [
        {
            title: '基础词汇',
            words: [
                { word: 'allowed', phonetic: '/əˈlaʊd/', definition: '允许的', example: 'Students are not allowed to use their phones at school.', emoji: 'https://em-content.zobj.net/source/apple/391/check-mark-button_2705.png' },
                { word: 'benefit', phonetic: '/ˈbenɪfɪt/', definition: '益处；好处', example: 'Do you think students would benefit more from more rules?', emoji: 'https://em-content.zobj.net/source/apple/391/thumbs-up_1f44d.png' },
                { word: 'follow the rules', phonetic: '/ˈfɒloʊ ðə ruːlz/', definition: '遵守规则', example: 'It\'s important to follow the rules in a game.', emoji: 'https://em-content.zobj.net/source/apple/391/check-mark-button_2705.png' },
                { word: 'break the rules', phonetic: '/breɪk ðə ruːlz/', definition: '违反规则', example: 'You will be punished if you break the rules.', emoji: 'https://em-content.zobj.net/source/apple/391/prohibited_1f6ab.png' },
                { word: 'respect', phonetic: '/rɪˈspekt/', definition: '尊重', example: 'We should respect the school rules.', emoji: 'https://em-content.zobj.net/source/apple/391/folded-hands_1f64f.png' },
                { word: 'fewer', phonetic: '/ˈfjuːər/', definition: '更少的', example: 'Do you prefer to have more or fewer rules at school?', emoji: 'https://em-content.zobj.net/source/apple/391/minus_2212.png' },
                { word: 'enough', phonetic: '/ɪˈnʌf/', definition: '足够的', example: 'I think many students don’t have enough self-discipline.', emoji: 'https://em-content.zobj.net/source/apple/391/ok-button_1f197.png' },
                { word: 'traffic rules', phonetic: '/ˈtræfɪk ruːlz/', definition: '交通规则', example: 'Following traffic rules can prevent accidents.', emoji: 'https://em-content.zobj.net/source/apple/391/vertical-traffic-light_1f6a6.png' },
                { word: 'public rules', phonetic: '/ˈpʌblɪk ruːlz/', definition: '公共规则', example: 'In public places, we should follow public rules like keeping quiet.', emoji: 'https://em-content.zobj.net/source/apple/391/shushing-face_1f92b.png' },
                { word: 'no littering', phonetic: '/noʊ ˈlɪtərɪŋ/', definition: '禁止乱扔垃圾', example: 'The sign says "no littering" in the park.', emoji: 'https://em-content.zobj.net/source/apple/391/litter-in-bin-sign_1f6ae.png' },
                { word: 'reasonable', phonetic: '/ˈriːznəbl/', definition: '合理的', example: 'The school rules are quite reasonable.', emoji: 'https://em-content.zobj.net/source/apple/391/thinking-face_1f914.png' },
                { word: 'annoying', phonetic: '/əˈnɔɪɪŋ/', definition: '烦人的', example: 'Some rules can be really annoying and unnecessary.', emoji: 'https://em-content.zobj.net/source/apple/391/angry-face_1f620.png' },
                { word: 'strict', phonetic: '/strɪkt/', definition: '严格的', example: 'Have you ever had a really strict teacher?', emoji: 'https://em-content.zobj.net/source/apple/391/man-judge_1f468-200d-2696-fe0f.png' },
                { word: 'school discipline', phonetic: '/skuːl ˈdɪsəplɪn/', definition: '校纪', example: 'Good school discipline is important for a positive learning environment.', emoji: 'https://em-content.zobj.net/source/apple/391/school_1f3eb.png' },
                { word: 'behave well', phonetic: '/bɪˈheɪv wel/', definition: '表现良好', example: 'Students are expected to behave well in the classroom.', emoji: 'https://em-content.zobj.net/source/apple/391/smiling-face-with-halo_1f607.png' },
                { word: 'misbehave', phonetic: '/ˌmɪsbɪˈheɪv/', definition: '行为不端', example: 'If you misbehave, you might get detention.', emoji: 'https://em-content.zobj.net/source/apple/391/smiling-face-with-horns_1f608.png' },
                { word: 'wear school uniform', phonetic: '/wer skuːl ˈjuːnɪfɔːrm/', definition: '穿校服', example: 'All students are required to wear a school uniform.', emoji: 'https://em-content.zobj.net/source/apple/391/t-shirt_1f455.png' },
                { word: 'no phones in class', phonetic: '/noʊ foʊnz ɪn klæs/', definition: '课上不准用手机', example: 'A common rule is "no phones in class" to help students focus.', emoji: 'https://em-content.zobj.net/source/apple/391/no-mobile-phones_1f4f5.png' },
                { word: 'warning', phonetic: '/ˈwɔːrnɪŋ/', definition: '警告', example: 'The teacher gave him a final warning before taking action.', emoji: 'https://em-content.zobj.net/source/apple/391/warning_26a0-fe0f.png' },
                { word: 'punishment', phonetic: '/ˈpʌnɪʃmənt/', definition: '惩罚', example: 'The punishment for cheating on the exam is severe.', emoji: 'https://em-content.zobj.net/source/apple/391/prohibited_1f6ab.png' },
                { word: 'get into trouble', phonetic: '/ɡet ˈɪntu ˈtrʌbl/', definition: '惹上麻烦', example: 'If you don\'t follow the rules, you will get into trouble.', emoji: 'https://em-content.zobj.net/source/apple/391/worried-face_1f61f.png' },
                { word: 'fair', phonetic: '/fer/', definition: '公平的', example: 'The rules should be fair to all students.', emoji: 'https://em-content.zobj.net/source/apple/391/balance-scale_2696-fe0f.png' },
                { word: 'unfair', phonetic: '/ʌnˈfer/', definition: '不公平的', example: 'He felt the punishment was unfair.', emoji: 'https://em-content.zobj.net/source/apple/391/pouting-face_1f621.png' },
            ],
        },
        {
            title: '进阶词汇',
            words: [
                { word: 'focus', phonetic: '/ˈfoʊkəs/', definition: '集中；专注', example: 'With more rules, students can focus more on their studies.', emoji: 'https://em-content.zobj.net/source/apple/391/direct-hit_1f3af.png' },
                { word: 'practice', phonetic: '/ˈpræktɪs/', definition: '练习', example: 'After school, she usually helped students with their practice.', emoji: 'https://em-content.zobj.net/source/apple/391/repeat-button_1f501.png' },
                { word: 'required', phonetic: '/rɪˈkwaɪərd/', definition: '要求的；必须的', example: 'She usually required us to finish our homework earlier.', emoji: 'https://em-content.zobj.net/source/apple/391/clipboard_1f4cb.png' },
                { word: 'rule-free', phonetic: '/ruːl friː/', definition: '没有规则的', example: 'Would you like to work as a teacher in a rule-free school?', emoji: 'https://em-content.zobj.net/source/apple/391/dove_1f54a-fe0f.png' },
                { word: 'self-discipline', phonetic: '/ˌself ˈdɪsəplɪn/', definition: '自律', example: 'Without rules, they might not have enough self-discipline to study hard.', emoji: 'https://em-content.zobj.net/source/apple/391/person-in-lotus-position_1f9d8.png' },
                { word: 'regulation', phonetic: '/ˌreɡjuˈleɪʃn/', definition: '规章', example: 'There are strict safety regulations in this factory.', emoji: 'https://em-content.zobj.net/source/apple/391/scroll_1f4dc.png' },
                { word: 'policy', phonetic: '/ˈpɑːləsi/', definition: '政策', example: 'The company has a no-smoking policy.', emoji: 'https://em-content.zobj.net/source/apple/391/page-facing-up_1f4c4.png' },
                { word: 'comply with', phonetic: '/kəmˈplaɪ wɪθ/', definition: '遵守', example: 'You must comply with the rules.', emoji: 'https://em-content.zobj.net/source/apple/391/check-mark-button_2705.png' },
                { word: 'enforce', phonetic: '/ɪnˈfɔːrs/', definition: '执行', example: 'The police are there to enforce the law.', emoji: 'https://em-content.zobj.net/source/apple/391/police-officer_1f46e.png' },
                { word: 'dedicated', phonetic: '/ˈdedɪkeɪtɪd/', definition: '专注的；献身的', example: 'Have you ever had a really dedicated teacher?', emoji: 'https://em-content.zobj.net/source/apple/391/direct-hit_1f3af.png' },
                { word: 'detention', phonetic: '/dɪˈtenʃn/', definition: '留校察看', example: 'He got detention for being late to class.', emoji: 'https://em-content.zobj.net/source/apple/391/hourglass-not-done_23f3.png' },
            ],
        },
    ],
};
