import { IeltsTopic, SubTopic } from './data-types';

const friends: SubTopic = {
    id: 'friends',
    title: 'Friends & Sharing',
    type: '人物题',
    color: 'yellow',
    words: [
      { word: 'sociable', phonetic: '/ˈsoʊʃəbl/', definition: '好交际的', example: 'My friend is very sociable and loves parties.', emoji: 'https://em-content.zobj.net/source/apple/391/partying-face_1f973.png' },
      { word: 'loyal', phonetic: '/ˈlɔɪəl/', definition: '忠诚的', example: 'A loyal friend will always support you.', emoji: 'https://em-content.zobj.net/source/apple/391/dog-face_1f436.png' },
      { word: 'trustworthy', phonetic: '/ˈtrʌstˌwɜːrði/', definition: '值得信赖的', example: 'She is a trustworthy person; your secret is safe with her.', emoji: 'https://em-content.zobj.net/source/apple/391/handshake_1f91d.png' },
      { word: 'supportive', phonetic: '/səˈpɔːrtɪv/', definition: '支持的', example: 'My parents are very supportive of my career choice.', emoji: 'https://em-content.zobj.net/source/apple/391/thumbs-up_1f44d.png' },
      { word: 'get along with', phonetic: '/ɡet əˈlɔŋ wɪθ/', definition: '和...相处融洽', example: 'I get along with my colleagues very well.', emoji: 'https://em-content.zobj.net/source/apple/391/smiling-face-with-smiling-eyes_1f60a.png' },
      { word: 'teammate', phonetic: '/ˈtiːmmeɪt/', definition: '队友', example: 'My teammate and I practice together every day.', emoji: 'https://em-content.zobj.net/source/apple/391/people-hugging_1fac2.png' },
      { word: 'close friend', phonetic: '/kloʊs frend/', definition: '密友', example: 'She is not just a colleague, she is a close friend.', emoji: 'https://em-content.zobj.net/source/apple/391/two-hearts_1f495.png' },
      { word: 'talkative', phonetic: '/ˈtɔːkətɪv/', definition: '健谈的', example: 'My roommate is very talkative, she can talk for hours.', emoji: 'https://em-content.zobj.net/source/apple/391/speaking-head_1f5e3-fe0f.png' },
      { word: 'reliable', phonetic: '/rɪˈlaɪəbl/', definition: '可靠的', example: 'He is a very reliable employee who always meets deadlines.', emoji: 'https://em-content.zobj.net/source/apple/391/key_1f511.png' },
      { word: 'easy-going', phonetic: '/ˈiːziˌɡoʊɪŋ/', definition: '随和的', example: 'He has an easy-going personality and gets along with everyone.', emoji: 'https://em-content.zobj.net/source/apple/391/smiling-face-with-sunglasses_1f60e.png' },
      { word: 'caring', phonetic: '/ˈkerɪŋ/', definition: '有爱心的', example: 'She is a caring person who always helps others in need.', emoji: 'https://em-content.zobj.net/source/apple/391/smiling-face-with-hearts_1f970.png' },
      { word: 'topics', phonetic: '/ˈtɒpɪks/', definition: '话题', example: 'We discussed a variety of topics during our conversation.', emoji: 'https://em-content.zobj.net/source/apple/391/speech-balloon_1f4ac.png' },
      { word: 'trust', phonetic: '/trʌst/', definition: '信任', example: 'Trust is the foundation of any strong friendship.', emoji: 'https://em-content.zobj.net/source/apple/391/handshake_1f91d.png' },
      { word: 'hang out', phonetic: '/hæŋ aʊt/', definition: '一起玩；闲逛', example: 'We often hang out at the cafe after school.', emoji: 'https://em-content.zobj.net/source/apple/391/hot-beverage_2615.png' },
      { word: 'generous', phonetic: '/ˈdʒenərəs/', definition: '慷慨的', example: 'He was generous and shared his lunch with me.', emoji: 'https://em-content.zobj.net/source/apple/391/wrapped-gift_1f381.png' },
      { word: 'mutual', phonetic: '/ˈmjuːtʃuəl/', definition: '相互的', example: 'Friendship is based on mutual trust and sharing.', emoji: 'https://em-content.zobj.net/source/apple/391/handshake_1f91d.png' },
      { word: 'contribute', phonetic: '/kənˈtrɪbjuːt/', definition: '贡献', example: 'Everyone should contribute to the group project.', emoji: 'https://em-content.zobj.net/source/apple/391/palms-up-together_1f932.png' },
      { word: 'cooperate', phonetic: '/koʊˈɑːpəreɪt/', definition: '合作', example: 'We need to cooperate to finish the task on time.', emoji: 'https://em-content.zobj.net/source/apple/391/people-holding-hands_1f9d1-200d-1f91d-200d-1f91d.png' },
      { word: 'lend', phonetic: '/lend/', definition: '借出', example: 'Could you lend me your pen for a moment?', emoji: 'https://em-content.zobj.net/source/apple/391/right-arrow_27a1-fe0f.png' },
      { word: 'borrow', phonetic: '/ˈbɔːroʊ/', definition: '借入', example: 'I need to borrow a book from the library.', emoji: 'https://em-content.zobj.net/source/apple/391/left-arrow_2b05-fe0f.png' },
      { word: 'thoughtful', phonetic: '/ˈθɔːtfl/', definition: '体贴的', example: 'It was very thoughtful of you to bring flowers.', emoji: 'https://em-content.zobj.net/source/apple/391/bouquet_1f490.png' },
      { word: 'personal', phonetic: '/ˈpɜːrsənl/', definition: '个人的', example: 'It\'s important to protect your personal information.', emoji: 'https://em-content.zobj.net/source/apple/391/locked-with-key_1f510.png' },
      { word: 'information', phonetic: '/ˌɪnfərˈmeɪʃn/', definition: '信息', example: 'Never share your personal information with strangers.', emoji: 'https://em-content.zobj.net/source/apple/391/page-facing-up_1f4c4.png' },
      { word: 'ID card', phonetic: '/aɪˈdiː kɑːrd/', definition: '身份证', example: 'You need to show your ID card to get a library card.', emoji: 'https://em-content.zobj.net/source/apple/391/id-button_1f194.png' },
      { word: 'bank account', phonetic: '/bæŋk əˈkaʊnt/', definition: '银行账户', example: 'You need to open a bank account to manage your money.', emoji: 'https://em-content.zobj.net/source/apple/391/bank_1f3e6.png' },
    ],
};

const oldPeople: SubTopic = {
    id: 'old-people',
    title: 'Staying with old people',
    type: '事件题',
    color: 'blue',
    words: [
      { word: 'respectful', phonetic: '/rɪˈspektfəl/', definition: '尊敬的', example: 'It is important to be respectful to the elderly.', emoji: 'https://em-content.zobj.net/source/apple/391/person-bowing_1f647.png' },
      { word: 'patient', phonetic: '/ˈpeɪʃnt/', definition: '有耐心的', example: 'You need to be patient when communicating with older people.', emoji: 'https://em-content.zobj.net/source/apple/391/hourglass-not-done_23f3.png' },
      { word: 'generation gap', phonetic: '/ˌdʒenəˈreɪʃn ɡæp/', definition: '代沟', example: 'The generation gap can sometimes cause misunderstandings.', emoji: 'https://em-content.zobj.net/source/apple/391/busts-in-silhouette_1f465.png' },
      { word: 'wisdom', phonetic: '/ˈwɪzdəm/', definition: '智慧', example: 'Old people often have a lot of wisdom to share.', emoji: 'https://em-content.zobj.net/source/apple/391/owl_1f989.png' },
      { word: 'companionship', phonetic: '/kəmˈpænjənʃɪp/', definition: '陪伴', example: 'Elderly people often value companionship.', emoji: 'https://em-content.zobj.net/source/apple/391/people-holding-hands_1f9d1-200d-1f91d-200d-1f9d1.png' },
      { word: 'caretakers', phonetic: '/ˈkerˌteɪkərz/', definition: '照顾者；看护人', example: 'Caretakers play a vital role in supporting the elderly.', emoji: 'https://em-content.zobj.net/source/apple/391/woman-health-worker_1f469-200d-2695-fe0f.png' },
      { word: 'caregivers', phonetic: '/ˈkerˌɡɪvərz/', definition: '照料者', example: 'Many adult children become caregivers for their aging parents.', emoji: 'https://em-content.zobj.net/source/apple/391/house_1f3e0.png' },
      { word: 'gentle', phonetic: '/ˈdʒentl/', definition: '温柔的', example: 'He has a gentle voice that is very calming.', emoji: 'https://em-content.zobj.net/source/apple/391/dove_1f54a-fe0f.png' },
      { word: 'thoughtful', phonetic: '/ˈθɔːtfl/', definition: '体贴的', example: 'It was very thoughtful of you to bring flowers.', emoji: 'https://em-content.zobj.net/source/apple/391/bouquet_1f490.png' },
      { word: 'wise', phonetic: '/waɪz/', definition: '明智的', example: 'My grandfather is a wise man who gives great advice.', emoji: 'https://em-content.zobj.net/source/apple/391/owl_1f989.png' },
      { word: 'rewarding', phonetic: '/rɪˈwɔːrdɪŋ/', definition: '有益的；值得的', example: 'Spending time with my grandparents is a rewarding experience.', emoji: 'https://em-content.zobj.net/source/apple/391/sparkling-heart_1f496.png' },
      { word: 'keep them company', phonetic: '/kiːp ðəm ˈkʌmpəni/', definition: '陪伴他们', example: 'I often visit my grandmother to keep her company.', emoji: 'https://em-content.zobj.net/source/apple/391/hot-beverage_2615.png' },
      { word: 'accompany', phonetic: '/əˈkʌmpəni/', definition: '陪伴；陪同', example: 'I will accompany you to the doctor\'s appointment.', emoji: 'https://em-content.zobj.net/source/apple/391/woman-walking_1f6b6-200d-2640-fe0f.png' },
    ],
};

const chatting: SubTopic = {
    id: 'chatting',
    title: 'Chatting',
    type: '事件题',
    color: 'blue',
    words: [
      { word: 'converse', phonetic: '/kənˈvɜːrs/', definition: '交谈', example: 'It was pleasant to converse with her.', emoji: 'https://em-content.zobj.net/source/apple/391/speaking-head_1f5e3-fe0f.png' },
      { word: 'conversation', phonetic: '/ˌkɑːnvərˈseɪʃn/', definition: '交谈；谈话', example: 'We had a long conversation about our future plans.', emoji: '🗣️' },
      { word: 'small talk', phonetic: '/smɔːl tɔːk/', definition: '闲聊', example: 'We made small talk while waiting for the bus.', emoji: 'https://em-content.zobj.net/source/apple/391/speech-balloon_1f4ac.png' },
      { word: 'catch up', phonetic: '/kætʃ ʌp/', definition: '叙旧 / 更新近况', example: 'Let\'s meet for coffee and catch up on each other\'s lives.', emoji: 'https://em-content.zobj.net/source/apple/391/hot-beverage_2615.png' },
      { word: 'engage in', phonetic: '/ɪnˈɡeɪdʒ ɪn/', definition: '参与', example: 'He likes to engage in deep conversations.', emoji: 'https://em-content.zobj.net/source/apple/391/woman-raising-hand_1f64b-200d-2640-fe0f.png' },
      { word: 'stay in touch', phonetic: '/steɪ ɪn tʌtʃ/', definition: '保持联系', example: 'We promised to stay in touch after we graduated.', emoji: '📧' },
      { word: 'lively', phonetic: '/ˈlaɪvli/', definition: '热烈的；活泼的', example: 'The discussion became more lively when we talked about movies.', emoji: '🎉' },
      { word: 'school stuff', phonetic: '/skuːl stʌf/', definition: '学校的事情', example: 'We usually talk about school stuff like homework and exams.', emoji: '🏫' },
      { word: 'private', phonetic: '/ˈpraɪvət/', definition: '私人的', example: 'Some topics are too private to discuss with everyone.', emoji: '🤫' },
      { word: 'face-to-face', phonetic: '/ˌfeɪs tə ˈfeɪs/', definition: '面对面', example: 'I prefer having face-to-face conversations.', emoji: '🧑‍🤝‍🧑' },
      { word: 'social media', phonetic: '/ˈsoʊʃl ˈmiːdiə/', definition: '社交媒体', example: 'We stay in touch through social media apps.', emoji: '📱' },
      { word: 'text messages', phonetic: '/tekst ˈmesɪdʒɪz/', definition: '短信', example: 'I prefer sending text messages because it\'s quick.', emoji: '💬' },
      { word: 'video call', phonetic: '/ˈvɪdioʊ kɔːl/', definition: '视频通话', example: 'I had a video call with my family last night.', emoji: '📹' },
      { word: 'express emotions', phonetic: '/ɪkˈspres ɪˈmoʊʃənz/', definition: '表达情感', example: 'It\'s easier to express emotions when you talk face-to-face.', emoji: '😄' },
      { word: 'misunderstand', phonetic: '/ˌmɪsʌndərˈstænd/', definition: '误解', example: 'Don\'t misunderstand me; I\'m not criticizing you.', emoji: '🤔' },
      { word: 'misunderstanding', phonetic: '/ˌmɪsʌndərˈstændɪŋ/', definition: '误会', example: 'There was a misunderstanding, but we cleared it up.', emoji: '😕' },
      { word: 'make up', phonetic: '/meɪk ʌp/', definition: '和好', example: 'Friends sometimes argue, but they always make up.', emoji: '🤗' },
      { word: 'respect each other', phonetic: '/rɪˈspekt iːtʃ ˈʌðər/', definition: '互相尊重', example: 'Good communication requires that we respect each other\'s opinions.', emoji: '🤝' },
    ],
};

const goingOut: SubTopic = {
    id: 'going-out',
    title: 'Going Out',
    type: '事件题',
    color: 'yellow',
    isNew: true,
    words: [
      { word: 'meet up', phonetic: '/miːt ʌp/', definition: '见面；聚会', example: 'Let\'s meet up for coffee this weekend.', emoji: 'https://em-content.zobj.net/source/apple/391/hot-beverage_2615.png' },
      { word: 'hang out', phonetic: '/hæŋ aʊt/', definition: '一起玩；闲逛', example: 'We like to hang out at the park on sunny days.', emoji: 'https://em-content.zobj.net/source/apple/391/deciduous-tree_1f333.png' },
      { word: 'socialize', phonetic: '/ˈsoʊʃəlaɪz/', definition: '社交', example: 'Parties are a great opportunity to socialize with new people.', emoji: 'https://em-content.zobj.net/source/apple/391/busts-in-silhouette_1f465.png' },
      { word: 'gathering', phonetic: '/ˈɡæðərɪŋ/', definition: '聚会', example: 'We\'re having a small gathering at my place on Friday.', emoji: 'https://em-content.zobj.net/source/apple/391/party-popper_1f389.png' },
      { word: 'get-together', phonetic: '/ˈɡet təˌɡeðər/', definition: '非正式的社交聚会', example: 'It was a casual get-together with a few close friends.', emoji: 'https://em-content.zobj.net/source/apple/391/people-hugging_1fac2.png' },
      { word: 'celebrate', phonetic: '/ˈseləbreɪt/', definition: '庆祝', example: 'We went out to a fancy restaurant to celebrate her birthday.', emoji: 'https://em-content.zobj.net/source/apple/391/partying-face_1f973.png' },
      { word: 'occasion', phonetic: '/əˈkeɪʒən/', definition: '场合', example: 'A wedding is a very special occasion.', emoji: 'https://em-content.zobj.net/source/apple/391/wrapped-gift_1f381.png' },
      { word: 'venue', phonetic: '/ˈvenjuː/', definition: '场所', example: 'Have you chosen a venue for the party yet?', emoji: 'https://em-content.zobj.net/source/apple/391/round-pushpin_1f4cd.png' },
      { word: 'atmosphere', phonetic: '/ˈætməsfɪər/', definition: '氛围', example: 'The cafe has a cozy and relaxed atmosphere.', emoji: 'https://em-content.zobj.net/source/apple/391/candle_1f56f-fe0f.png' },
      { word: 'lively', phonetic: '/ˈlaɪvli/', definition: '热闹的', example: 'The bar was very lively on Saturday night.', emoji: 'https://em-content.zobj.net/source/apple/391/woman-dancing_1f483.png' },
      { word: 'nightlife', phonetic: '/ˈnaɪtlaɪf/', definition: '夜生活', example: 'The city is famous for its vibrant nightlife.', emoji: 'https://em-content.zobj.net/source/apple/391/night-with-stars_1f303.png' },
      { word: 'entertainment', phonetic: '/ˌentərˈteɪnmənt/', definition: '娱乐', example: 'There are many entertainment options, such as cinemas and theaters.', emoji: 'https://em-content.zobj.net/source/apple/391/performing-arts_1f3ad.png' },
      { word: 'book a table', phonetic: '/bʊk ə ˈteɪbl/', definition: '订座', example: 'I\'ll call the restaurant and book a table for four.', emoji: 'https://em-content.zobj.net/source/apple/391/telephone_260e-fe0f.png' },
      { word: 'reservation', phonetic: '/ˌrezərˈveɪʃn/', definition: '预定', example: 'Do you have a reservation? The restaurant is full tonight.', emoji: 'https://em-content.zobj.net/source/apple/391/spiral-calendar_1f5d3-fe0f.png' },
      { word: 'go for a drink', phonetic: '/ɡoʊ fər ə drɪŋk/', definition: '去喝一杯', example: 'After work, we decided to go for a drink.', emoji: 'https://em-content.zobj.net/source/apple/391/clinking-beer-mugs_1f37b.png' },
      { word: 'snacks', phonetic: '/snæks/', definition: '零食', example: 'We packed some snacks like chips and fruit for the picnic.', emoji: 'https://em-content.zobj.net/source/apple/391/pretzel_1f968.png' },
      { word: 'pack some food', phonetic: '/pæk sʌm fuːd/', definition: '带点吃的', example: 'Let\'s pack some food for the road trip.', emoji: 'https://em-content.zobj.net/source/apple/391/bento-box_1f371.png' },
      { word: 'bottled water', phonetic: '/ˈbɒtld ˈwɔːtər/', definition: '瓶装水', example: 'It\'s always a good idea to bring some bottled water when you go hiking.', emoji: 'https://em-content.zobj.net/source/apple/391/droplet_1f4a7.png' },
      { word: 'energy bar', phonetic: '/ˈenərdʒi bɑːr/', definition: '能量棒', example: 'An energy bar can give you a quick boost of energy during a workout.', emoji: 'https://em-content.zobj.net/source/apple/391/chocolate-bar_1f36b.png' },
      { word: 'homemade food', phonetic: '/ˈhoʊmˈmeɪd fuːd/', definition: '自带食物', example: 'I prefer homemade food because it\'s healthier and cheaper.', emoji: 'https://em-content.zobj.net/source/apple/391/sandwich_1f96a.png' },
      { word: 'just in case', phonetic: '/dʒʌst ɪn keɪs/', definition: '以防万一', example: 'I\'ll bring an umbrella, just in case it rains.', emoji: 'https://em-content.zobj.net/source/apple/391/umbrella_2602.png' },
      { word: 'mobile phone / cellphone', phonetic: '/ˈmoʊbl foʊn / ˈselˌfoʊn/', definition: '手机', example: 'I can\'t imagine my life without a mobile phone.', emoji: 'https://em-content.zobj.net/source/apple/391/mobile-phone_1f4f1.png' },
      { word: 'take my phone with me', phonetic: '/teɪk maɪ foʊn wɪθ mi/', definition: '随身带手机', example: 'I always take my phone with me when I leave the house.', emoji: 'https://em-content.zobj.net/source/apple/391/selfie_1f933.png' },
      { word: 'cannot live without my phone', phonetic: '/ˈkænɒt lɪv wɪˈðaʊt maɪ foʊn/', definition: '离不开手机', example: 'Honestly, I feel like I cannot live without my phone these days.', emoji: 'https://em-content.zobj.net/source/apple/391/face-screaming-in-fear_1f631.png' },
      { word: 'check messages', phonetic: '/tʃek ˈmesɪdʒɪz/', definition: '看消息', example: 'I need to check my messages to see if she replied.', emoji: 'https://em-content.zobj.net/source/apple/391/speech-balloon_1f4ac.png' },
      { word: 'navigation app / map app', phonetic: '/ˌnævɪˈɡeɪʃn æp / mæp æp/', definition: '导航应用', example: 'I use a navigation app to find the best route.', emoji: 'https://em-content.zobj.net/source/apple/391/world-map_1f5fa-fe0f.png' },
      { word: 'stay connected', phonetic: '/steɪ kəˈnektɪd/', definition: '保持联系', example: 'My phone helps me stay connected with friends and family.', emoji: 'https://em-content.zobj.net/source/apple/391/link_1f517.png' },
      { word: 'cash', phonetic: '/kæʃ/', definition: '现金', example: 'Some small shops only accept cash.', emoji: 'https://em-content.zobj.net/source/apple/391/dollar-banknote_1f4b5.png' },
      { word: 'credit card', phonetic: '/ˈkredɪt kɑːrd/', definition: '信用卡', example: 'I usually pay with my credit card for larger purchases.', emoji: 'https://em-content.zobj.net/source/apple/391/credit-card_1f4b3.png' },
      { word: 'mobile payment', phonetic: '/ˈmoʊbl ˈpeɪmənt/', definition: '手机支付', example: 'Mobile payment is very convenient and popular now.', emoji: 'https://em-content.zobj.net/source/apple/391/mobile-phone-with-arrow_1f4f2.png' },
      { word: 'e-wallet', phonetic: '/ˈiː ˌwɒlɪt/', definition: '电子钱包', example: 'I have several payment methods linked to my e-wallet.', emoji: 'https://em-content.zobj.net/source/apple/391/purse_1f45b.png' },
      { word: 'QR code', phonetic: '/kjuː ɑːr koʊd/', definition: '二维码', example: 'You can scan the QR code to pay.', emoji: 'https://em-content.zobj.net/source/apple/391/camera-with-flash_1f4f8.png' },
      { word: 'rarely use cash', phonetic: '/ˈrerli juːz kæʃ/', definition: '很少用现金', example: 'I rarely use cash because mobile payments are so common.', emoji: 'https://em-content.zobj.net/source/apple/391/money-with-wings_1f4b8.png' },
      { word: 'only for small shops', phonetic: '/ˈoʊnli fɔːr smɔːl ʃɒps/', definition: '只在小店用', example: 'I carry a little cash, but only for small shops.', emoji: 'https://em-content.zobj.net/source/apple/391/convenience-store_1f3ea.png' },
      { word: 'go for a walk', phonetic: '/ɡoʊ fɔːr ə wɔːk/', definition: '出去散步', example: 'Let\'s go for a walk in the park after dinner.', emoji: 'https://em-content.zobj.net/source/apple/391/person-walking_1f6b6.png' },
      { word: 'hang out with friends', phonetic: '/hæŋ aʊt wɪθ frendz/', definition: '和朋友出去玩', example: 'I like to hang out with friends on weekends.', emoji: 'https://em-content.zobj.net/source/apple/391/people-holding-hands_1f9d1-200d-1f91d-200d-1f9d1.png' },
      { word: 'daily life', phonetic: '/ˈdeɪli laɪf/', definition: '日常生活', example: 'Going out for a walk is a simple pleasure in my daily life.', emoji: 'https://em-content.zobj.net/source/apple/391/calendar_1f4c5.png' },
      { word: 'just a habit', phonetic: '/dʒʌst ə ˈhæbɪt/', definition: '这就是习惯', example: 'Checking my phone first thing in the morning is just a habit.', emoji: 'https://em-content.zobj.net/source/apple/391/counterclockwise-arrows-button_1f504.png' },
      { word: 'depends on the situation', phonetic: '/dɪˈpendz ɒn ðə ˌsɪtʃuˈeɪʃn/', definition: '看情况', example: 'Whether I go out or stay in depends on the situation.', emoji: 'https://em-content.zobj.net/source/apple/391/thinking-face_1f914.png' },
    ],
};

export const peopleTopic: IeltsTopic = {
    title: '话题: 人物与社交',
    subTopics: [
      friends,
      oldPeople,
      chatting,
      goingOut,
    ],
};
